//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

namespace PayerLib.Riversamento.RichiestaPagamentoTelematico
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/")]
    [System.Xml.Serialization.XmlRootAttribute("RPT", Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/",
        IsNullable = false)]
    public partial class ctRichiestaPagamentoTelematico
    {

        private string versioneOggettoField;

        private ctDominio dominioField;

        private string identificativoMessaggioRichiestaField;

        private System.DateTime dataOraMessaggioRichiestaField;

        private stAutenticazioneSoggetto autenticazioneSoggettoField;

        private ctSoggettoVersante soggettoVersanteField;

        private ctSoggettoPagatore soggettoPagatoreField;

        private ctEnteBeneficiario enteBeneficiarioField;

        private ctDatiVersamentoRPT datiVersamentoField;

        /// <remarks/>
        public string versioneOggetto
        {
            get { return this.versioneOggettoField; }
            set { this.versioneOggettoField = value; }
        }

        /// <remarks/>
        public ctDominio dominio
        {
            get { return this.dominioField; }
            set { this.dominioField = value; }
        }

        /// <remarks/>
        public string identificativoMessaggioRichiesta
        {
            get { return this.identificativoMessaggioRichiestaField; }
            set { this.identificativoMessaggioRichiestaField = value; }
        }

        /// <remarks/>
        public System.DateTime dataOraMessaggioRichiesta
        {
            get { return this.dataOraMessaggioRichiestaField; }
            set { this.dataOraMessaggioRichiestaField = value; }
        }

        /// <remarks/>
        public stAutenticazioneSoggetto autenticazioneSoggetto
        {
            get { return this.autenticazioneSoggettoField; }
            set { this.autenticazioneSoggettoField = value; }
        }

        /// <remarks/>
        public ctSoggettoVersante soggettoVersante
        {
            get { return this.soggettoVersanteField; }
            set { this.soggettoVersanteField = value; }
        }

        /// <remarks/>
        public ctSoggettoPagatore soggettoPagatore
        {
            get { return this.soggettoPagatoreField; }
            set { this.soggettoPagatoreField = value; }
        }

        /// <remarks/>
        public ctEnteBeneficiario enteBeneficiario
        {
            get { return this.enteBeneficiarioField; }
            set { this.enteBeneficiarioField = value; }
        }

        /// <remarks/>
        public ctDatiVersamentoRPT datiVersamento
        {
            get { return this.datiVersamentoField; }
            set { this.datiVersamentoField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/")]
    public partial class ctDominio
    {

        private string identificativoDominioField;

        private string identificativoStazioneRichiedenteField;

        /// <remarks/>
        public string identificativoDominio
        {
            get { return this.identificativoDominioField; }
            set { this.identificativoDominioField = value; }
        }

        /// <remarks/>
        public string identificativoStazioneRichiedente
        {
            get { return this.identificativoStazioneRichiedenteField; }
            set { this.identificativoStazioneRichiedenteField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/")]
    public partial class ctAllegatoRicevuta
    {

        private stTipoAllegatoRicevuta tipoAllegatoRicevutaField;

        private byte[] testoAllegatoField;

        /// <remarks/>
        public stTipoAllegatoRicevuta tipoAllegatoRicevuta
        {
            get { return this.tipoAllegatoRicevutaField; }
            set { this.tipoAllegatoRicevutaField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public byte[] testoAllegato
        {
            get { return this.testoAllegatoField; }
            set { this.testoAllegatoField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/")]
    public enum stTipoAllegatoRicevuta
    {

        /// <remarks/>
        ES,

        /// <remarks/>
        BD,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/")]
    public partial class ctDatiSingoloPagamentoRT
    {

        private decimal singoloImportoPagatoField;

        private string esitoSingoloPagamentoField;

        private System.DateTime dataEsitoSingoloPagamentoField;

        private string identificativoUnivocoRiscossioneField;

        private string causaleVersamentoField;

        private string datiSpecificiRiscossioneField;

        private ctAllegatoRicevuta allegatoRicevutaField;

        /// <remarks/>
        public decimal singoloImportoPagato
        {
            get { return this.singoloImportoPagatoField; }
            set { this.singoloImportoPagatoField = value; }
        }

        /// <remarks/>
        public string esitoSingoloPagamento
        {
            get { return this.esitoSingoloPagamentoField; }
            set { this.esitoSingoloPagamentoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime dataEsitoSingoloPagamento
        {
            get { return this.dataEsitoSingoloPagamentoField; }
            set { this.dataEsitoSingoloPagamentoField = value; }
        }

        /// <remarks/>
        public string identificativoUnivocoRiscossione
        {
            get { return this.identificativoUnivocoRiscossioneField; }
            set { this.identificativoUnivocoRiscossioneField = value; }
        }

        /// <remarks/>
        public string causaleVersamento
        {
            get { return this.causaleVersamentoField; }
            set { this.causaleVersamentoField = value; }
        }

        /// <remarks/>
        public string datiSpecificiRiscossione
        {
            get { return this.datiSpecificiRiscossioneField; }
            set { this.datiSpecificiRiscossioneField = value; }
        }

        /// <remarks/>
        public ctAllegatoRicevuta allegatoRicevuta
        {
            get { return this.allegatoRicevutaField; }
            set { this.allegatoRicevutaField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/")]
    public partial class ctDatiVersamentoRT
    {

        private stCodiceEsitoPagamento codiceEsitoPagamentoField;

        private decimal importoTotalePagatoField;

        private string identificativoUnivocoVersamentoField;

        private string codiceContestoPagamentoField;

        private ctDatiSingoloPagamentoRT[] datiSingoloPagamentoField;

        /// <remarks/>
        public stCodiceEsitoPagamento codiceEsitoPagamento
        {
            get { return this.codiceEsitoPagamentoField; }
            set { this.codiceEsitoPagamentoField = value; }
        }

        /// <remarks/>
        public decimal importoTotalePagato
        {
            get { return this.importoTotalePagatoField; }
            set { this.importoTotalePagatoField = value; }
        }

        /// <remarks/>
        public string identificativoUnivocoVersamento
        {
            get { return this.identificativoUnivocoVersamentoField; }
            set { this.identificativoUnivocoVersamentoField = value; }
        }

        /// <remarks/>
        public string CodiceContestoPagamento
        {
            get { return this.codiceContestoPagamentoField; }
            set { this.codiceContestoPagamentoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("datiSingoloPagamento")]
        public ctDatiSingoloPagamentoRT[] datiSingoloPagamento
        {
            get { return this.datiSingoloPagamentoField; }
            set { this.datiSingoloPagamentoField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/")]
    public enum stCodiceEsitoPagamento
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/")]
    public partial class ctIdentificativoUnivoco
    {

        private stTipoIdentificativoUnivoco tipoIdentificativoUnivocoField;

        private string codiceIdentificativoUnivocoField;

        /// <remarks/>
        public stTipoIdentificativoUnivoco tipoIdentificativoUnivoco
        {
            get
            {
                return this.tipoIdentificativoUnivocoField;
            }
            set
            {
                this.tipoIdentificativoUnivocoField = value;
            }
        }

        /// <remarks/>
        public string codiceIdentificativoUnivoco
        {
            get
            {
                return this.codiceIdentificativoUnivocoField;
            }
            set
            {
                this.codiceIdentificativoUnivocoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/")]
    public enum stTipoIdentificativoUnivoco
    {

        /// <remarks/>
        G,

        /// <remarks/>
        A,

        /// <remarks/>
        B,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/")]
    public partial class ctIstitutoAttestante
    {

        private ctIdentificativoUnivoco identificativoUnivocoAttestanteField;

        private string denominazioneAttestanteField;

        private string codiceUnitOperAttestanteField;

        private string denomUnitOperAttestanteField;

        private string indirizzoAttestanteField;

        private string civicoAttestanteField;

        private string capAttestanteField;

        private string localitaAttestanteField;

        private string provinciaAttestanteField;

        private string nazioneAttestanteField;

        /// <remarks/>
        public ctIdentificativoUnivoco identificativoUnivocoAttestante
        {
            get { return this.identificativoUnivocoAttestanteField; }
            set { this.identificativoUnivocoAttestanteField = value; }
        }

        /// <remarks/>
        public string denominazioneAttestante
        {
            get { return this.denominazioneAttestanteField; }
            set { this.denominazioneAttestanteField = value; }
        }

        /// <remarks/>
        public string codiceUnitOperAttestante
        {
            get { return this.codiceUnitOperAttestanteField; }
            set { this.codiceUnitOperAttestanteField = value; }
        }

        /// <remarks/>
        public string denomUnitOperAttestante
        {
            get { return this.denomUnitOperAttestanteField; }
            set { this.denomUnitOperAttestanteField = value; }
        }

        /// <remarks/>
        public string indirizzoAttestante
        {
            get { return this.indirizzoAttestanteField; }
            set { this.indirizzoAttestanteField = value; }
        }

        /// <remarks/>
        public string civicoAttestante
        {
            get { return this.civicoAttestanteField; }
            set { this.civicoAttestanteField = value; }
        }

        /// <remarks/>
        public string capAttestante
        {
            get { return this.capAttestanteField; }
            set { this.capAttestanteField = value; }
        }

        /// <remarks/>
        public string localitaAttestante
        {
            get { return this.localitaAttestanteField; }
            set { this.localitaAttestanteField = value; }
        }

        /// <remarks/>
        public string provinciaAttestante
        {
            get { return this.provinciaAttestanteField; }
            set { this.provinciaAttestanteField = value; }
        }

        /// <remarks/>
        public string nazioneAttestante
        {
            get { return this.nazioneAttestanteField; }
            set { this.nazioneAttestanteField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/")]
    public partial class ctDatiMarcaBolloDigitale
    {

        private stTipoBollo tipoBolloField;

        private string hashDocumentoField;

        private string provinciaResidenzaField;

        /// <remarks/>
        public stTipoBollo tipoBollo
        {
            get { return this.tipoBolloField; }
            set { this.tipoBolloField = value; }
        }

        /// <remarks/>
        public string hashDocumento
        {
            get { return this.hashDocumentoField; }
            set { this.hashDocumentoField = value; }
        }

        /// <remarks/>
        public string provinciaResidenza
        {
            get { return this.provinciaResidenzaField; }
            set { this.provinciaResidenzaField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/")]
    public enum stTipoBollo
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")] Item01,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/")]
    public partial class ctDatiSingoloVersamentoRPT
    {

        private decimal importoSingoloVersamentoField;

        private decimal commissioneCaricoPAField;

        private bool commissioneCaricoPAFieldSpecified;

        private string ibanAccreditoField;

        private string bicAccreditoField;

        private string ibanAppoggioField;

        private string bicAppoggioField;

        private string credenzialiPagatoreField;

        private string causaleVersamentoField;

        private string datiSpecificiRiscossioneField;

        private ctDatiMarcaBolloDigitale datiMarcaBolloDigitaleField;

        /// <remarks/>
        public decimal importoSingoloVersamento
        {
            get { return this.importoSingoloVersamentoField; }
            set { this.importoSingoloVersamentoField = value; }
        }

        /// <remarks/>
        public decimal commissioneCaricoPA
        {
            get { return this.commissioneCaricoPAField; }
            set { this.commissioneCaricoPAField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool commissioneCaricoPASpecified
        {
            get { return this.commissioneCaricoPAFieldSpecified; }
            set { this.commissioneCaricoPAFieldSpecified = value; }
        }

        /// <remarks/>
        public string ibanAccredito
        {
            get { return this.ibanAccreditoField; }
            set { this.ibanAccreditoField = value; }
        }

        /// <remarks/>
        public string bicAccredito
        {
            get { return this.bicAccreditoField; }
            set { this.bicAccreditoField = value; }
        }

        /// <remarks/>
        public string ibanAppoggio
        {
            get { return this.ibanAppoggioField; }
            set { this.ibanAppoggioField = value; }
        }

        /// <remarks/>
        public string bicAppoggio
        {
            get { return this.bicAppoggioField; }
            set { this.bicAppoggioField = value; }
        }

        /// <remarks/>
        public string credenzialiPagatore
        {
            get { return this.credenzialiPagatoreField; }
            set { this.credenzialiPagatoreField = value; }
        }

        /// <remarks/>
        public string causaleVersamento
        {
            get { return this.causaleVersamentoField; }
            set { this.causaleVersamentoField = value; }
        }

        /// <remarks/>
        public string datiSpecificiRiscossione
        {
            get { return this.datiSpecificiRiscossioneField; }
            set { this.datiSpecificiRiscossioneField = value; }
        }

        /// <remarks/>
        public ctDatiMarcaBolloDigitale datiMarcaBolloDigitale
        {
            get { return this.datiMarcaBolloDigitaleField; }
            set { this.datiMarcaBolloDigitaleField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/")]
    public partial class ctDatiVersamentoRPT
    {

        private System.DateTime dataEsecuzionePagamentoField;

        private decimal importoTotaleDaVersareField;

        private stTipoVersamento tipoVersamentoField;

        private string identificativoUnivocoVersamentoField;

        private string codiceContestoPagamentoField;

        private string ibanAddebitoField;

        private string bicAddebitoField;

        private stFirmaRicevuta firmaRicevutaField;

        private ctDatiSingoloVersamentoRPT[] datiSingoloVersamentoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime dataEsecuzionePagamento
        {
            get { return this.dataEsecuzionePagamentoField; }
            set { this.dataEsecuzionePagamentoField = value; }
        }

        /// <remarks/>
        public decimal importoTotaleDaVersare
        {
            get { return this.importoTotaleDaVersareField; }
            set { this.importoTotaleDaVersareField = value; }
        }

        /// <remarks/>
        public stTipoVersamento tipoVersamento
        {
            get { return this.tipoVersamentoField; }
            set { this.tipoVersamentoField = value; }
        }

        /// <remarks/>
        public string identificativoUnivocoVersamento
        {
            get { return this.identificativoUnivocoVersamentoField; }
            set { this.identificativoUnivocoVersamentoField = value; }
        }

        /// <remarks/>
        public string codiceContestoPagamento
        {
            get { return this.codiceContestoPagamentoField; }
            set { this.codiceContestoPagamentoField = value; }
        }

        /// <remarks/>
        public string ibanAddebito
        {
            get { return this.ibanAddebitoField; }
            set { this.ibanAddebitoField = value; }
        }

        /// <remarks/>
        public string bicAddebito
        {
            get { return this.bicAddebitoField; }
            set { this.bicAddebitoField = value; }
        }

        /// <remarks/>
        public stFirmaRicevuta firmaRicevuta
        {
            get { return this.firmaRicevutaField; }
            set { this.firmaRicevutaField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("datiSingoloVersamento")]
        public ctDatiSingoloVersamentoRPT[] datiSingoloVersamento
        {
            get { return this.datiSingoloVersamentoField; }
            set { this.datiSingoloVersamentoField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/")]
    public enum stTipoVersamento
    {

        /// <remarks/>
        BBT,

        /// <remarks/>
        BP,

        /// <remarks/>
        AD,

        /// <remarks/>
        CP,

        /// <remarks/>
        PO,

        /// <remarks/>
        OBEP,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/")]
    public enum stFirmaRicevuta
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")] Item0,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")] Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")] Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")] Item4,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/")]
    public partial class ctIdentificativoUnivocoPersonaG
    {

        private stTipoIdentificativoUnivocoPersG tipoIdentificativoUnivocoField;

        private string codiceIdentificativoUnivocoField;

        /// <remarks/>
        public stTipoIdentificativoUnivocoPersG tipoIdentificativoUnivoco
        {
            get
            {
                return this.tipoIdentificativoUnivocoField;
            }
            set
            {
                this.tipoIdentificativoUnivocoField = value;
            }
        }

        /// <remarks/>
        public string codiceIdentificativoUnivoco
        {
            get
            {
                return this.codiceIdentificativoUnivocoField;
            }
            set
            {
                this.codiceIdentificativoUnivocoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/")]
    public enum stTipoIdentificativoUnivocoPersG
    {

        /// <remarks/>
        G,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/")]
    public partial class ctEnteBeneficiario
    {

        private ctIdentificativoUnivocoPersonaG identificativoUnivocoBeneficiarioField;

        private string denominazioneBeneficiarioField;

        private string codiceUnitOperBeneficiarioField;

        private string denomUnitOperBeneficiarioField;

        private string indirizzoBeneficiarioField;

        private string civicoBeneficiarioField;

        private string capBeneficiarioField;

        private string localitaBeneficiarioField;

        private string provinciaBeneficiarioField;

        private string nazioneBeneficiarioField;

        /// <remarks/>
        public ctIdentificativoUnivocoPersonaG identificativoUnivocoBeneficiario
        {
            get { return this.identificativoUnivocoBeneficiarioField; }
            set { this.identificativoUnivocoBeneficiarioField = value; }
        }

        /// <remarks/>
        public string denominazioneBeneficiario
        {
            get { return this.denominazioneBeneficiarioField; }
            set { this.denominazioneBeneficiarioField = value; }
        }

        /// <remarks/>
        public string codiceUnitOperBeneficiario
        {
            get { return this.codiceUnitOperBeneficiarioField; }
            set { this.codiceUnitOperBeneficiarioField = value; }
        }

        /// <remarks/>
        public string denomUnitOperBeneficiario
        {
            get { return this.denomUnitOperBeneficiarioField; }
            set { this.denomUnitOperBeneficiarioField = value; }
        }

        /// <remarks/>
        public string indirizzoBeneficiario
        {
            get { return this.indirizzoBeneficiarioField; }
            set { this.indirizzoBeneficiarioField = value; }
        }

        /// <remarks/>
        public string civicoBeneficiario
        {
            get { return this.civicoBeneficiarioField; }
            set { this.civicoBeneficiarioField = value; }
        }

        /// <remarks/>
        public string capBeneficiario
        {
            get { return this.capBeneficiarioField; }
            set { this.capBeneficiarioField = value; }
        }

        /// <remarks/>
        public string localitaBeneficiario
        {
            get { return this.localitaBeneficiarioField; }
            set { this.localitaBeneficiarioField = value; }
        }

        /// <remarks/>
        public string provinciaBeneficiario
        {
            get { return this.provinciaBeneficiarioField; }
            set { this.provinciaBeneficiarioField = value; }
        }

        /// <remarks/>
        public string nazioneBeneficiario
        {
            get { return this.nazioneBeneficiarioField; }
            set { this.nazioneBeneficiarioField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/")]
    public partial class ctSoggettoPagatore
    {

        private ctIdentificativoUnivocoPersonaFG identificativoUnivocoPagatoreField;

        private string anagraficaPagatoreField;

        private string indirizzoPagatoreField;

        private string civicoPagatoreField;

        private string capPagatoreField;

        private string localitaPagatoreField;

        private string provinciaPagatoreField;

        private string nazionePagatoreField;

        private string emailPagatoreField;

        /// <remarks/>
        public ctIdentificativoUnivocoPersonaFG identificativoUnivocoPagatore
        {
            get { return this.identificativoUnivocoPagatoreField; }
            set { this.identificativoUnivocoPagatoreField = value; }
        }

        /// <remarks/>
        public string anagraficaPagatore
        {
            get { return this.anagraficaPagatoreField; }
            set { this.anagraficaPagatoreField = value; }
        }

        /// <remarks/>
        public string indirizzoPagatore
        {
            get { return this.indirizzoPagatoreField; }
            set { this.indirizzoPagatoreField = value; }
        }

        /// <remarks/>
        public string civicoPagatore
        {
            get { return this.civicoPagatoreField; }
            set { this.civicoPagatoreField = value; }
        }

        /// <remarks/>
        public string capPagatore
        {
            get { return this.capPagatoreField; }
            set { this.capPagatoreField = value; }
        }

        /// <remarks/>
        public string localitaPagatore
        {
            get { return this.localitaPagatoreField; }
            set { this.localitaPagatoreField = value; }
        }

        /// <remarks/>
        public string provinciaPagatore
        {
            get { return this.provinciaPagatoreField; }
            set { this.provinciaPagatoreField = value; }
        }

        /// <remarks/>
        public string nazionePagatore
        {
            get { return this.nazionePagatoreField; }
            set { this.nazionePagatoreField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("e-mailPagatore")]
        public string emailPagatore
        {
            get { return this.emailPagatoreField; }
            set { this.emailPagatoreField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/")]
    public partial class ctIdentificativoUnivocoPersonaFG
    {

        private stTipoIdentificativoUnivocoPersFG tipoIdentificativoUnivocoField;

        private string codiceIdentificativoUnivocoField;

        /// <remarks/>
        public stTipoIdentificativoUnivocoPersFG tipoIdentificativoUnivoco
        {
            get { return this.tipoIdentificativoUnivocoField; }
            set { this.tipoIdentificativoUnivocoField = value; }
        }

        /// <remarks/>
        public string codiceIdentificativoUnivoco
        {
            get { return this.codiceIdentificativoUnivocoField; }
            set { this.codiceIdentificativoUnivocoField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/")]
    public enum stTipoIdentificativoUnivocoPersFG
    {

        /// <remarks/>
        F,

        /// <remarks/>
        G,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/")]
    public partial class ctSoggettoVersante
    {

        private ctIdentificativoUnivocoPersonaFG identificativoUnivocoVersanteField;

        private string anagraficaVersanteField;

        private string indirizzoVersanteField;

        private string civicoVersanteField;

        private string capVersanteField;

        private string localitaVersanteField;

        private string provinciaVersanteField;

        private string nazioneVersanteField;

        private string emailVersanteField;

        /// <remarks/>
        public ctIdentificativoUnivocoPersonaFG identificativoUnivocoVersante
        {
            get { return this.identificativoUnivocoVersanteField; }
            set { this.identificativoUnivocoVersanteField = value; }
        }

        /// <remarks/>
        public string anagraficaVersante
        {
            get { return this.anagraficaVersanteField; }
            set { this.anagraficaVersanteField = value; }
        }

        /// <remarks/>
        public string indirizzoVersante
        {
            get { return this.indirizzoVersanteField; }
            set { this.indirizzoVersanteField = value; }
        }

        /// <remarks/>
        public string civicoVersante
        {
            get { return this.civicoVersanteField; }
            set { this.civicoVersanteField = value; }
        }

        /// <remarks/>
        public string capVersante
        {
            get { return this.capVersanteField; }
            set { this.capVersanteField = value; }
        }

        /// <remarks/>
        public string localitaVersante
        {
            get { return this.localitaVersanteField; }
            set { this.localitaVersanteField = value; }
        }

        /// <remarks/>
        public string provinciaVersante
        {
            get { return this.provinciaVersanteField; }
            set { this.provinciaVersanteField = value; }
        }

        /// <remarks/>
        public string nazioneVersante
        {
            get { return this.nazioneVersanteField; }
            set { this.nazioneVersanteField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("e-mailVersante")]
        public string emailVersante
        {
            get { return this.emailVersanteField; }
            set { this.emailVersanteField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/")]
    public enum stAutenticazioneSoggetto
    {

        /// <remarks/>
        CNS,

        /// <remarks/>
        USR,

        /// <remarks/>
        OTH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("N/A")] NA,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/")]
    [System.Xml.Serialization.XmlRootAttribute("RT", Namespace = "http://www.digitpa.gov.it/schemas/2011/Pagamenti/",
        IsNullable = false)]
    public partial class ctRicevutaTelematica
    {

        private string versioneOggettoField;

        private ctDominio dominioField;

        private string identificativoMessaggioRicevutaField;

        private System.DateTime dataOraMessaggioRicevutaField;

        private string riferimentoMessaggioRichiestaField;

        private System.DateTime riferimentoDataRichiestaField;

        private ctIstitutoAttestante istitutoAttestanteField;

        private ctEnteBeneficiario enteBeneficiarioField;

        private ctSoggettoVersante soggettoVersanteField;

        private ctSoggettoPagatore soggettoPagatoreField;

        private ctDatiVersamentoRT datiPagamentoField;

        /// <remarks/>
        public string versioneOggetto
        {
            get { return this.versioneOggettoField; }
            set { this.versioneOggettoField = value; }
        }

        /// <remarks/>
        public ctDominio dominio
        {
            get { return this.dominioField; }
            set { this.dominioField = value; }
        }

        /// <remarks/>
        public string identificativoMessaggioRicevuta
        {
            get { return this.identificativoMessaggioRicevutaField; }
            set { this.identificativoMessaggioRicevutaField = value; }
        }

        /// <remarks/>
        public System.DateTime dataOraMessaggioRicevuta
        {
            get { return this.dataOraMessaggioRicevutaField; }
            set { this.dataOraMessaggioRicevutaField = value; }
        }

        /// <remarks/>
        public string riferimentoMessaggioRichiesta
        {
            get { return this.riferimentoMessaggioRichiestaField; }
            set { this.riferimentoMessaggioRichiestaField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime riferimentoDataRichiesta
        {
            get { return this.riferimentoDataRichiestaField; }
            set { this.riferimentoDataRichiestaField = value; }
        }

        /// <remarks/>
        public ctIstitutoAttestante istitutoAttestante
        {
            get { return this.istitutoAttestanteField; }
            set { this.istitutoAttestanteField = value; }
        }

        /// <remarks/>
        public ctEnteBeneficiario enteBeneficiario
        {
            get { return this.enteBeneficiarioField; }
            set { this.enteBeneficiarioField = value; }
        }

        /// <remarks/>
        public ctSoggettoVersante soggettoVersante
        {
            get { return this.soggettoVersanteField; }
            set { this.soggettoVersanteField = value; }
        }

        /// <remarks/>
        public ctSoggettoPagatore soggettoPagatore
        {
            get { return this.soggettoPagatoreField; }
            set { this.soggettoPagatoreField = value; }
        }

        /// <remarks/>
        public ctDatiVersamentoRT datiPagamento
        {
            get { return this.datiPagamentoField; }
            set { this.datiPagamentoField = value; }
        }
    }
}