//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_RigaPortafoglio
    {
        public COM_RigaPortafoglio()
        {
            this.RCT_BollinoCalorePulitoConvertito = new HashSet<RCT_BollinoCalorePulitoConvertito>();
        }
    
        public System.Guid IDMovimento { get; set; }
        public int IdPortafoglio { get; set; }
        public string Utente { get; set; }
        public Nullable<System.DateTime> DataRegistrazione { get; set; }
        public Nullable<int> Valuta { get; set; }
        public Nullable<decimal> Importo { get; set; }
        public Nullable<int> Quantita { get; set; }
        public Nullable<int> IDLibrettoImpianto { get; set; }
        public Nullable<int> IdMovimentoBonifico { get; set; }
        public Nullable<int> IdMovimentoCassa { get; set; }
        public Nullable<int> IdMovimentoStorno { get; set; }
        public Nullable<long> IdPaymentRequest { get; set; }
        public Nullable<int> IdLottoBollinicalorePulito { get; set; }
    
        public virtual COM_MovimentoBonifico COM_MovimentoBonifico { get; set; }
        public virtual COM_MovimentoCassa COM_MovimentoCassa { get; set; }
        public virtual COM_MovimentoStorno COM_MovimentoStorno { get; set; }
        public virtual COM_PayerPaymentRequest COM_PayerPaymentRequest { get; set; }
        public virtual RCT_LottiBolliniCalorePulito RCT_LottiBolliniCalorePulito { get; set; }
        public virtual COM_Portafoglio COM_Portafoglio { get; set; }
        public virtual LIM_LibrettiImpianti LIM_LibrettiImpianti { get; set; }
        public virtual ICollection<RCT_BollinoCalorePulitoConvertito> RCT_BollinoCalorePulitoConvertito { get; set; }
    }
}
