//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_AnagraficaSoggettiAccreditamento
    {
        public COM_AnagraficaSoggettiAccreditamento()
        {
            this.COM_AnagraficaSoggettiAccreditamentoStato = new HashSet<COM_AnagraficaSoggettiAccreditamentoStato>();
        }
    
        public int IDSoggetto { get; set; }
        public int IDStatoAccreditamento { get; set; }
        public Nullable<System.DateTime> DataAccreditamento { get; set; }
        public Nullable<System.DateTime> DataRinnovo { get; set; }
        public Nullable<System.DateTime> DataAnnullamento { get; set; }
        public string MotivazioneAnnullamento { get; set; }
        public Nullable<System.DateTime> DataSospensioneDa { get; set; }
        public Nullable<System.DateTime> DataSospensioneA { get; set; }
        public string MotivazioneSospensione { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual SYS_StatoAccreditamento SYS_StatoAccreditamento { get; set; }
        public virtual ICollection<COM_AnagraficaSoggettiAccreditamentoStato> COM_AnagraficaSoggettiAccreditamentoStato { get; set; }
        public virtual COM_AnagraficaSoggetti COM_AnagraficaSoggetti { get; set; }
    }
}
