//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_MovimentoCassa
    {
        public COM_MovimentoCassa()
        {
            this.COM_RigaPortafoglio = new HashSet<COM_RigaPortafoglio>();
        }
    
        public int IdMovimentoCassa { get; set; }
        public System.DateTime DataVersamento { get; set; }
    
        public virtual ICollection<COM_RigaPortafoglio> COM_RigaPortafoglio { get; set; }
    }
}
