//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_Reports
    {
        public COM_Reports()
        {
            this.COM_ReportsAccess = new HashSet<COM_ReportsAccess>();
        }
    
        public int IDReport { get; set; }
        public string ReportName { get; set; }
        public string ReportDescription { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<COM_ReportsAccess> COM_ReportsAccess { get; set; }
    }
}
