//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_ContrattoIspettore
    {
        public COM_ContrattoIspettore()
        {
            this.VER_Ispezione = new HashSet<VER_Ispezione>();
        }
    
        public int IDContrattoIspettore { get; set; }
        public int IDIspettore { get; set; }
        public int IDStatoContratto { get; set; }
        public int NumeroIspezioniMax { get; set; }
        public System.DateTime DataInizioContratto { get; set; }
        public System.DateTime DataFineContratto { get; set; }
        public byte[] Firma { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual SYS_StatoContratto SYS_StatoContratto { get; set; }
        public virtual COM_AnagraficaSoggetti COM_AnagraficaSoggetti { get; set; }
        public virtual ICollection<VER_Ispezione> VER_Ispezione { get; set; }
    }
}
