//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_QuestionariDomande
    {
        public COM_QuestionariDomande()
        {
            this.COM_QuestionariRisposte = new HashSet<COM_QuestionariRisposte>();
        }
    
        public int IDQuestionarioDomanda { get; set; }
        public int IDQuestionario { get; set; }
        public string Domanda { get; set; }
        public string Note { get; set; }
    
        public virtual COM_Questionari COM_Questionari { get; set; }
        public virtual ICollection<COM_QuestionariRisposte> COM_QuestionariRisposte { get; set; }
    }
}
