//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_PayerFlussoRiversamento
    {
        public COM_PayerFlussoRiversamento()
        {
            this.COM_PayerPaymentRequest = new HashSet<COM_PayerPaymentRequest>();
        }
    
        public int Id { get; set; }
        public string identificativoFlusso { get; set; }
        public Nullable<System.DateTime> dataOraFlusso { get; set; }
        public string identificativoUnivocoRegolamento { get; set; }
        public Nullable<System.DateTime> dataRegolamento { get; set; }
        public string tipoIdentificativoUnivocoMittente { get; set; }
        public string codiceIdentificativoUnivocoMittente { get; set; }
        public string denominazioneMittente { get; set; }
        public string tipoIdentificativoUnivocoRicevente { get; set; }
        public string codiceIdentificativoUnivocoRicevente { get; set; }
        public string denominazioneRicevente { get; set; }
        public Nullable<decimal> importoTotalePagamenti { get; set; }
        public Nullable<int> numeroTotalePagamenti { get; set; }
    
        public virtual ICollection<COM_PayerPaymentRequest> COM_PayerPaymentRequest { get; set; }
    }
}
