//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_AnagraficaSoggettiAccreditamentoStato
    {
        public long IDAccreditamentoStato { get; set; }
        public int IDSoggetto { get; set; }
        public System.DateTime Data { get; set; }
        public int IDStatoAccreditamento { get; set; }
        public int IDUtenteUltimaModifica { get; set; }
        public Nullable<System.DateTime> DataAnnullamento { get; set; }
        public string MotivazioneAnnullamento { get; set; }
        public Nullable<System.DateTime> DataSospensioneDa { get; set; }
        public Nullable<System.DateTime> DataSospensioneA { get; set; }
        public string MotivazioneSospensione { get; set; }
    
        public virtual COM_AnagraficaSoggettiAccreditamento COM_AnagraficaSoggettiAccreditamento { get; set; }
        public virtual COM_Utenti COM_Utenti { get; set; }
        public virtual SYS_StatoAccreditamento SYS_StatoAccreditamento { get; set; }
    }
}
