//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_PayerPaymentData
    {
        public long IdPaymentData { get; set; }
        public System.DateTime DataRicezioneNotifica { get; set; }
        public long IdPaymentRequest { get; set; }
        public Nullable<System.Guid> IDOrdine { get; set; }
        public Nullable<System.DateTime> DataOraOrdine { get; set; }
        public string IDTransazione { get; set; }
        public Nullable<System.DateTime> DataOraTransazione { get; set; }
        public string SistemaPagamento { get; set; }
        public string CircuitoAutorizzativo { get; set; }
        public Nullable<decimal> ImportoTransato { get; set; }
        public Nullable<decimal> ImportoCommissioni { get; set; }
        public Nullable<decimal> ImportoCommissioniEnte { get; set; }
        public short Esito { get; set; }
        public string Autorizzazione { get; set; }
    
        public virtual COM_PayerPaymentRequest COM_PayerPaymentRequest { get; set; }
    }
}
