//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_Raccomandate
    {
        public COM_Raccomandate()
        {
            this.COM_RaccomandateSteps = new HashSet<COM_RaccomandateSteps>();
        }
    
        public string IDRichiesta { get; set; }
        public int Passaggio { get; set; }
        public string RisultatoTipo { get; set; }
        public string RisultatoCodice { get; set; }
        public string RisultatoDescrizione { get; set; }
        public System.DateTime CreatoIl { get; set; }
        public string CreatoDa { get; set; }
        public Nullable<System.DateTime> ModificatoIl { get; set; }
        public string ModificatoDa { get; set; }
        public int IDRaccomandataType { get; set; }
        public Nullable<long> IDAccertamento { get; set; }
        public Nullable<long> IDAccertamentoDocumento { get; set; }
        public Nullable<long> IDIspezione { get; set; }
        public string CodiceStatoRaccomandata { get; set; }
        public string DescrizioneStatoRaccomandata { get; set; }
        public Nullable<System.DateTime> DataStatoRaccomandata { get; set; }
        public bool fRaccomandataRecapitata { get; set; }
        public string NumeroRaccomandata { get; set; }
        public string Note { get; set; }
        public string ServiceType { get; set; }
    
        public virtual COM_Raccomandate COM_Raccomandate1 { get; set; }
        public virtual COM_Raccomandate COM_Raccomandate2 { get; set; }
        public virtual SYS_TipoRaccomandata SYS_TipoRaccomandata { get; set; }
        public virtual VER_Accertamento VER_Accertamento { get; set; }
        public virtual VER_AccertamentoDocumento VER_AccertamentoDocumento { get; set; }
        public virtual VER_Ispezione VER_Ispezione { get; set; }
        public virtual ICollection<COM_RaccomandateSteps> COM_RaccomandateSteps { get; set; }
    }
}
