//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_QuestionariRisposte
    {
        public int IDQuestionarioRisposta { get; set; }
        public int IDQuestionarioDomanda { get; set; }
        public int IDQuestionarioTipoRisposta { get; set; }
        public string Risposta { get; set; }
        public bool fRisposta { get; set; }
    
        public virtual COM_QuestionariDomande COM_QuestionariDomande { get; set; }
        public virtual SYS_QuestionarioTipoRisposte SYS_QuestionarioTipoRisposte { get; set; }
    }
}
