//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_PayerPaymentRequest
    {
        public COM_PayerPaymentRequest()
        {
            this.COM_PayerPaymentData = new HashSet<COM_PayerPaymentData>();
            this.COM_RigaPortafoglio = new HashSet<COM_RigaPortafoglio>();
        }
    
        public long idPaymentRequest { get; set; }
        public System.Guid NumeroOperazione { get; set; }
        public decimal Importo { get; set; }
        public int IdSoggetto { get; set; }
        public System.DateTime DataOraInserimento { get; set; }
        public Nullable<short> Esito { get; set; }
        public string IUV { get; set; }
        public Nullable<int> IdFlussoRiversamento { get; set; }
        public string NumeroDocumento { get; set; }
    
        public virtual COM_PayerFlussoRiversamento COM_PayerFlussoRiversamento { get; set; }
        public virtual ICollection<COM_PayerPaymentData> COM_PayerPaymentData { get; set; }
        public virtual ICollection<COM_RigaPortafoglio> COM_RigaPortafoglio { get; set; }
        public virtual COM_AnagraficaSoggetti COM_AnagraficaSoggetti { get; set; }
    }
}
