//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_RaccomandateSteps
    {
        public int IDProcessoPassaggio { get; set; }
        public string IDRichiesta { get; set; }
        public int PassaggioNumero { get; set; }
        public string PassaggioNome { get; set; }
        public string RisultatoTipo { get; set; }
        public string RisultatoCodice { get; set; }
        public string RisultatoDescrizione { get; set; }
        public System.DateTime CreatoIl { get; set; }
        public string CreatoDa { get; set; }
        public string PassaggioRisultatoJson { get; set; }
        public string UtenteGuid { get; set; }
        public string IdOrdine { get; set; }
    
        public virtual COM_Raccomandate COM_Raccomandate { get; set; }
    }
}
