//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CriterDataModel : DbContext
    {
        public CriterDataModel()
            : base("name=CriterDataModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COM_ProvinceCompetenza> COM_ProvinceCompetenza { get; set; }
        public virtual DbSet<COM_RuoliSoggetti> COM_RuoliSoggetti { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiTrattamentoAcquaAcs> LIM_LibrettiImpiantiTrattamentoAcquaAcs { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiTrattamentoAcquaEstiva> LIM_LibrettiImpiantiTrattamentoAcquaEstiva { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiTrattamentoAcquaInvernale> LIM_LibrettiImpiantiTrattamentoAcquaInvernale { get; set; }
        public virtual DbSet<SYS_CodiciCatastaliSezioni> SYS_CodiciCatastaliSezioni { get; set; }
        public virtual DbSet<SYS_DestinazioneUso> SYS_DestinazioneUso { get; set; }
        public virtual DbSet<SYS_Paesi> SYS_Paesi { get; set; }
        public virtual DbSet<SYS_Province> SYS_Province { get; set; }
        public virtual DbSet<SYS_Regioni> SYS_Regioni { get; set; }
        public virtual DbSet<SYS_RuoloSoggetto> SYS_RuoloSoggetto { get; set; }
        public virtual DbSet<SYS_StatoLibrettoImpianto> SYS_StatoLibrettoImpianto { get; set; }
        public virtual DbSet<SYS_TipologiaAcquaAlimento> SYS_TipologiaAcquaAlimento { get; set; }
        public virtual DbSet<SYS_TipologiaAddolcimentoAcqua> SYS_TipologiaAddolcimentoAcqua { get; set; }
        public virtual DbSet<SYS_TipologiaCircuitoRaffreddamento> SYS_TipologiaCircuitoRaffreddamento { get; set; }
        public virtual DbSet<SYS_TipologiaCondizionamentoChimico> SYS_TipologiaCondizionamentoChimico { get; set; }
        public virtual DbSet<SYS_TipologiaFiltrazione> SYS_TipologiaFiltrazione { get; set; }
        public virtual DbSet<SYS_TipologiaFluidoVettore> SYS_TipologiaFluidoVettore { get; set; }
        public virtual DbSet<SYS_TipologiaGeneratori> SYS_TipologiaGeneratori { get; set; }
        public virtual DbSet<SYS_TipologiaIntervento> SYS_TipologiaIntervento { get; set; }
        public virtual DbSet<SYS_TipologiaProtezioneGelo> SYS_TipologiaProtezioneGelo { get; set; }
        public virtual DbSet<SYS_TipologiaTrattamentoAcqua> SYS_TipologiaTrattamentoAcqua { get; set; }
        public virtual DbSet<SYS_TitoliSoggetti> SYS_TitoliSoggetti { get; set; }
        public virtual DbSet<SYS_TipologiaGruppiTermici> SYS_TipologiaGruppiTermici { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiBruciatori> LIM_LibrettiImpiantiBruciatori { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiRecuperatori> LIM_LibrettiImpiantiRecuperatori { get; set; }
        public virtual DbSet<SYS_TipologiaMacchineFrigorifere> SYS_TipologiaMacchineFrigorifere { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiAltriGeneratori> LIM_LibrettiImpiantiAltriGeneratori { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiCampiSolariTermici> LIM_LibrettiImpiantiCampiSolariTermici { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiAccumuli> LIM_LibrettiImpiantiAccumuli { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiCircuitiInterrati> LIM_LibrettiImpiantiCircuitiInterrati { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiPompeCircolazione> LIM_LibrettiImpiantiPompeCircolazione { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiRecuperatoriCalore> LIM_LibrettiImpiantiRecuperatoriCalore { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiScambiatoriCaloreIntermedi> LIM_LibrettiImpiantiScambiatoriCaloreIntermedi { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiSistemiRegolazione> LIM_LibrettiImpiantiSistemiRegolazione { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiUnitaTrattamentoAria> LIM_LibrettiImpiantiUnitaTrattamentoAria { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiValvoleRegolazione> LIM_LibrettiImpiantiValvoleRegolazione { get; set; }
        public virtual DbSet<SYS_ModalitaInstallazioneRecuperatoriCalore> SYS_ModalitaInstallazioneRecuperatoriCalore { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiTipologiaSistemiEmissione> LIM_LibrettiImpiantiTipologiaSistemiEmissione { get; set; }
        public virtual DbSet<SYS_TipologiaSistemiEmissione> SYS_TipologiaSistemiEmissione { get; set; }
        public virtual DbSet<SYS_TipologiaSistemaContabilizzazione> SYS_TipologiaSistemaContabilizzazione { get; set; }
        public virtual DbSet<SYS_TipologiaTermostatoZona> SYS_TipologiaTermostatoZona { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiDescrizioniSistemi> LIM_LibrettiImpiantiDescrizioniSistemi { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiVasiEspansione> LIM_LibrettiImpiantiVasiEspansione { get; set; }
        public virtual DbSet<SYS_UserAccess> SYS_UserAccess { get; set; }
        public virtual DbSet<SYS_UserRole> SYS_UserRole { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SYS_TipologiaFluidoTermoVettore> SYS_TipologiaFluidoTermoVettore { get; set; }
        public virtual DbSet<SYS_AbilitazioneSoggetto> SYS_AbilitazioneSoggetto { get; set; }
        public virtual DbSet<COM_ClassificazioniImpianto> COM_ClassificazioniImpianto { get; set; }
        public virtual DbSet<SYS_ClassificazioneImpianto> SYS_ClassificazioneImpianto { get; set; }
        public virtual DbSet<COM_AbilitazioniSoggetto> COM_AbilitazioniSoggetto { get; set; }
        public virtual DbSet<MNU_Menu> MNU_Menu { get; set; }
        public virtual DbSet<V_MNU_Menu> V_MNU_Menu { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiDatiCatastali> LIM_LibrettiImpiantiDatiCatastali { get; set; }
        public virtual DbSet<SYS_FluidoLatoUtenze> SYS_FluidoLatoUtenze { get; set; }
        public virtual DbSet<SYS_SorgenteLatoEsterno> SYS_SorgenteLatoEsterno { get; set; }
        public virtual DbSet<V_LIM_LibrettiImpiantiDatiCatastali> V_LIM_LibrettiImpiantiDatiCatastali { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiAddolcimentoAcqua> LIM_LibrettiImpiantiAddolcimentoAcqua { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiCondizionamentoChimico> LIM_LibrettiImpiantiCondizionamentoChimico { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiTipologiaFiltrazioni> LIM_LibrettiImpiantiTipologiaFiltrazioni { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiTipologiaGeneratori> LIM_LibrettiImpiantiTipologiaGeneratori { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiTipologiaFluidoVettore> LIM_LibrettiImpiantiTipologiaFluidoVettore { get; set; }
        public virtual DbSet<SYS_TipologiaCogeneratore> SYS_TipologiaCogeneratore { get; set; }
        public virtual DbSet<SYS_TipologiaCombustibile> SYS_TipologiaCombustibile { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiTipologiaSistemaDistribuzione> LIM_LibrettiImpiantiTipologiaSistemaDistribuzione { get; set; }
        public virtual DbSet<SYS_TipologiaSistemaDistribuzione> SYS_TipologiaSistemaDistribuzione { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiRaffreddatoriLiquido> LIM_LibrettiImpiantiRaffreddatoriLiquido { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiTorriEvaporative> LIM_LibrettiImpiantiTorriEvaporative { get; set; }
        public virtual DbSet<SYS_TipologiaVentilatori> SYS_TipologiaVentilatori { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiImpiantiVMC> LIM_LibrettiImpiantiImpiantiVMC { get; set; }
        public virtual DbSet<SYS_TipologiaImpiantiVMC> SYS_TipologiaImpiantiVMC { get; set; }
        public virtual DbSet<COM_MovimentoBonifico> COM_MovimentoBonifico { get; set; }
        public virtual DbSet<COM_MovimentoCassa> COM_MovimentoCassa { get; set; }
        public virtual DbSet<COM_PayerFlussoRiversamento> COM_PayerFlussoRiversamento { get; set; }
        public virtual DbSet<COM_PayerPaymentRequest> COM_PayerPaymentRequest { get; set; }
        public virtual DbSet<COM_PayerPaymentData> COM_PayerPaymentData { get; set; }
        public virtual DbSet<SYS_UnitaMisura> SYS_UnitaMisura { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiConsumoCombustibile> LIM_LibrettiImpiantiConsumoCombustibile { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiConsumoAcqua> LIM_LibrettiImpiantiConsumoAcqua { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiConsumoEnergiaElettrica> LIM_LibrettiImpiantiConsumoEnergiaElettrica { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiConsumoProdottiChimici> LIM_LibrettiImpiantiConsumoProdottiChimici { get; set; }
        public virtual DbSet<SYS_TipoSoggetto> SYS_TipoSoggetto { get; set; }
        public virtual DbSet<SYS_TipologiaResponsabile> SYS_TipologiaResponsabile { get; set; }
        public virtual DbSet<LogData> LogData { get; set; }
        public virtual DbSet<RCT_RapportoDiControlloTecnicoBaseTrattamentoAcs> RCT_RapportoDiControlloTecnicoBaseTrattamentoAcs { get; set; }
        public virtual DbSet<SYS_TipologiaRapportoDiControllo> SYS_TipologiaRapportoDiControllo { get; set; }
        public virtual DbSet<SYS_StatoRapportoDiControllo> SYS_StatoRapportoDiControllo { get; set; }
        public virtual DbSet<SYS_TipologiaControllo> SYS_TipologiaControllo { get; set; }
        public virtual DbSet<SYS_RCTTipologiaCheckList> SYS_RCTTipologiaCheckList { get; set; }
        public virtual DbSet<SYS_RCTCheckList> SYS_RCTCheckList { get; set; }
        public virtual DbSet<RCT_RapportoDiControlloTecnicoBaseTrattamentoInvernale> RCT_RapportoDiControlloTecnicoBaseTrattamentoInvernale { get; set; }
        public virtual DbSet<SYS_TipologiaGeneratoriTermici> SYS_TipologiaGeneratoriTermici { get; set; }
        public virtual DbSet<V_SYS_CheckList> V_SYS_CheckList { get; set; }
        public virtual DbSet<RCT_RapportoDiControlloTecnicoGF> RCT_RapportoDiControlloTecnicoGF { get; set; }
        public virtual DbSet<RCT_RapportoDiControlloTecnicoGT> RCT_RapportoDiControlloTecnicoGT { get; set; }
        public virtual DbSet<RCT_RapportoDiControlloTecnicoBaseCheckList> RCT_RapportoDiControlloTecnicoBaseCheckList { get; set; }
        public virtual DbSet<V_SYS_ProvinceRegioni> V_SYS_ProvinceRegioni { get; set; }
        public virtual DbSet<SYS_TipoSistema> SYS_TipoSistema { get; set; }
        public virtual DbSet<COM_MovimentoStorno> COM_MovimentoStorno { get; set; }
        public virtual DbSet<COM_RigaPortafoglio> COM_RigaPortafoglio { get; set; }
        public virtual DbSet<RCT_LottiBolliniCalorePulito> RCT_LottiBolliniCalorePulito { get; set; }
        public virtual DbSet<RCT_RapportoDiControlloTecnicoSC> RCT_RapportoDiControlloTecnicoSC { get; set; }
        public virtual DbSet<RCT_RapportoDiControlloTecnicoCG> RCT_RapportoDiControlloTecnicoCG { get; set; }
        public virtual DbSet<SYS_TipologiaContabilizzazione> SYS_TipologiaContabilizzazione { get; set; }
        public virtual DbSet<COM_AnagraficaSoggettiFirmaDigitale> COM_AnagraficaSoggettiFirmaDigitale { get; set; }
        public virtual DbSet<RCT_FirmaDigitale> RCT_FirmaDigitale { get; set; }
        public virtual DbSet<COM_Utenti> COM_Utenti { get; set; }
        public virtual DbSet<SYS_TipologiaQualificaIspettore> SYS_TipologiaQualificaIspettore { get; set; }
        public virtual DbSet<SYS_TipologiaTitoloStudio> SYS_TipologiaTitoloStudio { get; set; }
        public virtual DbSet<SYS_CodiciCatastali> SYS_CodiciCatastali { get; set; }
        public virtual DbSet<SYS_RCTTipologiaPrescrizione> SYS_RCTTipologiaPrescrizione { get; set; }
        public virtual DbSet<SYS_RCTTipologiaRaccomandazione> SYS_RCTTipologiaRaccomandazione { get; set; }
        public virtual DbSet<SYS_TipologiaRaccomandazionePrescrizioneRct> SYS_TipologiaRaccomandazionePrescrizioneRct { get; set; }
        public virtual DbSet<RCT_RaccomandazioniPrescrizioni> RCT_RaccomandazioniPrescrizioni { get; set; }
        public virtual DbSet<LIM_TargatureImpianti> LIM_TargatureImpianti { get; set; }
        public virtual DbSet<SYS_StatoAccertamento> SYS_StatoAccertamento { get; set; }
        public virtual DbSet<COM_AnagraficaSoggettiAlbo> COM_AnagraficaSoggettiAlbo { get; set; }
        public virtual DbSet<V_RCT_RapportiControlloTecnico> V_RCT_RapportiControlloTecnico { get; set; }
        public virtual DbSet<VER_AccertamentoNote> VER_AccertamentoNote { get; set; }
        public virtual DbSet<COM_TipiDistributoriCombustibile> COM_TipiDistributoriCombustibile { get; set; }
        public virtual DbSet<SYS_TipologiaDistributoriCombustibile> SYS_TipologiaDistributoriCombustibile { get; set; }
        public virtual DbSet<UTE_Comunicazioni> UTE_Comunicazioni { get; set; }
        public virtual DbSet<UTE_DatiCatastali> UTE_DatiCatastali { get; set; }
        public virtual DbSet<UTE_DatiFornituraCliente> UTE_DatiFornituraCliente { get; set; }
        public virtual DbSet<V_LIM_VerifichePeriodicheCG> V_LIM_VerifichePeriodicheCG { get; set; }
        public virtual DbSet<V_LIM_VerifichePeriodicheGF> V_LIM_VerifichePeriodicheGF { get; set; }
        public virtual DbSet<V_LIM_VerifichePeriodicheGT> V_LIM_VerifichePeriodicheGT { get; set; }
        public virtual DbSet<V_LIM_VerifichePeriodicheSC> V_LIM_VerifichePeriodicheSC { get; set; }
        public virtual DbSet<SYS_TipologiaOrdineCollegio> SYS_TipologiaOrdineCollegio { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiCogeneratori> LIM_LibrettiImpiantiCogeneratori { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiMacchineFrigorifere> LIM_LibrettiImpiantiMacchineFrigorifere { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiScambiatoriCalore> LIM_LibrettiImpiantiScambiatoriCalore { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiGruppiTermici> LIM_LibrettiImpiantiGruppiTermici { get; set; }
        public virtual DbSet<SYS_TipologiaImpiantoFunzionanteAccertamento> SYS_TipologiaImpiantoFunzionanteAccertamento { get; set; }
        public virtual DbSet<SYS_TipologiaRisoluzioneAccertamento> SYS_TipologiaRisoluzioneAccertamento { get; set; }
        public virtual DbSet<SYS_TipologiaEventoAccertamento> SYS_TipologiaEventoAccertamento { get; set; }
        public virtual DbSet<SYS_TipologiaDistributori> SYS_TipologiaDistributori { get; set; }
        public virtual DbSet<COM_Portafoglio> COM_Portafoglio { get; set; }
        public virtual DbSet<SYS_TipologiaInterventoAccertamento> SYS_TipologiaInterventoAccertamento { get; set; }
        public virtual DbSet<VER_AccertamentoFirmaDigitale> VER_AccertamentoFirmaDigitale { get; set; }
        public virtual DbSet<SYS_StatoAccertamentoIntervento> SYS_StatoAccertamentoIntervento { get; set; }
        public virtual DbSet<VER_AccertamentoNonConformita> VER_AccertamentoNonConformita { get; set; }
        public virtual DbSet<VER_AccertamentoStato> VER_AccertamentoStato { get; set; }
        public virtual DbSet<V_VER_AccertamentiStato> V_VER_AccertamentiStato { get; set; }
        public virtual DbSet<SYS_StatoIspezione> SYS_StatoIspezione { get; set; }
        public virtual DbSet<SYS_StatoPianificazioneIspettore> SYS_StatoPianificazioneIspettore { get; set; }
        public virtual DbSet<SYS_StatoContratto> SYS_StatoContratto { get; set; }
        public virtual DbSet<COM_ContrattoIspettore> COM_ContrattoIspettore { get; set; }
        public virtual DbSet<V_COM_ContrattoIspettore> V_COM_ContrattoIspettore { get; set; }
        public virtual DbSet<SYS_TipologiaIspezioneRapportoCheckList> SYS_TipologiaIspezioneRapportoCheckList { get; set; }
        public virtual DbSet<SYS_CausaliRaccomandate> SYS_CausaliRaccomandate { get; set; }
        public virtual DbSet<VER_AccertamentoDocumento> VER_AccertamentoDocumento { get; set; }
        public virtual DbSet<V_LIM_TargatureImpianti> V_LIM_TargatureImpianti { get; set; }
        public virtual DbSet<SYS_QuestionarioDomande> SYS_QuestionarioDomande { get; set; }
        public virtual DbSet<SYS_QuestionarioRisposte> SYS_QuestionarioRisposte { get; set; }
        public virtual DbSet<SYS_QuestionarioTipoRisposte> SYS_QuestionarioTipoRisposte { get; set; }
        public virtual DbSet<COM_Questionari> COM_Questionari { get; set; }
        public virtual DbSet<SYS_StatoQuestionario> SYS_StatoQuestionario { get; set; }
        public virtual DbSet<COM_QuestionariDomande> COM_QuestionariDomande { get; set; }
        public virtual DbSet<COM_QuestionariRisposte> COM_QuestionariRisposte { get; set; }
        public virtual DbSet<V_LIM_LibrettiImpianti> V_LIM_LibrettiImpianti { get; set; }
        public virtual DbSet<SYS_TipoIspezione> SYS_TipoIspezione { get; set; }
        public virtual DbSet<VER_ProgrammaIspezione> VER_ProgrammaIspezione { get; set; }
        public virtual DbSet<V_COM_Questionari> V_COM_Questionari { get; set; }
        public virtual DbSet<V_SYS_CodiciCatastali> V_SYS_CodiciCatastali { get; set; }
        public virtual DbSet<SYS_FormeGiuridiche> SYS_FormeGiuridiche { get; set; }
        public virtual DbSet<SYS_FunzioniSoggetti> SYS_FunzioniSoggetti { get; set; }
        public virtual DbSet<COM_CodiciCatastaliCompetenza> COM_CodiciCatastaliCompetenza { get; set; }
        public virtual DbSet<COM_Reports> COM_Reports { get; set; }
        public virtual DbSet<COM_ReportsAccess> COM_ReportsAccess { get; set; }
        public virtual DbSet<V_RCT_RapportoDiControlloTecnicoCG> V_RCT_RapportoDiControlloTecnicoCG { get; set; }
        public virtual DbSet<V_RCT_RapportoDiControlloTecnicoGF> V_RCT_RapportoDiControlloTecnicoGF { get; set; }
        public virtual DbSet<V_RCT_RapportoDiControlloTecnicoGT> V_RCT_RapportoDiControlloTecnicoGT { get; set; }
        public virtual DbSet<V_RCT_RapportoDiControlloTecnicoSC> V_RCT_RapportoDiControlloTecnicoSC { get; set; }
        public virtual DbSet<RCT_RapportoDiControlloTecnicoBase> RCT_RapportoDiControlloTecnicoBase { get; set; }
        public virtual DbSet<COM_AnagraficaSoggettiAccreditamento> COM_AnagraficaSoggettiAccreditamento { get; set; }
        public virtual DbSet<SYS_StatoAccreditamento> SYS_StatoAccreditamento { get; set; }
        public virtual DbSet<COM_AnagraficaSoggettiAccreditamentoStato> COM_AnagraficaSoggettiAccreditamentoStato { get; set; }
        public virtual DbSet<V_COM_AnagraficaSoggettiAccreditamentoStato> V_COM_AnagraficaSoggettiAccreditamentoStato { get; set; }
        public virtual DbSet<VER_IspezioneVisita> VER_IspezioneVisita { get; set; }
        public virtual DbSet<SYS_Orario> SYS_Orario { get; set; }
        public virtual DbSet<VER_IspezioneStato> VER_IspezioneStato { get; set; }
        public virtual DbSet<V_VER_IspezioniStato> V_VER_IspezioniStato { get; set; }
        public virtual DbSet<VER_IspezioneRapportoCheckList> VER_IspezioneRapportoCheckList { get; set; }
        public virtual DbSet<VER_IspezioneRapportoStrumenti> VER_IspezioneRapportoStrumenti { get; set; }
        public virtual DbSet<VER_IspezioneRapportoTrattamentoAcs> VER_IspezioneRapportoTrattamentoAcs { get; set; }
        public virtual DbSet<VER_IspezioneRapportoTrattamentoInvernale> VER_IspezioneRapportoTrattamentoInvernale { get; set; }
        public virtual DbSet<VER_IspezioneRaccomandazioniPrescrizioni> VER_IspezioneRaccomandazioniPrescrizioni { get; set; }
        public virtual DbSet<LIM_LibrettiImpiantiResponsabili> LIM_LibrettiImpiantiResponsabili { get; set; }
        public virtual DbSet<COM_AnagraficaSoggetti> COM_AnagraficaSoggetti { get; set; }
        public virtual DbSet<V_COM_AnagraficaSoggetti> V_COM_AnagraficaSoggetti { get; set; }
        public virtual DbSet<COM_AnagraficaSoggettiPrivacyCount> COM_AnagraficaSoggettiPrivacyCount { get; set; }
        public virtual DbSet<V_VER_AccertamentiProgramma> V_VER_AccertamentiProgramma { get; set; }
        public virtual DbSet<VER_AccertamentoProgramma> VER_AccertamentoProgramma { get; set; }
        public virtual DbSet<VER_AccertamentoVisita> VER_AccertamentoVisita { get; set; }
        public virtual DbSet<VER_AccertamentoVisitaInfo> VER_AccertamentoVisitaInfo { get; set; }
        public virtual DbSet<V_VER_AccertamentoVisita> V_VER_AccertamentoVisita { get; set; }
        public virtual DbSet<VER_ProgrammaAccertamento> VER_ProgrammaAccertamento { get; set; }
        public virtual DbSet<SYS_TipoAccertamento> SYS_TipoAccertamento { get; set; }
        public virtual DbSet<SYS_ProceduraAccertamento> SYS_ProceduraAccertamento { get; set; }
        public virtual DbSet<V_COM_Utenti> V_COM_Utenti { get; set; }
        public virtual DbSet<V_VER_AccertamentoDocumento> V_VER_AccertamentoDocumento { get; set; }
        public virtual DbSet<SYS_StatoAccertamentoSanzione> SYS_StatoAccertamentoSanzione { get; set; }
        public virtual DbSet<VER_RegoleControlli> VER_RegoleControlli { get; set; }
        public virtual DbSet<VER_ProgrammaIspezioneInfo> VER_ProgrammaIspezioneInfo { get; set; }
        public virtual DbSet<VER_IspezioneVisitaInfo> VER_IspezioneVisitaInfo { get; set; }
        public virtual DbSet<V_VER_IspezioniVisite> V_VER_IspezioniVisite { get; set; }
        public virtual DbSet<LIM_LibrettiImpianti> LIM_LibrettiImpianti { get; set; }
        public virtual DbSet<COM_RaccomandateDestinatari> COM_RaccomandateDestinatari { get; set; }
        public virtual DbSet<COM_RaccomandateSteps> COM_RaccomandateSteps { get; set; }
        public virtual DbSet<SYS_TipoRaccomandata> SYS_TipoRaccomandata { get; set; }
        public virtual DbSet<V_LIM_LibrettiImpiantiTerziResponsabili> V_LIM_LibrettiImpiantiTerziResponsabili { get; set; }
        public virtual DbSet<V_VER_ProgrammaIspezioneGeneratori> V_VER_ProgrammaIspezioneGeneratori { get; set; }
        public virtual DbSet<VER_IspezioneGruppoVerifica> VER_IspezioneGruppoVerifica { get; set; }
        public virtual DbSet<SYS_TipoDocumentoIspezione> SYS_TipoDocumentoIspezione { get; set; }
        public virtual DbSet<VER_IspezioneDocumento> VER_IspezioneDocumento { get; set; }
        public virtual DbSet<V_VER_IspezioneDocumento> V_VER_IspezioneDocumento { get; set; }
        public virtual DbSet<VER_IspezioneRapporto> VER_IspezioneRapporto { get; set; }
        public virtual DbSet<V_RCT_BollinoCalorePulito> V_RCT_BollinoCalorePulito { get; set; }
        public virtual DbSet<RCT_BollinoCalorePulito> RCT_BollinoCalorePulito { get; set; }
        public virtual DbSet<SYS_FasceContributive> SYS_FasceContributive { get; set; }
        public virtual DbSet<RCT_BollinoCalorePulitoConvertito> RCT_BollinoCalorePulitoConvertito { get; set; }
        public virtual DbSet<VER_Accertamento> VER_Accertamento { get; set; }
        public virtual DbSet<V_VER_Accertamenti> V_VER_Accertamenti { get; set; }
        public virtual DbSet<V_VER_AccertamentiNota> V_VER_AccertamentiNota { get; set; }
        public virtual DbSet<SYS_SvolgimentoIspezione> SYS_SvolgimentoIspezione { get; set; }
        public virtual DbSet<VER_IspezioneNotificaRiaperturaIspezione> VER_IspezioneNotificaRiaperturaIspezione { get; set; }
        public virtual DbSet<V_VER_IspezioneNotificaRiaperturaIspezione> V_VER_IspezioneNotificaRiaperturaIspezione { get; set; }
        public virtual DbSet<VER_Ispezione> VER_Ispezione { get; set; }
        public virtual DbSet<VER_IspezioneQuestinarioQualita> VER_IspezioneQuestinarioQualita { get; set; }
        public virtual DbSet<V_VER_IspezioneQuestinarioQualita> V_VER_IspezioneQuestinarioQualita { get; set; }
        public virtual DbSet<V_VER_Ispezioni> V_VER_Ispezioni { get; set; }
        public virtual DbSet<COM_Raccomandate> COM_Raccomandate { get; set; }
        public virtual DbSet<V_COM_Raccomandate> V_COM_Raccomandate { get; set; }
    
        public virtual int sp_SetCodiceSoggetto(Nullable<int> iDSoggetto, Nullable<int> iDTipoSoggetto)
        {
            var iDSoggettoParameter = iDSoggetto.HasValue ?
                new ObjectParameter("IDSoggetto", iDSoggetto) :
                new ObjectParameter("IDSoggetto", typeof(int));
    
            var iDTipoSoggettoParameter = iDTipoSoggetto.HasValue ?
                new ObjectParameter("IDTipoSoggetto", iDTipoSoggetto) :
                new ObjectParameter("IDTipoSoggetto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SetCodiceSoggetto", iDSoggettoParameter, iDTipoSoggettoParameter);
        }
    
        public virtual int sp_SetCodiceTargatura(Nullable<int> iDSoggetto, Nullable<int> iDSoggettoDerived, Nullable<int> numeroTargature, ObjectParameter codiceLottoOut)
        {
            var iDSoggettoParameter = iDSoggetto.HasValue ?
                new ObjectParameter("IDSoggetto", iDSoggetto) :
                new ObjectParameter("IDSoggetto", typeof(int));
    
            var iDSoggettoDerivedParameter = iDSoggettoDerived.HasValue ?
                new ObjectParameter("IDSoggettoDerived", iDSoggettoDerived) :
                new ObjectParameter("IDSoggettoDerived", typeof(int));
    
            var numeroTargatureParameter = numeroTargature.HasValue ?
                new ObjectParameter("NumeroTargature", numeroTargature) :
                new ObjectParameter("NumeroTargature", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SetCodiceTargatura", iDSoggettoParameter, iDSoggettoDerivedParameter, numeroTargatureParameter, codiceLottoOut);
        }
    
        public virtual int sp_upLogIt(string userName, string tipoEvento, string hostName, string indirizzoIP, string tipoOggetto, string nomeOggetto, string iD, string note)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var tipoEventoParameter = tipoEvento != null ?
                new ObjectParameter("TipoEvento", tipoEvento) :
                new ObjectParameter("TipoEvento", typeof(string));
    
            var hostNameParameter = hostName != null ?
                new ObjectParameter("HostName", hostName) :
                new ObjectParameter("HostName", typeof(string));
    
            var indirizzoIPParameter = indirizzoIP != null ?
                new ObjectParameter("IndirizzoIP", indirizzoIP) :
                new ObjectParameter("IndirizzoIP", typeof(string));
    
            var tipoOggettoParameter = tipoOggetto != null ?
                new ObjectParameter("TipoOggetto", tipoOggetto) :
                new ObjectParameter("TipoOggetto", typeof(string));
    
            var nomeOggettoParameter = nomeOggetto != null ?
                new ObjectParameter("NomeOggetto", nomeOggetto) :
                new ObjectParameter("NomeOggetto", typeof(string));
    
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var noteParameter = note != null ?
                new ObjectParameter("Note", note) :
                new ObjectParameter("Note", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upLogIt", userNameParameter, tipoEventoParameter, hostNameParameter, indirizzoIPParameter, tipoOggettoParameter, nomeOggettoParameter, iDParameter, noteParameter);
        }
    
        public virtual int sp_SetRegoleControlli(Nullable<int> potenzaTermicaUtileNominaleKwR1, string listCombustibileR1, string listGruppiTermiciR1, Nullable<int> potenzaTermicaUtileNominaleKwR2, string listCombustibileR2, string listGruppiTermiciR2, Nullable<int> potenzaTermicaUtileNominaleKwR3, string listCombustibileR3, string listGruppiTermiciR3, Nullable<int> daPotenzaTermicaUtileNominaleKwR4, Nullable<int> aPotenzaTermicaUtileNominaleKwR4, string listCombustibileR4, string listGruppiTermiciR4, Nullable<int> potenzaTermicaUtileNominaleKwR5, string listCombustibileR5, string listGruppiTermiciR5)
        {
            var potenzaTermicaUtileNominaleKwR1Parameter = potenzaTermicaUtileNominaleKwR1.HasValue ?
                new ObjectParameter("PotenzaTermicaUtileNominaleKwR1", potenzaTermicaUtileNominaleKwR1) :
                new ObjectParameter("PotenzaTermicaUtileNominaleKwR1", typeof(int));
    
            var listCombustibileR1Parameter = listCombustibileR1 != null ?
                new ObjectParameter("ListCombustibileR1", listCombustibileR1) :
                new ObjectParameter("ListCombustibileR1", typeof(string));
    
            var listGruppiTermiciR1Parameter = listGruppiTermiciR1 != null ?
                new ObjectParameter("ListGruppiTermiciR1", listGruppiTermiciR1) :
                new ObjectParameter("ListGruppiTermiciR1", typeof(string));
    
            var potenzaTermicaUtileNominaleKwR2Parameter = potenzaTermicaUtileNominaleKwR2.HasValue ?
                new ObjectParameter("PotenzaTermicaUtileNominaleKwR2", potenzaTermicaUtileNominaleKwR2) :
                new ObjectParameter("PotenzaTermicaUtileNominaleKwR2", typeof(int));
    
            var listCombustibileR2Parameter = listCombustibileR2 != null ?
                new ObjectParameter("ListCombustibileR2", listCombustibileR2) :
                new ObjectParameter("ListCombustibileR2", typeof(string));
    
            var listGruppiTermiciR2Parameter = listGruppiTermiciR2 != null ?
                new ObjectParameter("ListGruppiTermiciR2", listGruppiTermiciR2) :
                new ObjectParameter("ListGruppiTermiciR2", typeof(string));
    
            var potenzaTermicaUtileNominaleKwR3Parameter = potenzaTermicaUtileNominaleKwR3.HasValue ?
                new ObjectParameter("PotenzaTermicaUtileNominaleKwR3", potenzaTermicaUtileNominaleKwR3) :
                new ObjectParameter("PotenzaTermicaUtileNominaleKwR3", typeof(int));
    
            var listCombustibileR3Parameter = listCombustibileR3 != null ?
                new ObjectParameter("ListCombustibileR3", listCombustibileR3) :
                new ObjectParameter("ListCombustibileR3", typeof(string));
    
            var listGruppiTermiciR3Parameter = listGruppiTermiciR3 != null ?
                new ObjectParameter("ListGruppiTermiciR3", listGruppiTermiciR3) :
                new ObjectParameter("ListGruppiTermiciR3", typeof(string));
    
            var daPotenzaTermicaUtileNominaleKwR4Parameter = daPotenzaTermicaUtileNominaleKwR4.HasValue ?
                new ObjectParameter("DaPotenzaTermicaUtileNominaleKwR4", daPotenzaTermicaUtileNominaleKwR4) :
                new ObjectParameter("DaPotenzaTermicaUtileNominaleKwR4", typeof(int));
    
            var aPotenzaTermicaUtileNominaleKwR4Parameter = aPotenzaTermicaUtileNominaleKwR4.HasValue ?
                new ObjectParameter("APotenzaTermicaUtileNominaleKwR4", aPotenzaTermicaUtileNominaleKwR4) :
                new ObjectParameter("APotenzaTermicaUtileNominaleKwR4", typeof(int));
    
            var listCombustibileR4Parameter = listCombustibileR4 != null ?
                new ObjectParameter("ListCombustibileR4", listCombustibileR4) :
                new ObjectParameter("ListCombustibileR4", typeof(string));
    
            var listGruppiTermiciR4Parameter = listGruppiTermiciR4 != null ?
                new ObjectParameter("ListGruppiTermiciR4", listGruppiTermiciR4) :
                new ObjectParameter("ListGruppiTermiciR4", typeof(string));
    
            var potenzaTermicaUtileNominaleKwR5Parameter = potenzaTermicaUtileNominaleKwR5.HasValue ?
                new ObjectParameter("PotenzaTermicaUtileNominaleKwR5", potenzaTermicaUtileNominaleKwR5) :
                new ObjectParameter("PotenzaTermicaUtileNominaleKwR5", typeof(int));
    
            var listCombustibileR5Parameter = listCombustibileR5 != null ?
                new ObjectParameter("ListCombustibileR5", listCombustibileR5) :
                new ObjectParameter("ListCombustibileR5", typeof(string));
    
            var listGruppiTermiciR5Parameter = listGruppiTermiciR5 != null ?
                new ObjectParameter("ListGruppiTermiciR5", listGruppiTermiciR5) :
                new ObjectParameter("ListGruppiTermiciR5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SetRegoleControlli", potenzaTermicaUtileNominaleKwR1Parameter, listCombustibileR1Parameter, listGruppiTermiciR1Parameter, potenzaTermicaUtileNominaleKwR2Parameter, listCombustibileR2Parameter, listGruppiTermiciR2Parameter, potenzaTermicaUtileNominaleKwR3Parameter, listCombustibileR3Parameter, listGruppiTermiciR3Parameter, daPotenzaTermicaUtileNominaleKwR4Parameter, aPotenzaTermicaUtileNominaleKwR4Parameter, listCombustibileR4Parameter, listGruppiTermiciR4Parameter, potenzaTermicaUtileNominaleKwR5Parameter, listCombustibileR5Parameter, listGruppiTermiciR5Parameter);
        }
    }
}
