//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIM_TargatureImpianti
    {
        public LIM_TargatureImpianti()
        {
            this.RCT_RapportoDiControlloTecnicoBase = new HashSet<RCT_RapportoDiControlloTecnicoBase>();
            this.VER_RegoleControlli = new HashSet<VER_RegoleControlli>();
            this.LIM_LibrettiImpianti = new HashSet<LIM_LibrettiImpianti>();
            this.VER_Accertamento = new HashSet<VER_Accertamento>();
        }
    
        public int IDTargaturaImpianto { get; set; }
        public int IDSoggetto { get; set; }
        public Nullable<int> IDSoggettoDerived { get; set; }
        public string CodiceLotto { get; set; }
        public string CodiceTargatura { get; set; }
        public int CodiceRandom { get; set; }
        public int Anno { get; set; }
        public Nullable<int> IDUtenteInserimento { get; set; }
        public Nullable<System.DateTime> DataInserimento { get; set; }
        public Nullable<int> IDUtenteUltimaModifica { get; set; }
        public Nullable<System.DateTime> DataUltimaModifica { get; set; }
    
        public virtual ICollection<RCT_RapportoDiControlloTecnicoBase> RCT_RapportoDiControlloTecnicoBase { get; set; }
        public virtual COM_AnagraficaSoggetti COM_AnagraficaSoggetti { get; set; }
        public virtual ICollection<VER_RegoleControlli> VER_RegoleControlli { get; set; }
        public virtual ICollection<LIM_LibrettiImpianti> LIM_LibrettiImpianti { get; set; }
        public virtual ICollection<VER_Accertamento> VER_Accertamento { get; set; }
    }
}
