//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIM_LibrettiImpiantiGruppiTermici
    {
        public LIM_LibrettiImpiantiGruppiTermici()
        {
            this.LIM_LibrettiImpiantiBruciatori = new HashSet<LIM_LibrettiImpiantiBruciatori>();
            this.RCT_RapportoDiControlloTecnicoGT = new HashSet<RCT_RapportoDiControlloTecnicoGT>();
            this.LIM_LibrettiImpiantiRecuperatori = new HashSet<LIM_LibrettiImpiantiRecuperatori>();
            this.VER_RegoleControlli = new HashSet<VER_RegoleControlli>();
        }
    
        public int IDLibrettoImpiantoGruppoTermico { get; set; }
        public int IDLibrettoImpianto { get; set; }
        public Nullable<int> IDUtenteInserimento { get; set; }
        public Nullable<System.DateTime> DataInserimento { get; set; }
        public int IDLibrettoImpiantoInserimento { get; set; }
        public Nullable<int> IDUtenteUltimaModifica { get; set; }
        public Nullable<System.DateTime> DataUltimaModifica { get; set; }
        public string Prefisso { get; set; }
        public int CodiceProgressivo { get; set; }
        public string Fabbricante { get; set; }
        public string Modello { get; set; }
        public string Matricola { get; set; }
        public Nullable<int> IDTipologiaCombustibile { get; set; }
        public string CombustibileAltro { get; set; }
        public Nullable<int> IDTipologiaFluidoTermoVettore { get; set; }
        public string FluidoTermovettoreAltro { get; set; }
        public Nullable<decimal> PotenzaTermicaUtileNominaleKw { get; set; }
        public Nullable<decimal> RendimentoTermicoUtilePc { get; set; }
        public int IDTipologiaGruppiTermici { get; set; }
        public Nullable<decimal> AnalisiFumoPrevisteNr { get; set; }
        public Nullable<System.DateTime> DataInstallazione { get; set; }
        public Nullable<System.DateTime> DataDismissione { get; set; }
        public bool fAttivo { get; set; }
        public bool fDismesso { get; set; }
        public Nullable<System.DateTime> DataDismesso { get; set; }
        public Nullable<int> IDUtenteDismesso { get; set; }
    
        public virtual ICollection<LIM_LibrettiImpiantiBruciatori> LIM_LibrettiImpiantiBruciatori { get; set; }
        public virtual ICollection<RCT_RapportoDiControlloTecnicoGT> RCT_RapportoDiControlloTecnicoGT { get; set; }
        public virtual SYS_TipologiaCombustibile SYS_TipologiaCombustibile { get; set; }
        public virtual SYS_TipologiaFluidoTermoVettore SYS_TipologiaFluidoTermoVettore { get; set; }
        public virtual SYS_TipologiaGruppiTermici SYS_TipologiaGruppiTermici { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiRecuperatori> LIM_LibrettiImpiantiRecuperatori { get; set; }
        public virtual ICollection<VER_RegoleControlli> VER_RegoleControlli { get; set; }
        public virtual LIM_LibrettiImpianti LIM_LibrettiImpianti { get; set; }
    }
}
