//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIM_LibrettiImpiantiConsumoProdottiChimici
    {
        public int IDLibrettiImpiantiConsumoProdottiChimici { get; set; }
        public int IDLibrettoImpianto { get; set; }
        public Nullable<int> DataEsercizioStart { get; set; }
        public Nullable<int> DataEsercizioEnd { get; set; }
        public bool fCircuitoImpiantoTermico { get; set; }
        public bool fCircuitoAcs { get; set; }
        public bool fAltriCircuiti { get; set; }
        public string NomeProdotto { get; set; }
        public decimal Consumo { get; set; }
        public Nullable<int> IDUnitaMisura { get; set; }
        public Nullable<int> IDUtenteInserimento { get; set; }
        public Nullable<System.DateTime> DataInserimento { get; set; }
        public Nullable<int> IDUtenteUltimaModifica { get; set; }
        public Nullable<System.DateTime> DataUltimaModifica { get; set; }
    
        public virtual SYS_UnitaMisura SYS_UnitaMisura { get; set; }
        public virtual LIM_LibrettiImpianti LIM_LibrettiImpianti { get; set; }
    }
}
