//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIM_LibrettiImpiantiRecuperatori
    {
        public int IDLibrettoImpiantoRecuperatore { get; set; }
        public int IDLibrettoImpiantoGruppoTermico { get; set; }
        public Nullable<int> IDUtenteInserimento { get; set; }
        public Nullable<System.DateTime> DataInserimento { get; set; }
        public int IDLibrettoImpiantoInserimento { get; set; }
        public Nullable<int> IDUtenteUltimaModifica { get; set; }
        public Nullable<System.DateTime> DataUltimaModifica { get; set; }
        public int CodiceProgressivo { get; set; }
        public string Fabbricante { get; set; }
        public string Modello { get; set; }
        public string Matricola { get; set; }
        public Nullable<System.DateTime> DataInstallazione { get; set; }
        public Nullable<System.DateTime> DataDismissione { get; set; }
        public bool fAttivo { get; set; }
        public Nullable<decimal> PortataTermicaNominaleTotaleKw { get; set; }
        public string Prefisso { get; set; }
    
        public virtual LIM_LibrettiImpiantiGruppiTermici LIM_LibrettiImpiantiGruppiTermici { get; set; }
    }
}
