//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIM_LibrettiImpiantiResponsabili
    {
        public int IDLibrettoImpiantoResponsabili { get; set; }
        public int IDLibrettoImpianto { get; set; }
        public Nullable<int> IDSoggetto { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string CodiceFiscale { get; set; }
        public string RagioneSociale { get; set; }
        public string PartitaIva { get; set; }
        public string Email { get; set; }
        public string EmailPec { get; set; }
        public string NumeroCciaa { get; set; }
        public Nullable<int> IDProvinciaCciaa { get; set; }
        public Nullable<System.DateTime> DataInizio { get; set; }
        public Nullable<System.DateTime> DataFine { get; set; }
        public bool fAttivo { get; set; }
        public Nullable<int> IDUtenteInserimento { get; set; }
        public Nullable<System.DateTime> DataInserimento { get; set; }
        public Nullable<int> IDUtenteUltimaModifica { get; set; }
        public Nullable<System.DateTime> DataUltimaModifica { get; set; }
        public Nullable<System.DateTime> DataDichiarazioneDismissioneIncarico { get; set; }
        public Nullable<int> IDUtenteDichiarazioneDismissioneIncarico { get; set; }
    
        public virtual SYS_Province SYS_Province { get; set; }
        public virtual COM_AnagraficaSoggetti COM_AnagraficaSoggetti { get; set; }
        public virtual LIM_LibrettiImpianti LIM_LibrettiImpianti { get; set; }
    }
}
