//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIM_LibrettiImpiantiMacchineFrigorifere
    {
        public LIM_LibrettiImpiantiMacchineFrigorifere()
        {
            this.RCT_RapportoDiControlloTecnicoGF = new HashSet<RCT_RapportoDiControlloTecnicoGF>();
        }
    
        public int IDLibrettoImpiantoMacchinaFrigorifera { get; set; }
        public int IDLibrettoImpianto { get; set; }
        public Nullable<int> IDUtenteInserimento { get; set; }
        public Nullable<System.DateTime> DataInserimento { get; set; }
        public int IDLibrettoImpiantoInserimento { get; set; }
        public Nullable<int> IDUtenteUltimaModifica { get; set; }
        public Nullable<System.DateTime> DataUltimaModifica { get; set; }
        public string Prefisso { get; set; }
        public int CodiceProgressivo { get; set; }
        public string Fabbricante { get; set; }
        public string Modello { get; set; }
        public string Matricola { get; set; }
        public string FiltroFrigorigeno { get; set; }
        public Nullable<int> IDTipologiaMacchineFrigorifere { get; set; }
        public string Combustibile { get; set; }
        public Nullable<int> IDSorgenteLatoEsterno { get; set; }
        public Nullable<int> IDFluidoLatoUtenze { get; set; }
        public Nullable<decimal> NumCircuiti { get; set; }
        public Nullable<decimal> CoefficienteRiscaldamento { get; set; }
        public Nullable<decimal> CoefficienteRaffrescamento { get; set; }
        public Nullable<decimal> PotenzaFrigoriferaNominaleKw { get; set; }
        public Nullable<decimal> PortataTermicaNominaleKw { get; set; }
        public Nullable<decimal> PotenzaFrigoriferaAssorbitaNominaleKw { get; set; }
        public Nullable<decimal> PotenzaTermicaAssorbitaNominaleKw { get; set; }
        public Nullable<System.DateTime> DataInstallazione { get; set; }
        public Nullable<System.DateTime> DataDismissione { get; set; }
        public bool fAttivo { get; set; }
        public bool fDismesso { get; set; }
        public Nullable<System.DateTime> DataDismesso { get; set; }
        public Nullable<int> IDUtenteDismesso { get; set; }
    
        public virtual ICollection<RCT_RapportoDiControlloTecnicoGF> RCT_RapportoDiControlloTecnicoGF { get; set; }
        public virtual SYS_FluidoLatoUtenze SYS_FluidoLatoUtenze { get; set; }
        public virtual SYS_SorgenteLatoEsterno SYS_SorgenteLatoEsterno { get; set; }
        public virtual SYS_TipologiaMacchineFrigorifere SYS_TipologiaMacchineFrigorifere { get; set; }
        public virtual LIM_LibrettiImpianti LIM_LibrettiImpianti { get; set; }
    }
}
