//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIM_LibrettiImpianti
    {
        public LIM_LibrettiImpianti()
        {
            this.COM_RigaPortafoglio = new HashSet<COM_RigaPortafoglio>();
            this.RCT_RapportoDiControlloTecnicoBase = new HashSet<RCT_RapportoDiControlloTecnicoBase>();
            this.LIM_LibrettiImpiantiAccumuli = new HashSet<LIM_LibrettiImpiantiAccumuli>();
            this.LIM_LibrettiImpiantiAddolcimentoAcqua = new HashSet<LIM_LibrettiImpiantiAddolcimentoAcqua>();
            this.LIM_LibrettiImpiantiAltriGeneratori = new HashSet<LIM_LibrettiImpiantiAltriGeneratori>();
            this.LIM_LibrettiImpiantiCampiSolariTermici = new HashSet<LIM_LibrettiImpiantiCampiSolariTermici>();
            this.LIM_LibrettiImpiantiCircuitiInterrati = new HashSet<LIM_LibrettiImpiantiCircuitiInterrati>();
            this.LIM_LibrettiImpiantiCogeneratori = new HashSet<LIM_LibrettiImpiantiCogeneratori>();
            this.LIM_LibrettiImpiantiCondizionamentoChimico = new HashSet<LIM_LibrettiImpiantiCondizionamentoChimico>();
            this.LIM_LibrettiImpiantiConsumoAcqua = new HashSet<LIM_LibrettiImpiantiConsumoAcqua>();
            this.LIM_LibrettiImpiantiConsumoCombustibile = new HashSet<LIM_LibrettiImpiantiConsumoCombustibile>();
            this.LIM_LibrettiImpiantiConsumoEnergiaElettrica = new HashSet<LIM_LibrettiImpiantiConsumoEnergiaElettrica>();
            this.LIM_LibrettiImpiantiConsumoProdottiChimici = new HashSet<LIM_LibrettiImpiantiConsumoProdottiChimici>();
            this.LIM_LibrettiImpiantiDatiCatastali = new HashSet<LIM_LibrettiImpiantiDatiCatastali>();
            this.LIM_LibrettiImpiantiDescrizioniSistemi = new HashSet<LIM_LibrettiImpiantiDescrizioniSistemi>();
            this.LIM_LibrettiImpiantiGruppiTermici = new HashSet<LIM_LibrettiImpiantiGruppiTermici>();
            this.LIM_LibrettiImpiantiImpiantiVMC = new HashSet<LIM_LibrettiImpiantiImpiantiVMC>();
            this.LIM_LibrettiImpiantiMacchineFrigorifere = new HashSet<LIM_LibrettiImpiantiMacchineFrigorifere>();
            this.LIM_LibrettiImpiantiPompeCircolazione = new HashSet<LIM_LibrettiImpiantiPompeCircolazione>();
            this.LIM_LibrettiImpiantiRaffreddatoriLiquido = new HashSet<LIM_LibrettiImpiantiRaffreddatoriLiquido>();
            this.LIM_LibrettiImpiantiRecuperatoriCalore = new HashSet<LIM_LibrettiImpiantiRecuperatoriCalore>();
            this.LIM_LibrettiImpiantiResponsabili = new HashSet<LIM_LibrettiImpiantiResponsabili>();
            this.LIM_LibrettiImpiantiScambiatoriCalore = new HashSet<LIM_LibrettiImpiantiScambiatoriCalore>();
            this.LIM_LibrettiImpiantiScambiatoriCaloreIntermedi = new HashSet<LIM_LibrettiImpiantiScambiatoriCaloreIntermedi>();
            this.LIM_LibrettiImpiantiSistemiRegolazione = new HashSet<LIM_LibrettiImpiantiSistemiRegolazione>();
            this.LIM_LibrettiImpiantiTipologiaFiltrazioni = new HashSet<LIM_LibrettiImpiantiTipologiaFiltrazioni>();
            this.LIM_LibrettiImpiantiTipologiaFluidoVettore = new HashSet<LIM_LibrettiImpiantiTipologiaFluidoVettore>();
            this.LIM_LibrettiImpiantiTipologiaGeneratori = new HashSet<LIM_LibrettiImpiantiTipologiaGeneratori>();
            this.LIM_LibrettiImpiantiTipologiaSistemaDistribuzione = new HashSet<LIM_LibrettiImpiantiTipologiaSistemaDistribuzione>();
            this.LIM_LibrettiImpiantiTipologiaSistemiEmissione = new HashSet<LIM_LibrettiImpiantiTipologiaSistemiEmissione>();
            this.LIM_LibrettiImpiantiTorriEvaporative = new HashSet<LIM_LibrettiImpiantiTorriEvaporative>();
            this.LIM_LibrettiImpiantiTrattamentoAcquaAcs = new HashSet<LIM_LibrettiImpiantiTrattamentoAcquaAcs>();
            this.LIM_LibrettiImpiantiTrattamentoAcquaEstiva = new HashSet<LIM_LibrettiImpiantiTrattamentoAcquaEstiva>();
            this.LIM_LibrettiImpiantiTrattamentoAcquaInvernale = new HashSet<LIM_LibrettiImpiantiTrattamentoAcquaInvernale>();
            this.LIM_LibrettiImpiantiUnitaTrattamentoAria = new HashSet<LIM_LibrettiImpiantiUnitaTrattamentoAria>();
            this.LIM_LibrettiImpiantiValvoleRegolazione = new HashSet<LIM_LibrettiImpiantiValvoleRegolazione>();
            this.LIM_LibrettiImpiantiVasiEspansione = new HashSet<LIM_LibrettiImpiantiVasiEspansione>();
            this.VER_ProgrammaIspezioneInfo = new HashSet<VER_ProgrammaIspezioneInfo>();
            this.VER_RegoleControlli = new HashSet<VER_RegoleControlli>();
            this.VER_Accertamento = new HashSet<VER_Accertamento>();
        }
    
        public int IDLibrettoImpianto { get; set; }
        public Nullable<int> IDSoggetto { get; set; }
        public int IDSoggettoDerived { get; set; }
        public Nullable<int> IDTargaturaImpianto { get; set; }
        public int IDStatoLibrettoImpianto { get; set; }
        public Nullable<int> IDTipologiaIntervento { get; set; }
        public Nullable<System.DateTime> DataIntervento { get; set; }
        public string Indirizzo { get; set; }
        public string Civico { get; set; }
        public string Palazzo { get; set; }
        public string Scala { get; set; }
        public string Interno { get; set; }
        public Nullable<int> IDCodiceCatastale { get; set; }
        public bool fUnitaImmobiliare { get; set; }
        public Nullable<int> IDDestinazioneUso { get; set; }
        public Nullable<decimal> VolumeLordoRiscaldato { get; set; }
        public Nullable<decimal> VolumeLordoRaffrescato { get; set; }
        public string NumeroAPE { get; set; }
        public string NumeroPDR { get; set; }
        public string NumeroPOD { get; set; }
        public bool fAcs { get; set; }
        public Nullable<decimal> PotenzaAcs { get; set; }
        public bool fClimatizzazioneEstiva { get; set; }
        public Nullable<decimal> PotenzaClimatizzazioneEstiva { get; set; }
        public bool fClimatizzazioneInvernale { get; set; }
        public Nullable<decimal> PotenzaClimatizzazioneInvernale { get; set; }
        public bool fClimatizzazioneAltro { get; set; }
        public string ClimatizzazioneAltro { get; set; }
        public bool fPannelliSolariTermici { get; set; }
        public Nullable<decimal> SuperficieTotaleSolariTermici { get; set; }
        public Nullable<decimal> PotenzaSolariTermici { get; set; }
        public bool fPannelliSolariTermiciAltro { get; set; }
        public string PannelliSolariTermiciAltro { get; set; }
        public bool fPannelliSolariClimatizzazioneAcs { get; set; }
        public bool fPannelliSolariClimatizzazioneEstiva { get; set; }
        public bool fPannelliSolariClimatizzazioneInvernale { get; set; }
        public Nullable<decimal> ContenutoAcquaImpianto { get; set; }
        public Nullable<decimal> DurezzaTotaleAcquaImpianto { get; set; }
        public bool fTrattamentoAcquaInvernale { get; set; }
        public Nullable<decimal> DurezzaTotaleAcquaImpiantoInvernale { get; set; }
        public bool fProtezioneGelo { get; set; }
        public Nullable<int> IDTipologiaProtezioneGelo { get; set; }
        public bool fTrattamentoAcquaAcs { get; set; }
        public Nullable<decimal> DurezzaTotaleAcquaAcs { get; set; }
        public Nullable<decimal> PercentualeGlicole { get; set; }
        public Nullable<decimal> PhGlicole { get; set; }
        public bool fTrattamentoAcquaEstiva { get; set; }
        public Nullable<int> IDTipologiaCircuitoRaffreddamento { get; set; }
        public Nullable<int> IDTipologiaAcquaAlimento { get; set; }
        public bool fSistemaSpurgoAutomatico { get; set; }
        public Nullable<decimal> ConducibilitaAcquaIngresso { get; set; }
        public Nullable<decimal> ConducibilitaInizioSpurgo { get; set; }
        public bool fSistemaRegolazioneOnOff { get; set; }
        public bool fSistemaRegolazioneIntegrato { get; set; }
        public bool fSistemaRegolazioneIndipendente { get; set; }
        public bool fValvoleRegolazione { get; set; }
        public bool fSistemaRegolazioneMultigradino { get; set; }
        public bool fSistemaRegolazioneAInverter { get; set; }
        public bool fAltroSistemaRegolazionePrimaria { get; set; }
        public string SistemaRegolazionePrimariaAltro { get; set; }
        public Nullable<int> IDTipologiaTermostatoZona { get; set; }
        public bool fControlloEntalpico { get; set; }
        public bool fControlloPortataAriaVariabile { get; set; }
        public bool fValvoleTermostatiche { get; set; }
        public bool fValvoleDueVie { get; set; }
        public bool fValvoleTreVie { get; set; }
        public string NoteRegolazioneSingoloAmbiente { get; set; }
        public bool fTelelettura { get; set; }
        public bool fTelegestione { get; set; }
        public bool fContabilizzazione { get; set; }
        public bool fContabilizzazioneRiscaldamento { get; set; }
        public bool fContabilizzazioneRaffrescamento { get; set; }
        public bool fContabilizzazioneAcquaCalda { get; set; }
        public Nullable<int> IDTipologiaSistemaContabilizzazione { get; set; }
        public Nullable<bool> fCoibentazioneReteDistribuzione { get; set; }
        public string NoteCoibentazioneReteDistribuzione { get; set; }
        public string SistemaEmissioneAltro { get; set; }
        public Nullable<int> IDTipologiaResponsabile { get; set; }
        public Nullable<int> IDTipoSoggetto { get; set; }
        public string NomeResponsabile { get; set; }
        public string CognomeResponsabile { get; set; }
        public string CodiceFiscaleResponsabile { get; set; }
        public string RagioneSocialeResponsabile { get; set; }
        public string PartitaIvaResponsabile { get; set; }
        public string EmailResponsabile { get; set; }
        public string EmailPecResponsabile { get; set; }
        public string IndirizzoResponsabile { get; set; }
        public string CivicoResponsabile { get; set; }
        public Nullable<int> IDComuneResponsabile { get; set; }
        public Nullable<int> IDProvinciaResponsabile { get; set; }
        public bool fTerzoResponsabile { get; set; }
        public Nullable<int> IDUtenteInserimento { get; set; }
        public Nullable<System.DateTime> DataInserimento { get; set; }
        public Nullable<int> IDUtenteUltimaModifica { get; set; }
        public Nullable<System.DateTime> DataUltimaModifica { get; set; }
        public Nullable<int> IDLibrettoImpiantoRevisione { get; set; }
        public Nullable<int> NumeroRevisione { get; set; }
        public Nullable<System.DateTime> DataRevisione { get; set; }
        public Nullable<System.DateTime> DataAnnullamento { get; set; }
        public bool fAttivo { get; set; }
        public string JsonFormat { get; set; }
        public string KeyApi { get; set; }
        public System.Data.Entity.Spatial.DbGeography Coordinate { get; set; }
        public string IndirizzoNormalizzatoResponsabile { get; set; }
        public string CapResponsabile { get; set; }
        public string CivicoNormalizzatoResponsabile { get; set; }
    
        public virtual COM_AnagraficaSoggetti COM_AnagraficaSoggetti { get; set; }
        public virtual COM_AnagraficaSoggetti COM_AnagraficaSoggetti1 { get; set; }
        public virtual ICollection<COM_RigaPortafoglio> COM_RigaPortafoglio { get; set; }
        public virtual ICollection<RCT_RapportoDiControlloTecnicoBase> RCT_RapportoDiControlloTecnicoBase { get; set; }
        public virtual LIM_TargatureImpianti LIM_TargatureImpianti { get; set; }
        public virtual SYS_CodiciCatastali SYS_CodiciCatastali { get; set; }
        public virtual SYS_CodiciCatastali SYS_CodiciCatastali1 { get; set; }
        public virtual SYS_DestinazioneUso SYS_DestinazioneUso { get; set; }
        public virtual SYS_StatoLibrettoImpianto SYS_StatoLibrettoImpianto { get; set; }
        public virtual SYS_TipologiaAcquaAlimento SYS_TipologiaAcquaAlimento { get; set; }
        public virtual SYS_TipologiaCircuitoRaffreddamento SYS_TipologiaCircuitoRaffreddamento { get; set; }
        public virtual SYS_TipologiaIntervento SYS_TipologiaIntervento { get; set; }
        public virtual SYS_TipologiaProtezioneGelo SYS_TipologiaProtezioneGelo { get; set; }
        public virtual SYS_TipologiaResponsabile SYS_TipologiaResponsabile { get; set; }
        public virtual SYS_TipologiaSistemaContabilizzazione SYS_TipologiaSistemaContabilizzazione { get; set; }
        public virtual SYS_TipologiaTermostatoZona SYS_TipologiaTermostatoZona { get; set; }
        public virtual SYS_TipoSoggetto SYS_TipoSoggetto { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiAccumuli> LIM_LibrettiImpiantiAccumuli { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiAddolcimentoAcqua> LIM_LibrettiImpiantiAddolcimentoAcqua { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiAltriGeneratori> LIM_LibrettiImpiantiAltriGeneratori { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiCampiSolariTermici> LIM_LibrettiImpiantiCampiSolariTermici { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiCircuitiInterrati> LIM_LibrettiImpiantiCircuitiInterrati { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiCogeneratori> LIM_LibrettiImpiantiCogeneratori { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiCondizionamentoChimico> LIM_LibrettiImpiantiCondizionamentoChimico { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiConsumoAcqua> LIM_LibrettiImpiantiConsumoAcqua { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiConsumoCombustibile> LIM_LibrettiImpiantiConsumoCombustibile { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiConsumoEnergiaElettrica> LIM_LibrettiImpiantiConsumoEnergiaElettrica { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiConsumoProdottiChimici> LIM_LibrettiImpiantiConsumoProdottiChimici { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiDatiCatastali> LIM_LibrettiImpiantiDatiCatastali { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiDescrizioniSistemi> LIM_LibrettiImpiantiDescrizioniSistemi { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiGruppiTermici> LIM_LibrettiImpiantiGruppiTermici { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiImpiantiVMC> LIM_LibrettiImpiantiImpiantiVMC { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiMacchineFrigorifere> LIM_LibrettiImpiantiMacchineFrigorifere { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiPompeCircolazione> LIM_LibrettiImpiantiPompeCircolazione { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiRaffreddatoriLiquido> LIM_LibrettiImpiantiRaffreddatoriLiquido { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiRecuperatoriCalore> LIM_LibrettiImpiantiRecuperatoriCalore { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiResponsabili> LIM_LibrettiImpiantiResponsabili { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiScambiatoriCalore> LIM_LibrettiImpiantiScambiatoriCalore { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiScambiatoriCaloreIntermedi> LIM_LibrettiImpiantiScambiatoriCaloreIntermedi { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiSistemiRegolazione> LIM_LibrettiImpiantiSistemiRegolazione { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiTipologiaFiltrazioni> LIM_LibrettiImpiantiTipologiaFiltrazioni { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiTipologiaFluidoVettore> LIM_LibrettiImpiantiTipologiaFluidoVettore { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiTipologiaGeneratori> LIM_LibrettiImpiantiTipologiaGeneratori { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiTipologiaSistemaDistribuzione> LIM_LibrettiImpiantiTipologiaSistemaDistribuzione { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiTipologiaSistemiEmissione> LIM_LibrettiImpiantiTipologiaSistemiEmissione { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiTorriEvaporative> LIM_LibrettiImpiantiTorriEvaporative { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiTrattamentoAcquaAcs> LIM_LibrettiImpiantiTrattamentoAcquaAcs { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiTrattamentoAcquaEstiva> LIM_LibrettiImpiantiTrattamentoAcquaEstiva { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiTrattamentoAcquaInvernale> LIM_LibrettiImpiantiTrattamentoAcquaInvernale { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiUnitaTrattamentoAria> LIM_LibrettiImpiantiUnitaTrattamentoAria { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiValvoleRegolazione> LIM_LibrettiImpiantiValvoleRegolazione { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiVasiEspansione> LIM_LibrettiImpiantiVasiEspansione { get; set; }
        public virtual ICollection<VER_ProgrammaIspezioneInfo> VER_ProgrammaIspezioneInfo { get; set; }
        public virtual ICollection<VER_RegoleControlli> VER_RegoleControlli { get; set; }
        public virtual ICollection<VER_Accertamento> VER_Accertamento { get; set; }
    }
}
