//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogData
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DataOraEvento { get; set; }
        public string UserName { get; set; }
        public string TipoEvento { get; set; }
        public string HostName { get; set; }
        public string IndirizzoIP { get; set; }
        public string TipoOggetto { get; set; }
        public string NomeOggetto { get; set; }
        public string IDOggetto { get; set; }
        public string Note { get; set; }
    }
}
