//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNU_Menu
    {
        public MNU_Menu()
        {
            this.MNU_Menu1 = new HashSet<MNU_Menu>();
            this.SYS_UserAccess = new HashSet<SYS_UserAccess>();
        }
    
        public int IDMenu { get; set; }
        public string Menu { get; set; }
        public string PageUrl { get; set; }
        public int Ordine { get; set; }
        public Nullable<int> IDMenuParent { get; set; }
        public bool fattivo { get; set; }
        public bool fPrivate { get; set; }
        public bool fTile { get; set; }
        public Nullable<int> TileOrdine { get; set; }
        public string TileCssClassDimension { get; set; }
        public string TileCssClassColor { get; set; }
        public string TileImage { get; set; }
    
        public virtual ICollection<MNU_Menu> MNU_Menu1 { get; set; }
        public virtual MNU_Menu MNU_Menu2 { get; set; }
        public virtual ICollection<SYS_UserAccess> SYS_UserAccess { get; set; }
    }
}
