//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCT_LottiBolliniCalorePulito
    {
        public RCT_LottiBolliniCalorePulito()
        {
            this.COM_RigaPortafoglio = new HashSet<COM_RigaPortafoglio>();
            this.RCT_BollinoCalorePulito = new HashSet<RCT_BollinoCalorePulito>();
        }
    
        public int IdLottobolliniCalorePulito { get; set; }
        public int IDSoggetto { get; set; }
        public string CodiceLotto { get; set; }
        public int QuantitaBollini { get; set; }
        public System.DateTime DataAcquisto { get; set; }
    
        public virtual ICollection<COM_RigaPortafoglio> COM_RigaPortafoglio { get; set; }
        public virtual COM_AnagraficaSoggetti COM_AnagraficaSoggetti { get; set; }
        public virtual ICollection<RCT_BollinoCalorePulito> RCT_BollinoCalorePulito { get; set; }
    }
}
