//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCT_RapportoDiControlloTecnicoGT
    {
        public long Id { get; set; }
        public Nullable<decimal> TemperaturaFumi { get; set; }
        public Nullable<int> GeneratoriIdonei { get; set; }
        public Nullable<int> RegolazioneTemperaturaAmbiente { get; set; }
        public bool EvacuazioneForzata { get; set; }
        public bool EvacuazioneNaturale { get; set; }
        public Nullable<decimal> DepressioneCanaleFumo { get; set; }
        public Nullable<decimal> TemperaraturaComburente { get; set; }
        public Nullable<decimal> O2 { get; set; }
        public Nullable<decimal> Co2 { get; set; }
        public Nullable<decimal> RendimentoCombustione { get; set; }
        public Nullable<decimal> RendimentoMinimo { get; set; }
        public Nullable<int> DispositiviComandoRegolazione { get; set; }
        public Nullable<int> DispositiviSicurezza { get; set; }
        public Nullable<int> ValvolaSicurezzaSovrappressione { get; set; }
        public Nullable<int> ScambiatoreFumiPulito { get; set; }
        public Nullable<int> RiflussoProdottiCombustione { get; set; }
        public Nullable<int> ConformitaUNI10389 { get; set; }
        public Nullable<int> IdTipologiaGruppiTermici { get; set; }
        public Nullable<decimal> bacharach1 { get; set; }
        public Nullable<decimal> bacharach2 { get; set; }
        public Nullable<decimal> bacharach3 { get; set; }
        public Nullable<decimal> CoCorretto { get; set; }
        public string ModuloTermico { get; set; }
        public Nullable<decimal> PotenzaTermicaNominaleFocolare { get; set; }
        public Nullable<int> IDLIM_LibrettiImpiantiGruppitermici { get; set; }
        public Nullable<decimal> COFumiSecchi { get; set; }
        public Nullable<decimal> PortataCombustibile { get; set; }
        public bool RispettaIndiceBacharach { get; set; }
        public bool COFumiSecchiNoAria1000 { get; set; }
        public bool RendimentoSupMinimo { get; set; }
        public Nullable<int> IdTipologiaGeneratoriTermici { get; set; }
        public Nullable<decimal> PotenzaTermicaEffettiva { get; set; }
    
        public virtual SYS_TipologiaGeneratoriTermici SYS_TipologiaGeneratoriTermici { get; set; }
        public virtual SYS_TipologiaGruppiTermici SYS_TipologiaGruppiTermici { get; set; }
        public virtual LIM_LibrettiImpiantiGruppiTermici LIM_LibrettiImpiantiGruppiTermici { get; set; }
        public virtual RCT_RapportoDiControlloTecnicoBase RCT_RapportoDiControlloTecnicoBase { get; set; }
    }
}
