//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCT_RaccomandazioniPrescrizioni
    {
        public int IDRaccomandazioniPrescrizioni { get; set; }
        public long IDRapportoControlloTecnico { get; set; }
        public int IDTipologiaRaccomandazionePrescrizioneRct { get; set; }
        public Nullable<int> IDTipologiaRaccomandazione { get; set; }
        public Nullable<int> IDTipologiaPrescrizione { get; set; }
    
        public virtual SYS_RCTTipologiaPrescrizione SYS_RCTTipologiaPrescrizione { get; set; }
        public virtual SYS_RCTTipologiaRaccomandazione SYS_RCTTipologiaRaccomandazione { get; set; }
        public virtual RCT_RapportoDiControlloTecnicoBase RCT_RapportoDiControlloTecnicoBase { get; set; }
    }
}
