//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCT_RapportoDiControlloTecnicoCG
    {
        public long Id { get; set; }
        public Nullable<int> CapsulaInsonorizzataIdonea { get; set; }
        public Nullable<int> TenutaCircuitoOlioIdonea { get; set; }
        public Nullable<int> FunzionalitàScambiatoreSeparazione { get; set; }
        public Nullable<decimal> TemperaturaAriaComburente { get; set; }
        public Nullable<decimal> TemperaturaAcquaIngresso { get; set; }
        public Nullable<decimal> TemperaturaAcquauscita { get; set; }
        public Nullable<decimal> PotenzaAiMorsetti { get; set; }
        public Nullable<decimal> TemperaturaAcquaMotore { get; set; }
        public Nullable<decimal> TemperaturaFumiMonte { get; set; }
        public Nullable<decimal> TemperaturaFumiValle { get; set; }
        public Nullable<decimal> PotenzaElettricaMorsetti { get; set; }
        public Nullable<decimal> PotenzaAssorbitaCombustibile { get; set; }
        public Nullable<decimal> PotenzaMassimoRecupero { get; set; }
        public Nullable<decimal> PotenzaByPass { get; set; }
        public Nullable<decimal> EmissioneMonossido { get; set; }
        public Nullable<int> IdLIM_LibrettiImpiantiCogeneratori { get; set; }
        public Nullable<int> IDTipologiaFluidoTermoVettoreUscita { get; set; }
        public string AltroTipologiaFluidoTermoVettoreUscita { get; set; }
        public Nullable<decimal> SovrafrequenzaSogliaInterv1 { get; set; }
        public Nullable<decimal> SovrafrequenzaSogliaInterv2 { get; set; }
        public Nullable<decimal> SovrafrequenzaSogliaInterv3 { get; set; }
        public Nullable<decimal> SovrafrequenzaTempoInterv1 { get; set; }
        public Nullable<decimal> SovrafrequenzaTempoInterv2 { get; set; }
        public Nullable<decimal> SovrafrequenzaTempoInterv3 { get; set; }
        public Nullable<decimal> SottofrequenzaSogliaInterv1 { get; set; }
        public Nullable<decimal> SottofrequenzaSogliaInterv2 { get; set; }
        public Nullable<decimal> SottofrequenzaSogliaInterv3 { get; set; }
        public Nullable<decimal> SottofrequenzaTempoInterv1 { get; set; }
        public Nullable<decimal> SottofrequenzaTempoInterv2 { get; set; }
        public Nullable<decimal> SottofrequenzaTempoInterv3 { get; set; }
        public Nullable<decimal> SovratensioneSogliaInterv1 { get; set; }
        public Nullable<decimal> SovratensioneSogliaInterv2 { get; set; }
        public Nullable<decimal> SovratensioneSogliaInterv3 { get; set; }
        public Nullable<decimal> SovratensioneTempoInterv1 { get; set; }
        public Nullable<decimal> SovratensioneTempoInterv2 { get; set; }
        public Nullable<decimal> SovratensioneTempoInterv3 { get; set; }
        public Nullable<decimal> SottotensioneSogliaInterv1 { get; set; }
        public Nullable<decimal> SottotensioneSogliaInterv2 { get; set; }
        public Nullable<decimal> SottotensioneSogliaInterv3 { get; set; }
        public Nullable<decimal> SottotensioneTempoInterv1 { get; set; }
        public Nullable<decimal> SottotensioneTempoInterv2 { get; set; }
        public Nullable<decimal> SottotensioneTempoInterv3 { get; set; }
        public Nullable<int> IDTipologiaCogeneratore { get; set; }
    
        public virtual SYS_TipologiaFluidoTermoVettore SYS_TipologiaFluidoTermoVettore { get; set; }
        public virtual SYS_TipologiaCogeneratore SYS_TipologiaCogeneratore { get; set; }
        public virtual LIM_LibrettiImpiantiCogeneratori LIM_LibrettiImpiantiCogeneratori { get; set; }
        public virtual RCT_RapportoDiControlloTecnicoBase RCT_RapportoDiControlloTecnicoBase { get; set; }
    }
}
