//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCT_BollinoCalorePulitoConvertito
    {
        public int IDBollinoCalorePulitoConvertito { get; set; }
        public System.Guid IDMovimento { get; set; }
        public long IDBollinoCalorePulito { get; set; }
    
        public virtual COM_RigaPortafoglio COM_RigaPortafoglio { get; set; }
        public virtual RCT_BollinoCalorePulito RCT_BollinoCalorePulito { get; set; }
    }
}
