//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCT_RapportoDiControlloTecnicoBase
    {
        public RCT_RapportoDiControlloTecnicoBase()
        {
            this.COM_Questionari = new HashSet<COM_Questionari>();
            this.RCT_FirmaDigitale = new HashSet<RCT_FirmaDigitale>();
            this.RCT_RaccomandazioniPrescrizioni = new HashSet<RCT_RaccomandazioniPrescrizioni>();
            this.RCT_RapportoDiControlloTecnicoBaseCheckList = new HashSet<RCT_RapportoDiControlloTecnicoBaseCheckList>();
            this.RCT_RapportoDiControlloTecnicoBaseTrattamentoAcs = new HashSet<RCT_RapportoDiControlloTecnicoBaseTrattamentoAcs>();
            this.RCT_RapportoDiControlloTecnicoBaseTrattamentoInvernale = new HashSet<RCT_RapportoDiControlloTecnicoBaseTrattamentoInvernale>();
            this.RCT_BollinoCalorePulito = new HashSet<RCT_BollinoCalorePulito>();
            this.VER_Accertamento = new HashSet<VER_Accertamento>();
        }
    
        public long IDRapportoControlloTecnico { get; set; }
        public int IDSoggetto { get; set; }
        public Nullable<int> IDSoggettoDerived { get; set; }
        public int IDTargaturaImpianto { get; set; }
        public Nullable<decimal> PotenzaTermicaNominale { get; set; }
        public string Indirizzo { get; set; }
        public string Civico { get; set; }
        public string Palazzo { get; set; }
        public string Scala { get; set; }
        public string Interno { get; set; }
        public Nullable<int> IDCodiceCatastale { get; set; }
        public int IDTipologiaRCT { get; set; }
        public int IDLibrettoImpianto { get; set; }
        public int IDStatoRapportoDiControllo { get; set; }
        public int IDTipologiaControllo { get; set; }
        public Nullable<int> IDTipologiaResponsabile { get; set; }
        public Nullable<int> IDTipoSoggetto { get; set; }
        public string NomeResponsabile { get; set; }
        public string CognomeResponsabile { get; set; }
        public string CodiceFiscaleResponsabile { get; set; }
        public string RagioneSocialeResponsabile { get; set; }
        public string PartitaIVAResponsabile { get; set; }
        public string IndirizzoResponsabile { get; set; }
        public string CivicoResponsabile { get; set; }
        public string ComuneResponsabile { get; set; }
        public Nullable<int> IDProvinciaResponsabile { get; set; }
        public string RagioneSocialeTerzoResponsabile { get; set; }
        public string PartitaIVATerzoResponsabile { get; set; }
        public string IndirizzoTerzoResponsabile { get; set; }
        public string CivicoTerzoResponsabile { get; set; }
        public string ComuneTerzoResponsabile { get; set; }
        public Nullable<int> IDProvinciaTerzoResponsabile { get; set; }
        public string RagioneSocialeImpresaManutentrice { get; set; }
        public string PartitaIVAImpresaManutentrice { get; set; }
        public string IndirizzoImpresaManutentrice { get; set; }
        public string CivicoImpresaManutentrice { get; set; }
        public string ComuneImpresaManutentrice { get; set; }
        public Nullable<int> IDProvinciaImpresaManutentrice { get; set; }
        public Nullable<int> LocaleInstallazioneIdoneo { get; set; }
        public Nullable<decimal> PotenzaTermicaNominaleTotaleMax { get; set; }
        public bool fDichiarazioneConformita { get; set; }
        public bool fLibrettoImpiantoPresente { get; set; }
        public bool fUsoManutenzioneGeneratore { get; set; }
        public bool fLibrettoImpiantoCompilato { get; set; }
        public Nullable<decimal> DurezzaAcqua { get; set; }
        public Nullable<int> TrattamentoACS { get; set; }
        public Nullable<int> TrattamentoRiscaldamento { get; set; }
        public Nullable<int> ApertureLibere { get; set; }
        public Nullable<int> DimensioniApertureAdeguate { get; set; }
        public Nullable<int> LineeElettricheIdonee { get; set; }
        public Nullable<int> CoibentazioniIdonee { get; set; }
        public Nullable<int> StatoCoibentazioniIdonee { get; set; }
        public Nullable<int> AssenzaPerditeCombustibile { get; set; }
        public Nullable<int> TenutaImpiantoIdraulico { get; set; }
        public Nullable<int> ScarichiIdonei { get; set; }
        public string Prefisso { get; set; }
        public int CodiceProgressivo { get; set; }
        public Nullable<System.DateTime> DataInstallazione { get; set; }
        public string Fabbricante { get; set; }
        public string Modello { get; set; }
        public string Matricola { get; set; }
        public bool fClimatizzazioneInvernale { get; set; }
        public bool fProduzioneACS { get; set; }
        public bool fClimatizzazioneEstiva { get; set; }
        public Nullable<int> IDTipologiaCombustibile { get; set; }
        public string AltroCombustibile { get; set; }
        public Nullable<int> IDTipologiaFluidoTermoVettore { get; set; }
        public string Osservazioni { get; set; }
        public string Raccomandazioni { get; set; }
        public string Prescrizioni { get; set; }
        public bool fImpiantoFunzionante { get; set; }
        public Nullable<System.DateTime> DataManutenzioneConsigliata { get; set; }
        public Nullable<System.DateTime> DataControllo { get; set; }
        public Nullable<System.DateTime> OraArrivo { get; set; }
        public Nullable<System.DateTime> OraPartenza { get; set; }
        public Nullable<int> IDTipologiaSistemaDistribuzione { get; set; }
        public string AltroTipologiaSistemaDistribuzione { get; set; }
        public Nullable<int> Contabilizzazione { get; set; }
        public Nullable<int> IDTipologiaContabilizzazione { get; set; }
        public Nullable<int> Termoregolazione { get; set; }
        public Nullable<int> CorrettoFunzionamentoContabilizzazione { get; set; }
        public string JsonFormat { get; set; }
        public string GuidRapportoTecnico { get; set; }
        public Nullable<System.DateTime> DataInserimento { get; set; }
        public Nullable<System.DateTime> DataAnnullamento { get; set; }
        public string KeyApi { get; set; }
        public string guidInteroImpianto { get; set; }
    
        public virtual ICollection<COM_Questionari> COM_Questionari { get; set; }
        public virtual LIM_TargatureImpianti LIM_TargatureImpianti { get; set; }
        public virtual ICollection<RCT_FirmaDigitale> RCT_FirmaDigitale { get; set; }
        public virtual ICollection<RCT_RaccomandazioniPrescrizioni> RCT_RaccomandazioniPrescrizioni { get; set; }
        public virtual SYS_CodiciCatastali SYS_CodiciCatastali { get; set; }
        public virtual SYS_TipologiaCombustibile SYS_TipologiaCombustibile { get; set; }
        public virtual SYS_TipologiaFluidoTermoVettore SYS_TipologiaFluidoTermoVettore { get; set; }
        public virtual SYS_TipologiaResponsabile SYS_TipologiaResponsabile { get; set; }
        public virtual RCT_RapportoDiControlloTecnicoCG RCT_RapportoDiControlloTecnicoCG { get; set; }
        public virtual RCT_RapportoDiControlloTecnicoGF RCT_RapportoDiControlloTecnicoGF { get; set; }
        public virtual RCT_RapportoDiControlloTecnicoGT RCT_RapportoDiControlloTecnicoGT { get; set; }
        public virtual RCT_RapportoDiControlloTecnicoSC RCT_RapportoDiControlloTecnicoSC { get; set; }
        public virtual SYS_StatoRapportoDiControllo SYS_StatoRapportoDiControllo { get; set; }
        public virtual SYS_TipologiaContabilizzazione SYS_TipologiaContabilizzazione { get; set; }
        public virtual SYS_TipologiaControllo SYS_TipologiaControllo { get; set; }
        public virtual SYS_TipologiaRapportoDiControllo SYS_TipologiaRapportoDiControllo { get; set; }
        public virtual SYS_TipologiaSistemaDistribuzione SYS_TipologiaSistemaDistribuzione { get; set; }
        public virtual SYS_TipoSoggetto SYS_TipoSoggetto { get; set; }
        public virtual ICollection<RCT_RapportoDiControlloTecnicoBaseCheckList> RCT_RapportoDiControlloTecnicoBaseCheckList { get; set; }
        public virtual ICollection<RCT_RapportoDiControlloTecnicoBaseTrattamentoAcs> RCT_RapportoDiControlloTecnicoBaseTrattamentoAcs { get; set; }
        public virtual ICollection<RCT_RapportoDiControlloTecnicoBaseTrattamentoInvernale> RCT_RapportoDiControlloTecnicoBaseTrattamentoInvernale { get; set; }
        public virtual COM_AnagraficaSoggetti COM_AnagraficaSoggetti { get; set; }
        public virtual LIM_LibrettiImpianti LIM_LibrettiImpianti { get; set; }
        public virtual ICollection<RCT_BollinoCalorePulito> RCT_BollinoCalorePulito { get; set; }
        public virtual ICollection<VER_Accertamento> VER_Accertamento { get; set; }
    }
}
