//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCT_RapportoDiControlloTecnicoGF
    {
        public long Id { get; set; }
        public Nullable<decimal> TemperaturaSurriscaldamento { get; set; }
        public Nullable<decimal> TemperaturaSottoraffreddamento { get; set; }
        public Nullable<decimal> TemperaturaCondensazione { get; set; }
        public Nullable<decimal> TemperaturaEvaporazione { get; set; }
        public Nullable<decimal> TInglatoEst { get; set; }
        public Nullable<decimal> TUscLatoEst { get; set; }
        public Nullable<decimal> TIngLatoUtenze { get; set; }
        public Nullable<decimal> TUscLatoUtenze { get; set; }
        public Nullable<int> AssenzaPerditeRefrigerante { get; set; }
        public Nullable<int> LeakDetector { get; set; }
        public Nullable<int> ParametriTermodinamici { get; set; }
        public Nullable<int> ScambiatoriLiberi { get; set; }
        public Nullable<decimal> Potenzafrigorifera { get; set; }
        public bool ProvaRaffrescamento { get; set; }
        public bool ProvaRiscaldamento { get; set; }
        public Nullable<int> IdLIM_LibrettiImpiantiMacchineFrigorifere { get; set; }
        public Nullable<int> IDTipologiemacchineFrigorifere { get; set; }
        public Nullable<decimal> NCircuiti { get; set; }
        public Nullable<int> FiltriPuliti { get; set; }
        public Nullable<decimal> PotenzaAssorbita { get; set; }
        public Nullable<decimal> TUscitaFluido { get; set; }
        public Nullable<decimal> TBulboUmidoAria { get; set; }
        public Nullable<decimal> TIngressoLatoEsterno { get; set; }
        public Nullable<decimal> TUscitaLatoEsterno { get; set; }
        public Nullable<decimal> TIngressoLatoMacchina { get; set; }
        public Nullable<decimal> TUscitaLatoMacchina { get; set; }
        public Nullable<decimal> NCircuitiTotali { get; set; }
    
        public virtual SYS_TipologiaMacchineFrigorifere SYS_TipologiaMacchineFrigorifere { get; set; }
        public virtual LIM_LibrettiImpiantiMacchineFrigorifere LIM_LibrettiImpiantiMacchineFrigorifere { get; set; }
        public virtual RCT_RapportoDiControlloTecnicoBase RCT_RapportoDiControlloTecnicoBase { get; set; }
    }
}
