//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCT_RapportoDiControlloTecnicoSC
    {
        public long Id { get; set; }
        public Nullable<decimal> TemperaturaEsterna { get; set; }
        public Nullable<decimal> TemperaturaMandataPrimario { get; set; }
        public Nullable<decimal> TemperaturaRitornoPrimario { get; set; }
        public Nullable<decimal> PotenzaTermica { get; set; }
        public Nullable<decimal> PortataFluidoPrimario { get; set; }
        public Nullable<decimal> TemperaturaMandataSecondario { get; set; }
        public Nullable<decimal> TemperaturaRitornoSecondario { get; set; }
        public Nullable<int> PotenzaCompatibileProgetto { get; set; }
        public Nullable<int> AssenzaTrafilamenti { get; set; }
        public Nullable<int> IdLIM_LibrettiImpiantiScambaitoriCalore { get; set; }
        public Nullable<int> DispositiviComandoRegolazione { get; set; }
        public Nullable<int> IDTipologiaFluidoTermoVettoreEntrata { get; set; }
        public string AltroTipologiaFluidoTermoVettoreEntrata { get; set; }
        public Nullable<int> IDTipologiaFluidoTermoVettoreUscita { get; set; }
        public string AltroTipologiaFluidoTermoVettoreUscita { get; set; }
    
        public virtual SYS_TipologiaFluidoTermoVettore SYS_TipologiaFluidoTermoVettore { get; set; }
        public virtual SYS_TipologiaFluidoTermoVettore SYS_TipologiaFluidoTermoVettore1 { get; set; }
        public virtual LIM_LibrettiImpiantiScambiatoriCalore LIM_LibrettiImpiantiScambiatoriCalore { get; set; }
        public virtual RCT_RapportoDiControlloTecnicoBase RCT_RapportoDiControlloTecnicoBase { get; set; }
    }
}
