//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_ClassificazioneImpianto
    {
        public SYS_ClassificazioneImpianto()
        {
            this.COM_ClassificazioniImpianto = new HashSet<COM_ClassificazioniImpianto>();
        }
    
        public int IDClassificazioneImpianto { get; set; }
        public string ClassificazioneImpianto { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<COM_ClassificazioniImpianto> COM_ClassificazioniImpianto { get; set; }
    }
}
