//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TipoSoggetto
    {
        public SYS_TipoSoggetto()
        {
            this.SYS_FormeGiuridiche = new HashSet<SYS_FormeGiuridiche>();
            this.SYS_FunzioniSoggetti = new HashSet<SYS_FunzioniSoggetti>();
            this.RCT_RapportoDiControlloTecnicoBase = new HashSet<RCT_RapportoDiControlloTecnicoBase>();
            this.SYS_StatoAccreditamento = new HashSet<SYS_StatoAccreditamento>();
            this.COM_AnagraficaSoggetti = new HashSet<COM_AnagraficaSoggetti>();
            this.LIM_LibrettiImpianti = new HashSet<LIM_LibrettiImpianti>();
        }
    
        public int IDTipoSoggetto { get; set; }
        public string TipoSoggetto { get; set; }
        public string TipoSoggettoImage { get; set; }
        public bool fIscrizione { get; set; }
        public bool fattivo { get; set; }
    
        public virtual ICollection<SYS_FormeGiuridiche> SYS_FormeGiuridiche { get; set; }
        public virtual ICollection<SYS_FunzioniSoggetti> SYS_FunzioniSoggetti { get; set; }
        public virtual ICollection<RCT_RapportoDiControlloTecnicoBase> RCT_RapportoDiControlloTecnicoBase { get; set; }
        public virtual ICollection<SYS_StatoAccreditamento> SYS_StatoAccreditamento { get; set; }
        public virtual ICollection<COM_AnagraficaSoggetti> COM_AnagraficaSoggetti { get; set; }
        public virtual ICollection<LIM_LibrettiImpianti> LIM_LibrettiImpianti { get; set; }
    }
}
