//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TipologiaVentilatori
    {
        public SYS_TipologiaVentilatori()
        {
            this.LIM_LibrettiImpiantiRaffreddatoriLiquido = new HashSet<LIM_LibrettiImpiantiRaffreddatoriLiquido>();
            this.LIM_LibrettiImpiantiTorriEvaporative = new HashSet<LIM_LibrettiImpiantiTorriEvaporative>();
        }
    
        public int IDTipologiaVentilatori { get; set; }
        public string TipologiaVentilatori { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<LIM_LibrettiImpiantiRaffreddatoriLiquido> LIM_LibrettiImpiantiRaffreddatoriLiquido { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiTorriEvaporative> LIM_LibrettiImpiantiTorriEvaporative { get; set; }
    }
}
