//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TipoSistema
    {
        public SYS_TipoSistema()
        {
            this.LIM_LibrettiImpiantiDescrizioniSistemi = new HashSet<LIM_LibrettiImpiantiDescrizioniSistemi>();
        }
    
        public int IDTipoSistema { get; set; }
        public string TipoSistema { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<LIM_LibrettiImpiantiDescrizioniSistemi> LIM_LibrettiImpiantiDescrizioniSistemi { get; set; }
    }
}
