//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TipologiaTrattamentoAcqua
    {
        public SYS_TipologiaTrattamentoAcqua()
        {
            this.LIM_LibrettiImpiantiTrattamentoAcquaAcs = new HashSet<LIM_LibrettiImpiantiTrattamentoAcquaAcs>();
            this.LIM_LibrettiImpiantiTrattamentoAcquaEstiva = new HashSet<LIM_LibrettiImpiantiTrattamentoAcquaEstiva>();
            this.LIM_LibrettiImpiantiTrattamentoAcquaInvernale = new HashSet<LIM_LibrettiImpiantiTrattamentoAcquaInvernale>();
            this.RCT_RapportoDiControlloTecnicoBaseTrattamentoAcs = new HashSet<RCT_RapportoDiControlloTecnicoBaseTrattamentoAcs>();
            this.RCT_RapportoDiControlloTecnicoBaseTrattamentoInvernale = new HashSet<RCT_RapportoDiControlloTecnicoBaseTrattamentoInvernale>();
        }
    
        public int IDTipologiaTrattamentoAcqua { get; set; }
        public string TipologiaTrattamentoAcqua { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<LIM_LibrettiImpiantiTrattamentoAcquaAcs> LIM_LibrettiImpiantiTrattamentoAcquaAcs { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiTrattamentoAcquaEstiva> LIM_LibrettiImpiantiTrattamentoAcquaEstiva { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiTrattamentoAcquaInvernale> LIM_LibrettiImpiantiTrattamentoAcquaInvernale { get; set; }
        public virtual ICollection<RCT_RapportoDiControlloTecnicoBaseTrattamentoAcs> RCT_RapportoDiControlloTecnicoBaseTrattamentoAcs { get; set; }
        public virtual ICollection<RCT_RapportoDiControlloTecnicoBaseTrattamentoInvernale> RCT_RapportoDiControlloTecnicoBaseTrattamentoInvernale { get; set; }
    }
}
