//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_StatoIspezione
    {
        public SYS_StatoIspezione()
        {
            this.VER_IspezioneStato = new HashSet<VER_IspezioneStato>();
            this.VER_Ispezione = new HashSet<VER_Ispezione>();
        }
    
        public int IDStatoIspezione { get; set; }
        public string StatoIspezione { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<VER_IspezioneStato> VER_IspezioneStato { get; set; }
        public virtual ICollection<VER_Ispezione> VER_Ispezione { get; set; }
    }
}
