//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Paesi
    {
        public SYS_Paesi()
        {
            this.COM_AnagraficaSoggetti = new HashSet<COM_AnagraficaSoggetti>();
            this.COM_AnagraficaSoggetti1 = new HashSet<COM_AnagraficaSoggetti>();
            this.COM_AnagraficaSoggetti2 = new HashSet<COM_AnagraficaSoggetti>();
            this.COM_AnagraficaSoggetti3 = new HashSet<COM_AnagraficaSoggetti>();
        }
    
        public int IDPaese { get; set; }
        public string Paese { get; set; }
        public bool fAttivo { get; set; }
        public string CodiceIso { get; set; }
    
        public virtual ICollection<COM_AnagraficaSoggetti> COM_AnagraficaSoggetti { get; set; }
        public virtual ICollection<COM_AnagraficaSoggetti> COM_AnagraficaSoggetti1 { get; set; }
        public virtual ICollection<COM_AnagraficaSoggetti> COM_AnagraficaSoggetti2 { get; set; }
        public virtual ICollection<COM_AnagraficaSoggetti> COM_AnagraficaSoggetti3 { get; set; }
    }
}
