//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TipologiaAddolcimentoAcqua
    {
        public SYS_TipologiaAddolcimentoAcqua()
        {
            this.LIM_LibrettiImpiantiAddolcimentoAcqua = new HashSet<LIM_LibrettiImpiantiAddolcimentoAcqua>();
        }
    
        public int IDTipologiaAddolcimentoAcqua { get; set; }
        public string TipologiaAddolcimentoAcqua { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<LIM_LibrettiImpiantiAddolcimentoAcqua> LIM_LibrettiImpiantiAddolcimentoAcqua { get; set; }
    }
}
