//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TipoAccertamento
    {
        public SYS_TipoAccertamento()
        {
            this.VER_ProgrammaAccertamento = new HashSet<VER_ProgrammaAccertamento>();
            this.SYS_ProceduraAccertamento = new HashSet<SYS_ProceduraAccertamento>();
            this.VER_Accertamento = new HashSet<VER_Accertamento>();
        }
    
        public int IDTipoAccertamento { get; set; }
        public string TipoAccertamento { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<VER_ProgrammaAccertamento> VER_ProgrammaAccertamento { get; set; }
        public virtual ICollection<SYS_ProceduraAccertamento> SYS_ProceduraAccertamento { get; set; }
        public virtual ICollection<VER_Accertamento> VER_Accertamento { get; set; }
    }
}
