//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TipologiaGeneratori
    {
        public SYS_TipologiaGeneratori()
        {
            this.LIM_LibrettiImpiantiTipologiaGeneratori = new HashSet<LIM_LibrettiImpiantiTipologiaGeneratori>();
        }
    
        public int IDTipologiaGeneratori { get; set; }
        public string TipologiaGeneratori { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<LIM_LibrettiImpiantiTipologiaGeneratori> LIM_LibrettiImpiantiTipologiaGeneratori { get; set; }
    }
}
