//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TipologiaInterventoAccertamento
    {
        public SYS_TipologiaInterventoAccertamento()
        {
            this.VER_AccertamentoNonConformita = new HashSet<VER_AccertamentoNonConformita>();
        }
    
        public int IDTipologiaInterventoAccertamento { get; set; }
        public string TipologiaInterventoAccertamento { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<VER_AccertamentoNonConformita> VER_AccertamentoNonConformita { get; set; }
    }
}
