//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_QuestionarioTipoRisposte
    {
        public SYS_QuestionarioTipoRisposte()
        {
            this.SYS_QuestionarioRisposte = new HashSet<SYS_QuestionarioRisposte>();
            this.COM_QuestionariRisposte = new HashSet<COM_QuestionariRisposte>();
        }
    
        public int IDQuestionarioTipoRisposta { get; set; }
        public string TipoRisposta { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<SYS_QuestionarioRisposte> SYS_QuestionarioRisposte { get; set; }
        public virtual ICollection<COM_QuestionariRisposte> COM_QuestionariRisposte { get; set; }
    }
}
