//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TipologiaDistributori
    {
        public SYS_TipologiaDistributori()
        {
            this.VER_Accertamento = new HashSet<VER_Accertamento>();
        }
    
        public int IDDistributore { get; set; }
        public int IDCodiceCatastale { get; set; }
        public string Distributore { get; set; }
        public string Indirizzo { get; set; }
        public string PartitaIva { get; set; }
        public string EmailPec { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual SYS_CodiciCatastali SYS_CodiciCatastali { get; set; }
        public virtual ICollection<VER_Accertamento> VER_Accertamento { get; set; }
    }
}
