//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Orario
    {
        public SYS_Orario()
        {
            this.VER_IspezioneStato = new HashSet<VER_IspezioneStato>();
            this.VER_IspezioneStato1 = new HashSet<VER_IspezioneStato>();
            this.VER_Ispezione = new HashSet<VER_Ispezione>();
            this.VER_Ispezione1 = new HashSet<VER_Ispezione>();
            this.VER_Ispezione2 = new HashSet<VER_Ispezione>();
            this.VER_Ispezione3 = new HashSet<VER_Ispezione>();
        }
    
        public int IDOrario { get; set; }
        public string Orario { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<VER_IspezioneStato> VER_IspezioneStato { get; set; }
        public virtual ICollection<VER_IspezioneStato> VER_IspezioneStato1 { get; set; }
        public virtual ICollection<VER_Ispezione> VER_Ispezione { get; set; }
        public virtual ICollection<VER_Ispezione> VER_Ispezione1 { get; set; }
        public virtual ICollection<VER_Ispezione> VER_Ispezione2 { get; set; }
        public virtual ICollection<VER_Ispezione> VER_Ispezione3 { get; set; }
    }
}
