//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_SvolgimentoIspezione
    {
        public SYS_SvolgimentoIspezione()
        {
            this.VER_Ispezione = new HashSet<VER_Ispezione>();
        }
    
        public int IDSvolgimentoIspezione { get; set; }
        public string SvolgimentoIspezione { get; set; }
        public bool IsIspezioneSvolta { get; set; }
        public bool fattivo { get; set; }
    
        public virtual ICollection<VER_Ispezione> VER_Ispezione { get; set; }
    }
}
