//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TipologiaCombustibile
    {
        public SYS_TipologiaCombustibile()
        {
            this.LIM_LibrettiImpiantiConsumoCombustibile = new HashSet<LIM_LibrettiImpiantiConsumoCombustibile>();
            this.LIM_LibrettiImpiantiCogeneratori = new HashSet<LIM_LibrettiImpiantiCogeneratori>();
            this.LIM_LibrettiImpiantiGruppiTermici = new HashSet<LIM_LibrettiImpiantiGruppiTermici>();
            this.RCT_RapportoDiControlloTecnicoBase = new HashSet<RCT_RapportoDiControlloTecnicoBase>();
            this.VER_RegoleControlli = new HashSet<VER_RegoleControlli>();
            this.VER_Accertamento = new HashSet<VER_Accertamento>();
        }
    
        public int IDTipologiaCombustibile { get; set; }
        public string TipologiaCombustibile { get; set; }
        public bool fAttivo { get; set; }
        public bool Biomassa { get; set; }
        public decimal LimiteFisicoCO2 { get; set; }
        public bool Liquido { get; set; }
        public bool Gas { get; set; }
    
        public virtual ICollection<LIM_LibrettiImpiantiConsumoCombustibile> LIM_LibrettiImpiantiConsumoCombustibile { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiCogeneratori> LIM_LibrettiImpiantiCogeneratori { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiGruppiTermici> LIM_LibrettiImpiantiGruppiTermici { get; set; }
        public virtual ICollection<RCT_RapportoDiControlloTecnicoBase> RCT_RapportoDiControlloTecnicoBase { get; set; }
        public virtual ICollection<VER_RegoleControlli> VER_RegoleControlli { get; set; }
        public virtual ICollection<VER_Accertamento> VER_Accertamento { get; set; }
    }
}
