//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TipologiaSistemiEmissione
    {
        public SYS_TipologiaSistemiEmissione()
        {
            this.LIM_LibrettiImpiantiTipologiaSistemiEmissione = new HashSet<LIM_LibrettiImpiantiTipologiaSistemiEmissione>();
        }
    
        public int IDTipologiaSistemiEmissione { get; set; }
        public string TipologiaSistemiEmissione { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<LIM_LibrettiImpiantiTipologiaSistemiEmissione> LIM_LibrettiImpiantiTipologiaSistemiEmissione { get; set; }
    }
}
