//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TipologiaAcquaAlimento
    {
        public SYS_TipologiaAcquaAlimento()
        {
            this.LIM_LibrettiImpianti = new HashSet<LIM_LibrettiImpianti>();
        }
    
        public int IDTipologiaAcquaAlimento { get; set; }
        public string TipologiaAcquaAlimento { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<LIM_LibrettiImpianti> LIM_LibrettiImpianti { get; set; }
    }
}
