//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TipologiaGeneratoriTermici
    {
        public SYS_TipologiaGeneratoriTermici()
        {
            this.RCT_RapportoDiControlloTecnicoGT = new HashSet<RCT_RapportoDiControlloTecnicoGT>();
        }
    
        public int IdTipologiaGeneratoriTermici { get; set; }
        public string Descrizione { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<RCT_RapportoDiControlloTecnicoGT> RCT_RapportoDiControlloTecnicoGT { get; set; }
    }
}
