//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TipologiaCogeneratore
    {
        public SYS_TipologiaCogeneratore()
        {
            this.RCT_RapportoDiControlloTecnicoCG = new HashSet<RCT_RapportoDiControlloTecnicoCG>();
            this.LIM_LibrettiImpiantiCogeneratori = new HashSet<LIM_LibrettiImpiantiCogeneratori>();
        }
    
        public int IDTipologiaCogeneratore { get; set; }
        public string TipologiaCogeneratore { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<RCT_RapportoDiControlloTecnicoCG> RCT_RapportoDiControlloTecnicoCG { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiCogeneratori> LIM_LibrettiImpiantiCogeneratori { get; set; }
    }
}
