//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_UserAccess
    {
        public int IDAccess { get; set; }
        public Nullable<int> IDMenu { get; set; }
        public Nullable<int> IDRole { get; set; }
        public bool fActive { get; set; }
    
        public virtual SYS_UserRole SYS_UserRole { get; set; }
        public virtual MNU_Menu MNU_Menu { get; set; }
    }
}
