//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TipoIspezione
    {
        public SYS_TipoIspezione()
        {
            this.VER_ProgrammaIspezioneInfo = new HashSet<VER_ProgrammaIspezioneInfo>();
            this.VER_IspezioneVisitaInfo = new HashSet<VER_IspezioneVisitaInfo>();
        }
    
        public int IDTipoIspezione { get; set; }
        public string TipoIspezione { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<VER_ProgrammaIspezioneInfo> VER_ProgrammaIspezioneInfo { get; set; }
        public virtual ICollection<VER_IspezioneVisitaInfo> VER_IspezioneVisitaInfo { get; set; }
    }
}
