//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_CodiciCatastaliSezioni
    {
        public SYS_CodiciCatastaliSezioni()
        {
            this.LIM_LibrettiImpiantiDatiCatastali = new HashSet<LIM_LibrettiImpiantiDatiCatastali>();
        }
    
        public int IDCodiceCatastaleSezione { get; set; }
        public int IDCodiceCatastale { get; set; }
        public string Sezione { get; set; }
        public string CodiceSezione { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<LIM_LibrettiImpiantiDatiCatastali> LIM_LibrettiImpiantiDatiCatastali { get; set; }
        public virtual SYS_CodiciCatastali SYS_CodiciCatastali { get; set; }
    }
}
