//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_CausaliRaccomandate
    {
        public SYS_CausaliRaccomandate()
        {
            this.VER_AccertamentoDocumento = new HashSet<VER_AccertamentoDocumento>();
        }
    
        public int IDCausale { get; set; }
        public string Causale { get; set; }
        public string DescrizioneCausale { get; set; }
        public string EsitoRaccomandata { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<VER_AccertamentoDocumento> VER_AccertamentoDocumento { get; set; }
    }
}
