//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TipologiaImpiantiVMC
    {
        public SYS_TipologiaImpiantiVMC()
        {
            this.LIM_LibrettiImpiantiImpiantiVMC = new HashSet<LIM_LibrettiImpiantiImpiantiVMC>();
        }
    
        public int IDTipologiaImpiantiVMC { get; set; }
        public string TipologiaImpianto { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<LIM_LibrettiImpiantiImpiantiVMC> LIM_LibrettiImpiantiImpiantiVMC { get; set; }
    }
}
