//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_FasceContributive
    {
        public int IDFasciaContributiva { get; set; }
        public int NumeroBollini { get; set; }
        public Nullable<decimal> CostoBollini { get; set; }
        public int IDTipologiaRCT { get; set; }
        public decimal PotenzaMassima { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual SYS_TipologiaRapportoDiControllo SYS_TipologiaRapportoDiControllo { get; set; }
    }
}
