//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_RCTCheckList
    {
        public SYS_RCTCheckList()
        {
            this.SYS_RCTTipologiaCheckList = new HashSet<SYS_RCTTipologiaCheckList>();
            this.RCT_RapportoDiControlloTecnicoBaseCheckList = new HashSet<RCT_RapportoDiControlloTecnicoBaseCheckList>();
        }
    
        public int IDCheckList { get; set; }
        public string TestoCheckList { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<SYS_RCTTipologiaCheckList> SYS_RCTTipologiaCheckList { get; set; }
        public virtual ICollection<RCT_RapportoDiControlloTecnicoBaseCheckList> RCT_RapportoDiControlloTecnicoBaseCheckList { get; set; }
    }
}
