//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_StatoContratto
    {
        public SYS_StatoContratto()
        {
            this.COM_ContrattoIspettore = new HashSet<COM_ContrattoIspettore>();
        }
    
        public int IDStatoContratto { get; set; }
        public string StatoContratto { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<COM_ContrattoIspettore> COM_ContrattoIspettore { get; set; }
    }
}
