//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TipologiaRaccomandazionePrescrizioneRct
    {
        public SYS_TipologiaRaccomandazionePrescrizioneRct()
        {
            this.SYS_RCTTipologiaPrescrizione = new HashSet<SYS_RCTTipologiaPrescrizione>();
            this.SYS_RCTTipologiaRaccomandazione = new HashSet<SYS_RCTTipologiaRaccomandazione>();
        }
    
        public int IDTipologiaRaccomandazionePrescrizioneRct { get; set; }
        public string TipologiaRaccomandazionePrescrizioneRct { get; set; }
        public int IDTipologiaRCT { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<SYS_RCTTipologiaPrescrizione> SYS_RCTTipologiaPrescrizione { get; set; }
        public virtual ICollection<SYS_RCTTipologiaRaccomandazione> SYS_RCTTipologiaRaccomandazione { get; set; }
    }
}
