//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_UserRole
    {
        public SYS_UserRole()
        {
            this.SYS_UserAccess = new HashSet<SYS_UserAccess>();
            this.COM_Utenti = new HashSet<COM_Utenti>();
            this.COM_ReportsAccess = new HashSet<COM_ReportsAccess>();
        }
    
        public int IDRole { get; set; }
        public string Role { get; set; }
        public string Description { get; set; }
        public bool fActive { get; set; }
    
        public virtual ICollection<SYS_UserAccess> SYS_UserAccess { get; set; }
        public virtual ICollection<COM_Utenti> COM_Utenti { get; set; }
        public virtual ICollection<COM_ReportsAccess> COM_ReportsAccess { get; set; }
    }
}
