//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TipologiaFluidoTermoVettore
    {
        public SYS_TipologiaFluidoTermoVettore()
        {
            this.RCT_RapportoDiControlloTecnicoSC = new HashSet<RCT_RapportoDiControlloTecnicoSC>();
            this.RCT_RapportoDiControlloTecnicoSC1 = new HashSet<RCT_RapportoDiControlloTecnicoSC>();
            this.RCT_RapportoDiControlloTecnicoCG = new HashSet<RCT_RapportoDiControlloTecnicoCG>();
            this.LIM_LibrettiImpiantiGruppiTermici = new HashSet<LIM_LibrettiImpiantiGruppiTermici>();
            this.RCT_RapportoDiControlloTecnicoBase = new HashSet<RCT_RapportoDiControlloTecnicoBase>();
        }
    
        public int IDTipologiaFluidoTermoVettore { get; set; }
        public string TipologiaFluidoTermoVettore { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<RCT_RapportoDiControlloTecnicoSC> RCT_RapportoDiControlloTecnicoSC { get; set; }
        public virtual ICollection<RCT_RapportoDiControlloTecnicoSC> RCT_RapportoDiControlloTecnicoSC1 { get; set; }
        public virtual ICollection<RCT_RapportoDiControlloTecnicoCG> RCT_RapportoDiControlloTecnicoCG { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiGruppiTermici> LIM_LibrettiImpiantiGruppiTermici { get; set; }
        public virtual ICollection<RCT_RapportoDiControlloTecnicoBase> RCT_RapportoDiControlloTecnicoBase { get; set; }
    }
}
