//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_DestinazioneUso
    {
        public SYS_DestinazioneUso()
        {
            this.LIM_LibrettiImpianti = new HashSet<LIM_LibrettiImpianti>();
        }
    
        public int IDDestinazioneUso { get; set; }
        public string DestinazioneUso { get; set; }
        public string CodiceDestinazioneUso { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<LIM_LibrettiImpianti> LIM_LibrettiImpianti { get; set; }
    }
}
