//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TitoliSoggetti
    {
        public SYS_TitoliSoggetti()
        {
            this.COM_AnagraficaSoggetti = new HashSet<COM_AnagraficaSoggetti>();
        }
    
        public int IDTitoloSoggetto { get; set; }
        public string TitoloSoggetto { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<COM_AnagraficaSoggetti> COM_AnagraficaSoggetti { get; set; }
    }
}
