//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Regioni
    {
        public SYS_Regioni()
        {
            this.SYS_Province = new HashSet<SYS_Province>();
        }
    
        public int IDRegione { get; set; }
        public string Regione { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<SYS_Province> SYS_Province { get; set; }
    }
}
