//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TipologiaCondizionamentoChimico
    {
        public SYS_TipologiaCondizionamentoChimico()
        {
            this.LIM_LibrettiImpiantiCondizionamentoChimico = new HashSet<LIM_LibrettiImpiantiCondizionamentoChimico>();
        }
    
        public int IDTipologiaCondizionamentoChimico { get; set; }
        public string TipologiaCondizionamentoChimico { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<LIM_LibrettiImpiantiCondizionamentoChimico> LIM_LibrettiImpiantiCondizionamentoChimico { get; set; }
    }
}
