//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_AbilitazioneSoggetto
    {
        public SYS_AbilitazioneSoggetto()
        {
            this.COM_AbilitazioniSoggetto = new HashSet<COM_AbilitazioniSoggetto>();
        }
    
        public int IDAbilitazioneSoggetto { get; set; }
        public string AbilitazioneSoggetto { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<COM_AbilitazioniSoggetto> COM_AbilitazioniSoggetto { get; set; }
    }
}
