//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_UnitaMisura
    {
        public SYS_UnitaMisura()
        {
            this.LIM_LibrettiImpiantiConsumoCombustibile = new HashSet<LIM_LibrettiImpiantiConsumoCombustibile>();
            this.LIM_LibrettiImpiantiConsumoAcqua = new HashSet<LIM_LibrettiImpiantiConsumoAcqua>();
            this.LIM_LibrettiImpiantiConsumoProdottiChimici = new HashSet<LIM_LibrettiImpiantiConsumoProdottiChimici>();
        }
    
        public int IDUnitaMisura { get; set; }
        public string UnitaMisura { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<LIM_LibrettiImpiantiConsumoCombustibile> LIM_LibrettiImpiantiConsumoCombustibile { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiConsumoAcqua> LIM_LibrettiImpiantiConsumoAcqua { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiConsumoProdottiChimici> LIM_LibrettiImpiantiConsumoProdottiChimici { get; set; }
    }
}
