//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_StatoAccertamentoSanzione
    {
        public SYS_StatoAccertamentoSanzione()
        {
            this.VER_Accertamento = new HashSet<VER_Accertamento>();
        }
    
        public int IDStatoAccertamentoSanzione { get; set; }
        public string StatoAccertamentoSanzione { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<VER_Accertamento> VER_Accertamento { get; set; }
    }
}
