//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TipologiaDistributoriCombustibile
    {
        public SYS_TipologiaDistributoriCombustibile()
        {
            this.COM_TipiDistributoriCombustibile = new HashSet<COM_TipiDistributoriCombustibile>();
        }
    
        public int IDTipologiaDistributoriCombustibile { get; set; }
        public string TipologiaDistributoriCombustibile { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<COM_TipiDistributoriCombustibile> COM_TipiDistributoriCombustibile { get; set; }
    }
}
