//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_StatoQuestionario
    {
        public SYS_StatoQuestionario()
        {
            this.COM_Questionari = new HashSet<COM_Questionari>();
        }
    
        public int IDStatoQuestionario { get; set; }
        public string StatoQuestionario { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<COM_Questionari> COM_Questionari { get; set; }
    }
}
