//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_RuoloSoggetto
    {
        public SYS_RuoloSoggetto()
        {
            this.COM_RuoliSoggetti = new HashSet<COM_RuoliSoggetti>();
        }
    
        public int IDRuoloSoggetto { get; set; }
        public string RuoloSoggetto { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<COM_RuoliSoggetti> COM_RuoliSoggetti { get; set; }
    }
}
