//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_ModalitaInstallazioneRecuperatoriCalore
    {
        public SYS_ModalitaInstallazioneRecuperatoriCalore()
        {
            this.LIM_LibrettiImpiantiRecuperatoriCalore = new HashSet<LIM_LibrettiImpiantiRecuperatoriCalore>();
        }
    
        public int IDModalitaInstallazioneRecuperatoriCalore { get; set; }
        public string ModalitaInstallazione { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<LIM_LibrettiImpiantiRecuperatoriCalore> LIM_LibrettiImpiantiRecuperatoriCalore { get; set; }
    }
}
