//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_RCTTipologiaPrescrizione
    {
        public SYS_RCTTipologiaPrescrizione()
        {
            this.RCT_RaccomandazioniPrescrizioni = new HashSet<RCT_RaccomandazioniPrescrizioni>();
        }
    
        public int IDTipologiaPrescrizione { get; set; }
        public string Prescrizione { get; set; }
        public int IDTipologiaRaccomandazionePrescrizioneRct { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual SYS_TipologiaRaccomandazionePrescrizioneRct SYS_TipologiaRaccomandazionePrescrizioneRct { get; set; }
        public virtual ICollection<RCT_RaccomandazioniPrescrizioni> RCT_RaccomandazioniPrescrizioni { get; set; }
    }
}
