//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TipologiaGruppiTermici
    {
        public SYS_TipologiaGruppiTermici()
        {
            this.RCT_RapportoDiControlloTecnicoGT = new HashSet<RCT_RapportoDiControlloTecnicoGT>();
            this.LIM_LibrettiImpiantiGruppiTermici = new HashSet<LIM_LibrettiImpiantiGruppiTermici>();
            this.VER_RegoleControlli = new HashSet<VER_RegoleControlli>();
        }
    
        public int IDTipologiaGruppiTermici { get; set; }
        public string TipologiaGruppiTermici { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<RCT_RapportoDiControlloTecnicoGT> RCT_RapportoDiControlloTecnicoGT { get; set; }
        public virtual ICollection<LIM_LibrettiImpiantiGruppiTermici> LIM_LibrettiImpiantiGruppiTermici { get; set; }
        public virtual ICollection<VER_RegoleControlli> VER_RegoleControlli { get; set; }
    }
}
