//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TipologiaFluidoVettore
    {
        public SYS_TipologiaFluidoVettore()
        {
            this.LIM_LibrettiImpiantiTipologiaFluidoVettore = new HashSet<LIM_LibrettiImpiantiTipologiaFluidoVettore>();
        }
    
        public int IDTipologiaFluidoVettore { get; set; }
        public string TipologiaFluidoVettore { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<LIM_LibrettiImpiantiTipologiaFluidoVettore> LIM_LibrettiImpiantiTipologiaFluidoVettore { get; set; }
    }
}
