//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTE_DatiCatastali
    {
        public long Id { get; set; }
        public long IdDatiFornituraCliente { get; set; }
        public string Sezione { get; set; }
        public string Foglio { get; set; }
        public string Mappale { get; set; }
        public string Subalterno { get; set; }
    
        public virtual UTE_DatiFornituraCliente UTE_DatiFornituraCliente { get; set; }
    }
}
