//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_COM_Raccomandate
    {
        public string IDRichiesta { get; set; }
        public System.DateTime CreatoIl { get; set; }
        public string CreatoDa { get; set; }
        public Nullable<System.DateTime> ModificatoIl { get; set; }
        public string ModificatoDa { get; set; }
        public Nullable<long> IDAccertamento { get; set; }
        public Nullable<long> IDAccertamentoDocumento { get; set; }
        public Nullable<long> IDIspezione { get; set; }
        public int IDRaccomandataType { get; set; }
        public string RaccomandataType { get; set; }
        public string CodiceAccertamento { get; set; }
        public string CodiceIspezione { get; set; }
        public string ProceduraAccertamento { get; set; }
        public int Passaggio { get; set; }
        public string RisultatoTipo { get; set; }
        public string RisultatoCodice { get; set; }
        public string RisultatoDescrizione { get; set; }
        public string CodiceStatoRaccomandata { get; set; }
        public string DescrizioneStatoRaccomandata { get; set; }
        public Nullable<System.DateTime> DataStatoRaccomandata { get; set; }
        public bool fRaccomandataRecapitata { get; set; }
        public Nullable<int> IDTipoAccertamento { get; set; }
        public Nullable<long> IDIspezioneVisita { get; set; }
        public string NumeroRaccomandata { get; set; }
        public Nullable<bool> fEsitoDepositoRaccomandata { get; set; }
        public string EsitoDescrizioneDepositoRaccomandata { get; set; }
        public string Note { get; set; }
        public string ServiceType { get; set; }
    }
}
