//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_COM_Utenti
    {
        public int IDUtente { get; set; }
        public int IDSoggetto { get; set; }
        public int IDRuolo { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DataUltimaModificaPassword { get; set; }
        public Nullable<System.DateTime> DataScadenzaPassword { get; set; }
        public string Ruolo { get; set; }
        public bool fattivoUser { get; set; }
        public bool fattivoRole { get; set; }
        public string Utente { get; set; }
        public bool fVerificaCredenziali { get; set; }
        public string CodiceVerificaCredenziali { get; set; }
        public string CodiceFiscale { get; set; }
        public string CodiceSoggetto { get; set; }
        public string PartitaIVA { get; set; }
        public bool fSpid { get; set; }
        public Nullable<System.DateTime> DataUltimoAccesso { get; set; }
        public Nullable<System.DateTime> DataPrimoLogonFallito { get; set; }
        public int NrTentativiFalliti { get; set; }
        public bool fBloccato { get; set; }
        public string Salt { get; set; }
        public string KeyApi { get; set; }
        public string Email { get; set; }
    }
}
