//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_COM_AnagraficaSoggetti
    {
        public int IDSoggetto { get; set; }
        public string Soggetto { get; set; }
        public string CodiceSoggetto { get; set; }
        public Nullable<int> IDSoggettoDerived { get; set; }
        public string SoggettoDerived { get; set; }
        public Nullable<int> IDTipoSoggetto { get; set; }
        public string NomeAzienda { get; set; }
        public Nullable<int> IDFormaGiuridica { get; set; }
        public string FormaGiuridica { get; set; }
        public Nullable<int> IDFunzioneSoggetto { get; set; }
        public string FunzioneSoggetto { get; set; }
        public string IndirizzoSoggetto { get; set; }
        public Nullable<int> IDPaeseSedeLegale { get; set; }
        public string PaeseSedeLegale { get; set; }
        public string IndirizzoSedeLegale { get; set; }
        public string CapSedeLegale { get; set; }
        public string CittaSedeLegale { get; set; }
        public string RegioneSedeLegale { get; set; }
        public Nullable<int> IDProvinciaSedeLegale { get; set; }
        public string SiglaProvinciaSedeLegale { get; set; }
        public string ProvinciaSedeLegale { get; set; }
        public Nullable<int> IDTitoloSoggetto { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string EmailPec { get; set; }
        public string PartitaIVA { get; set; }
        public string CodiceFiscaleAzienda { get; set; }
        public string CodiceFiscale { get; set; }
        public string SitoWeb { get; set; }
        public string NumeroIscrizioneAlboImprese { get; set; }
        public Nullable<int> IDProvinciaIscrizioneAlboImprese { get; set; }
        public string SiglaProvinciaAlboImprese { get; set; }
        public string ProvinciaAlboImprese { get; set; }
        public Nullable<System.DateTime> DataIscrizione { get; set; }
        public bool fPubblicazioneAlbo { get; set; }
        public bool fPrivacy { get; set; }
        public Nullable<int> IDUtenteInserimento { get; set; }
        public Nullable<System.DateTime> DataInserimento { get; set; }
        public Nullable<int> IDUtenteUltimaModifica { get; set; }
        public Nullable<System.DateTime> DataUltimaModifica { get; set; }
        public bool fAttivo { get; set; }
        public string TipoSoggetto { get; set; }
        public string TipoSoggettoImage { get; set; }
        public string TitoloSoggetto { get; set; }
        public string UtenteInserimento { get; set; }
        public string UtenteUltimaModifica { get; set; }
        public string NumeroCivicoSedeLegale { get; set; }
        public bool fIscrizioneRegistroGasFluorurati { get; set; }
        public string NumeroIscrizioneRegistroGasFluorurati { get; set; }
        public System.Data.Entity.Spatial.DbGeography Coordinate { get; set; }
        public Nullable<int> IDPaeseNascita { get; set; }
        public string PaeseNascita { get; set; }
        public Nullable<System.DateTime> DataNascita { get; set; }
        public string CittaNascita { get; set; }
        public Nullable<int> IDProvinciaNascita { get; set; }
        public string ProvinciaNascita { get; set; }
        public string CittaResidenza { get; set; }
        public Nullable<int> IDProvinciaResidenza { get; set; }
        public string ProvinciaResidenza { get; set; }
        public string CapResidenza { get; set; }
        public string IndirizzoResidenza { get; set; }
        public string NumeroCivicoResidenza { get; set; }
        public bool fIscrizione { get; set; }
        public Nullable<int> TipoFirma { get; set; }
        public Nullable<System.DateTime> DataFirma { get; set; }
        public string IPClient { get; set; }
        public string SignerQualifier { get; set; }
        public string SignerName { get; set; }
        public string SignerSurname { get; set; }
        public string SignerIdentifier { get; set; }
        public string SignerFullName { get; set; }
        public string SignerAuthority { get; set; }
        public string SignerCertificationAuthority { get; set; }
        public string SignerSerialNumber { get; set; }
        public bool fDomicilioUgualeResidenza { get; set; }
        public string CittaDomicilio { get; set; }
        public Nullable<int> IDProvinciaDomicilio { get; set; }
        public string ProvinciaDomicilio { get; set; }
        public string CapDomicilio { get; set; }
        public string IndirizzoDomicilio { get; set; }
        public string NumeroCivicoDomicilio { get; set; }
        public string Cellulare { get; set; }
        public string TelefonoOrganizzazione { get; set; }
        public string EmailOrganizzazione { get; set; }
        public string EmailPecOrganizzazione { get; set; }
        public string PartitaIVAOrganizzazione { get; set; }
        public Nullable<int> IDTipologiaQualificaIspettore { get; set; }
        public string TipologiaQualificaIspettore { get; set; }
        public bool fIdoneoIspezione { get; set; }
        public bool fCondanna { get; set; }
        public Nullable<int> IDTipologiaTitoloStudio { get; set; }
        public string TipologiaTitoloStudio { get; set; }
        public string TitoloStudioConseguitoPresso { get; set; }
        public Nullable<System.DateTime> DataTitoloStudio { get; set; }
        public string StageAzienda { get; set; }
        public Nullable<System.DateTime> DataStageAziendaDal { get; set; }
        public Nullable<System.DateTime> DataStageAziendaAl { get; set; }
        public string CorsoFormazione { get; set; }
        public string CorsoFormazioneOrganizzatore { get; set; }
        public bool fRequisitoOrganizzativo { get; set; }
        public bool fDisponibilitaApparecchiature { get; set; }
        public bool fDisponibilitaControlli { get; set; }
        public bool fOrganizzazioneEsterna { get; set; }
        public bool fConsensoRequisitiDichiarati { get; set; }
        public string OrganismoIspezioneNumero { get; set; }
        public string OrganismoIspezione { get; set; }
        public Nullable<int> IDPaeseResidenza { get; set; }
        public string PaeseResidenza { get; set; }
        public Nullable<int> IDPaeseDomicilio { get; set; }
        public string PaeseDomicilio { get; set; }
        public Nullable<int> IDTipologiaOrdineCollegio { get; set; }
        public string TipologiaOrdineCollegio { get; set; }
        public Nullable<int> IDProvinciaOrdineCollegio { get; set; }
        public string ProvinciaOrdineCollegio { get; set; }
        public string SezioneOrdineCollegio { get; set; }
        public string NumeroOrdineCollegio { get; set; }
        public Nullable<System.DateTime> DataOrdineCollegio { get; set; }
        public Nullable<int> IDStatoAccreditamento { get; set; }
        public Nullable<System.DateTime> DataAccreditamento { get; set; }
        public Nullable<System.DateTime> DataRinnovo { get; set; }
        public Nullable<System.DateTime> DataAnnullamento { get; set; }
        public string MotivazioneAnnullamento { get; set; }
        public Nullable<System.DateTime> DataSospensioneDa { get; set; }
        public Nullable<System.DateTime> DataSospensioneA { get; set; }
        public string MotivazioneSospensione { get; set; }
        public string StatoAccreditamento { get; set; }
        public string ImageUrlStatoAccreditamento { get; set; }
        public Nullable<bool> fAttivoAccreditamento { get; set; }
        public bool fPrivacyNew { get; set; }
    }
}
