//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_COM_ContrattoIspettore
    {
        public int IDContrattoIspettore { get; set; }
        public int IDIspettore { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public int IDStatoContratto { get; set; }
        public int NumeroIspezioniMax { get; set; }
        public System.DateTime DataInizioContratto { get; set; }
        public System.DateTime DataFineContratto { get; set; }
        public bool fAttivo { get; set; }
        public string StatoContratto { get; set; }
        public byte[] Firma { get; set; }
    }
}
