//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_COM_Questionari
    {
        public long IDRapportoControlloTecnico { get; set; }
        public int IDSoggettoAzienda { get; set; }
        public string SoggettoAzienda { get; set; }
        public int IDTargaturaImpianto { get; set; }
        public string Indirizzo { get; set; }
        public string Civico { get; set; }
        public string Palazzo { get; set; }
        public string Scala { get; set; }
        public string Interno { get; set; }
        public Nullable<int> IDCodiceCatastale { get; set; }
        public string CodiceSoggettoManutentore { get; set; }
        public int IDTipologiaRCT { get; set; }
        public int IDLibrettoImpianto { get; set; }
        public int IDStatoRapportoDiControllo { get; set; }
        public int IDTipologiaControllo { get; set; }
        public Nullable<int> IDTipologiaResponsabile { get; set; }
        public string NomeResponsabile { get; set; }
        public string CognomeResponsabile { get; set; }
        public string CodiceFiscaleResponsabile { get; set; }
        public string RagioneSocialeResponsabile { get; set; }
        public string PartitaIVAResponsabile { get; set; }
        public string DescrizioneRCT { get; set; }
        public string TipologiaControllo { get; set; }
        public Nullable<decimal> PotenzaTermicaNominale { get; set; }
        public Nullable<System.DateTime> DataControllo { get; set; }
        public string Prefisso { get; set; }
        public int CodiceProgressivo { get; set; }
        public string CodiceTargatura { get; set; }
        public Nullable<int> NumeroRevisione { get; set; }
        public string Osservazioni { get; set; }
        public string Raccomandazioni { get; set; }
        public string Prescrizioni { get; set; }
        public bool fImpiantoFunzionante { get; set; }
        public Nullable<int> IDUtenteQuestionario { get; set; }
        public Nullable<int> IDStatoQuestionario { get; set; }
        public string StatoQuestionario { get; set; }
        public Nullable<bool> fTerzoResponsabile { get; set; }
        public Nullable<int> IDQuestionario { get; set; }
        public string IndirizzoResponsabile { get; set; }
        public string CivicoResponsabile { get; set; }
        public string ComuneResponsabile { get; set; }
        public string RagioneSocialeTerzoResponsabile { get; set; }
        public string PartitaIVATerzoResponsabile { get; set; }
        public string IndirizzoTerzoResponsabile { get; set; }
        public string CivicoTerzoResponsabile { get; set; }
        public string ComuneTerzoResponsabile { get; set; }
    }
}
