//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LIM_VerifichePeriodicheGF
    {
        public Nullable<long> RowNum { get; set; }
        public long Id { get; set; }
        public int IDLibrettoImpianto { get; set; }
        public int IDTargaturaImpianto { get; set; }
        public int IDSoggetto { get; set; }
        public Nullable<int> IDSoggettoDerived { get; set; }
        public int IDTipologiaControllo { get; set; }
        public int IDStatoRapportoDiControllo { get; set; }
        public Nullable<System.DateTime> DataControllo { get; set; }
        public Nullable<decimal> NCircuiti { get; set; }
        public Nullable<int> AssenzaPerditeRefrigerante { get; set; }
        public bool ProvaRaffrescamento { get; set; }
        public bool ProvaRiscaldamento { get; set; }
        public Nullable<decimal> TemperaturaSurriscaldamento { get; set; }
        public Nullable<decimal> TemperaturaSottoraffreddamento { get; set; }
        public Nullable<decimal> TemperaturaCondensazione { get; set; }
        public Nullable<decimal> TemperaturaEvaporazione { get; set; }
        public Nullable<decimal> TInglatoEst { get; set; }
        public Nullable<decimal> TUscLatoEst { get; set; }
        public Nullable<decimal> TIngLatoUtenze { get; set; }
        public Nullable<decimal> TUscLatoUtenze { get; set; }
        public Nullable<decimal> TUscitaFluido { get; set; }
        public Nullable<decimal> TBulboUmidoAria { get; set; }
        public Nullable<decimal> TIngressoLatoEsterno { get; set; }
        public Nullable<decimal> TUscitaLatoEsterno { get; set; }
        public Nullable<decimal> TIngressoLatoMacchina { get; set; }
        public Nullable<decimal> TUscitaLatoMacchina { get; set; }
        public Nullable<decimal> PotenzaAssorbita { get; set; }
        public Nullable<int> FiltriPuliti { get; set; }
        public Nullable<int> IdLIM_LibrettiImpiantiMacchineFrigorifere { get; set; }
        public string Prefisso { get; set; }
        public int CodiceProgressivo { get; set; }
    }
}
