//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LIM_TargatureImpianti
    {
        public int IDTargaturaImpianto { get; set; }
        public Nullable<int> IDLibrettoImpianto { get; set; }
        public Nullable<int> IDSoggettoDerived { get; set; }
        public int IDSoggetto { get; set; }
        public string CodiceLotto { get; set; }
        public string DescrizioneLotto { get; set; }
        public string CodiceTargatura { get; set; }
        public int CodiceRandom { get; set; }
        public int Anno { get; set; }
        public Nullable<int> IDUtenteInserimento { get; set; }
        public Nullable<System.DateTime> DataInserimento { get; set; }
        public Nullable<int> IDUtenteUltimaModifica { get; set; }
        public Nullable<System.DateTime> DataUltimaModifica { get; set; }
        public Nullable<bool> fAttivoLibretto { get; set; }
        public string Soggetto { get; set; }
        public string IndirizzoSoggetto { get; set; }
        public string SoggettoManutentore { get; set; }
    }
}
