//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LIM_LibrettiImpianti
    {
        public int IDLibrettoImpianto { get; set; }
        public Nullable<int> IDSoggettoManutentore { get; set; }
        public int IDSoggettoAzienda { get; set; }
        public string SoggettoManutentore { get; set; }
        public string SoggettoAzienda { get; set; }
        public Nullable<int> IDTargaturaImpianto { get; set; }
        public int IDStatoLibrettoImpianto { get; set; }
        public Nullable<int> IDTipologiaIntervento { get; set; }
        public Nullable<System.DateTime> DataIntervento { get; set; }
        public string Indirizzo { get; set; }
        public string Civico { get; set; }
        public string Palazzo { get; set; }
        public string Scala { get; set; }
        public string Interno { get; set; }
        public Nullable<int> IDCodiceCatastale { get; set; }
        public bool fUnitaImmobiliare { get; set; }
        public Nullable<int> IDDestinazioneUso { get; set; }
        public Nullable<decimal> VolumeLordoRiscaldato { get; set; }
        public Nullable<decimal> VolumeLordoRaffrescato { get; set; }
        public string NumeroAPE { get; set; }
        public string NumeroPDR { get; set; }
        public string NumeroPOD { get; set; }
        public bool fAcs { get; set; }
        public Nullable<decimal> PotenzaAcs { get; set; }
        public bool fClimatizzazioneEstiva { get; set; }
        public Nullable<decimal> PotenzaClimatizzazioneEstiva { get; set; }
        public bool fClimatizzazioneInvernale { get; set; }
        public Nullable<decimal> PotenzaClimatizzazioneInvernale { get; set; }
        public bool fClimatizzazioneAltro { get; set; }
        public string ClimatizzazioneAltro { get; set; }
        public bool fPannelliSolariTermici { get; set; }
        public Nullable<decimal> SuperficieTotaleSolariTermici { get; set; }
        public Nullable<decimal> PotenzaSolariTermici { get; set; }
        public bool fPannelliSolariTermiciAltro { get; set; }
        public string PannelliSolariTermiciAltro { get; set; }
        public bool fPannelliSolariClimatizzazioneAcs { get; set; }
        public bool fPannelliSolariClimatizzazioneEstiva { get; set; }
        public bool fPannelliSolariClimatizzazioneInvernale { get; set; }
        public Nullable<decimal> ContenutoAcquaImpianto { get; set; }
        public Nullable<decimal> DurezzaTotaleAcquaImpianto { get; set; }
        public bool fTrattamentoAcquaInvernale { get; set; }
        public Nullable<decimal> DurezzaTotaleAcquaImpiantoInvernale { get; set; }
        public Nullable<int> IDTipologiaProtezioneGelo { get; set; }
        public bool fTrattamentoAcquaAcs { get; set; }
        public Nullable<decimal> DurezzaTotaleAcquaAcs { get; set; }
        public Nullable<decimal> PercentualeGlicole { get; set; }
        public Nullable<decimal> PhGlicole { get; set; }
        public bool fTrattamentoAcquaEstiva { get; set; }
        public Nullable<int> IDTipologiaCircuitoRaffreddamento { get; set; }
        public Nullable<int> IDTipologiaAcquaAlimento { get; set; }
        public bool fSistemaSpurgoAutomatico { get; set; }
        public Nullable<decimal> ConducibilitaAcquaIngresso { get; set; }
        public Nullable<decimal> ConducibilitaInizioSpurgo { get; set; }
        public Nullable<int> IDUtenteInserimento { get; set; }
        public Nullable<System.DateTime> DataInserimento { get; set; }
        public Nullable<int> IDUtenteUltimaModifica { get; set; }
        public Nullable<System.DateTime> DataUltimaModifica { get; set; }
        public Nullable<int> IDLibrettoImpiantoRevisione { get; set; }
        public Nullable<int> NumeroRevisione { get; set; }
        public Nullable<System.DateTime> DataRevisione { get; set; }
        public Nullable<System.DateTime> DataAnnullamento { get; set; }
        public bool fAttivo { get; set; }
        public string StatoLibrettoImpianto { get; set; }
        public string CodiceTargatura { get; set; }
        public string DestinazioneUso { get; set; }
        public string CodiceCatastale { get; set; }
        public string Provincia { get; set; }
        public string UtenteInserimento { get; set; }
        public string UtenteUltimaModifica { get; set; }
        public string CodiceSoggettoAzienda { get; set; }
        public string CodiceSoggettoManutentore { get; set; }
        public Nullable<int> IDTipologiaResponsabile { get; set; }
        public string NomeResponsabile { get; set; }
        public string CognomeResponsabile { get; set; }
        public string CodiceFiscaleResponsabile { get; set; }
        public string RagioneSocialeResponsabile { get; set; }
        public string PartitaIvaResponsabile { get; set; }
        public string JsonFormat { get; set; }
        public string KeyApi { get; set; }
        public System.Data.Entity.Spatial.DbGeography Coordinate { get; set; }
    }
}
