//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LIM_VerifichePeriodicheCG
    {
        public Nullable<long> RowNum { get; set; }
        public long Id { get; set; }
        public int IDLibrettoImpianto { get; set; }
        public int IDTargaturaImpianto { get; set; }
        public int IDSoggetto { get; set; }
        public Nullable<int> IDSoggettoDerived { get; set; }
        public int IDTipologiaControllo { get; set; }
        public int IDStatoRapportoDiControllo { get; set; }
        public Nullable<System.DateTime> DataControllo { get; set; }
        public Nullable<decimal> TemperaturaAriaComburente { get; set; }
        public Nullable<decimal> TemperaturaAcquauscita { get; set; }
        public Nullable<decimal> TemperaturaAcquaIngresso { get; set; }
        public Nullable<decimal> TemperaturaAcquaMotore { get; set; }
        public Nullable<decimal> TemperaturaFumiValle { get; set; }
        public Nullable<decimal> TemperaturaFumiMonte { get; set; }
        public Nullable<decimal> PotenzaAiMorsetti { get; set; }
        public Nullable<decimal> EmissioneMonossido { get; set; }
        public Nullable<decimal> SovrafrequenzaSogliaInterv1 { get; set; }
        public Nullable<decimal> SovrafrequenzaSogliaInterv2 { get; set; }
        public Nullable<decimal> SovrafrequenzaSogliaInterv3 { get; set; }
        public Nullable<decimal> SovrafrequenzaTempoInterv1 { get; set; }
        public Nullable<decimal> SovrafrequenzaTempoInterv2 { get; set; }
        public Nullable<decimal> SovrafrequenzaTempoInterv3 { get; set; }
        public Nullable<decimal> SottofrequenzaSogliaInterv1 { get; set; }
        public Nullable<decimal> SottofrequenzaSogliaInterv2 { get; set; }
        public Nullable<decimal> SottofrequenzaSogliaInterv3 { get; set; }
        public Nullable<decimal> SottofrequenzaTempoInterv1 { get; set; }
        public Nullable<decimal> SottofrequenzaTempoInterv2 { get; set; }
        public Nullable<decimal> SottofrequenzaTempoInterv3 { get; set; }
        public Nullable<decimal> SovratensioneSogliaInterv1 { get; set; }
        public Nullable<decimal> SovratensioneSogliaInterv2 { get; set; }
        public Nullable<decimal> SovratensioneSogliaInterv3 { get; set; }
        public Nullable<decimal> SovratensioneTempoInterv1 { get; set; }
        public Nullable<decimal> SovratensioneTempoInterv2 { get; set; }
        public Nullable<decimal> SovratensioneTempoInterv3 { get; set; }
        public Nullable<decimal> SottotensioneSogliaInterv1 { get; set; }
        public Nullable<decimal> SottotensioneSogliaInterv2 { get; set; }
        public Nullable<decimal> SottotensioneSogliaInterv3 { get; set; }
        public Nullable<decimal> SottotensioneTempoInterv1 { get; set; }
        public Nullable<decimal> SottotensioneTempoInterv2 { get; set; }
        public Nullable<decimal> SottotensioneTempoInterv3 { get; set; }
        public Nullable<int> IdLIM_LibrettiImpiantiCogeneratori { get; set; }
        public string Prefisso { get; set; }
        public int CodiceProgressivo { get; set; }
    }
}
