//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MNU_Menu
    {
        public int IDMenu { get; set; }
        public string Menu { get; set; }
        public string PageUrl { get; set; }
        public int Ordine { get; set; }
        public Nullable<int> IDMenuParent { get; set; }
        public bool fattivoMenu { get; set; }
        public Nullable<int> IDUtente { get; set; }
        public Nullable<int> IDSoggetto { get; set; }
        public Nullable<int> IDRuolo { get; set; }
        public Nullable<bool> fattivoUtente { get; set; }
        public Nullable<bool> fattivoRuolo { get; set; }
        public Nullable<bool> fattivoAccessoUtente { get; set; }
        public bool fPrivate { get; set; }
        public bool fTile { get; set; }
        public string TileCssClassColor { get; set; }
        public string TileImage { get; set; }
        public Nullable<int> TileOrdine { get; set; }
        public string TileCssClassDimension { get; set; }
    }
}
