//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RCT_RapportoDiControlloTecnicoGT
    {
        public long IDRapportoControlloTecnico { get; set; }
        public int IDSoggetto { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public Nullable<int> IDSoggettoDerived { get; set; }
        public int IDTargaturaImpianto { get; set; }
        public Nullable<decimal> PotenzaTermicaNominale { get; set; }
        public string Indirizzo { get; set; }
        public string Civico { get; set; }
        public string Palazzo { get; set; }
        public string Scala { get; set; }
        public string Interno { get; set; }
        public Nullable<int> IDCodiceCatastale { get; set; }
        public int IDTipologiaRCT { get; set; }
        public int IDLibrettoImpianto { get; set; }
        public int IDStatoRapportoDiControllo { get; set; }
        public int IDTipologiaControllo { get; set; }
        public Nullable<int> IDTipologiaResponsabile { get; set; }
        public string NomeResponsabile { get; set; }
        public string CognomeResponsabile { get; set; }
        public string CodiceFiscaleResponsabile { get; set; }
        public string RagioneSocialeResponsabile { get; set; }
        public string PartitaIVAResponsabile { get; set; }
        public string IndirizzoResponsabile { get; set; }
        public string CivicoResponsabile { get; set; }
        public string ComuneResponsabile { get; set; }
        public Nullable<int> IDProvinciaResponsabile { get; set; }
        public string ProvinciaResponsabile { get; set; }
        public string RagioneSocialeTerzoResponsabile { get; set; }
        public string PartitaIVATerzoResponsabile { get; set; }
        public string IndirizzoTerzoResponsabile { get; set; }
        public string CivicoTerzoResponsabile { get; set; }
        public string ComuneTerzoResponsabile { get; set; }
        public Nullable<int> IDProvinciaTerzoResponsabile { get; set; }
        public string ProvinciaTerzoResponsabile { get; set; }
        public string RagioneSocialeImpresaManutentrice { get; set; }
        public string PartitaIVAImpresaManutentrice { get; set; }
        public string IndirizzoImpresaManutentrice { get; set; }
        public string CivicoImpresaManutentrice { get; set; }
        public string ComuneImpresaManutentrice { get; set; }
        public Nullable<int> IDProvinciaImpresaManutentrice { get; set; }
        public string ProvinciaImpresaManutentrice { get; set; }
        public Nullable<int> LocaleInstallazioneIdoneo { get; set; }
        public Nullable<decimal> PotenzaTermicaNominaleTotaleMax { get; set; }
        public bool fDichiarazioneConformita { get; set; }
        public bool fLibrettoImpiantoPresente { get; set; }
        public bool fUsoManutenzioneGeneratore { get; set; }
        public bool fLibrettoImpiantoCompilato { get; set; }
        public Nullable<decimal> DurezzaAcqua { get; set; }
        public Nullable<int> TrattamentoACS { get; set; }
        public Nullable<int> TrattamentoRiscaldamento { get; set; }
        public Nullable<int> ApertureLibere { get; set; }
        public Nullable<int> DimensioniApertureAdeguate { get; set; }
        public Nullable<int> LineeElettricheIdonee { get; set; }
        public Nullable<int> CoibentazioniIdonee { get; set; }
        public Nullable<int> AssenzaPerditeCombustibile { get; set; }
        public Nullable<int> TenutaImpiantoIdraulico { get; set; }
        public Nullable<int> ScarichiIdonei { get; set; }
        public string Prefisso { get; set; }
        public int CodiceProgressivo { get; set; }
        public Nullable<System.DateTime> DataInstallazione { get; set; }
        public string Fabbricante { get; set; }
        public string Modello { get; set; }
        public string Matricola { get; set; }
        public bool fClimatizzazioneInvernale { get; set; }
        public bool fProduzioneACS { get; set; }
        public bool fClimatizzazioneEstiva { get; set; }
        public Nullable<int> IDTipologiaCombustibile { get; set; }
        public string AltroCombustibile { get; set; }
        public Nullable<int> IDTipologiaFluidoTermoVettore { get; set; }
        public string Osservazioni { get; set; }
        public string Raccomandazioni { get; set; }
        public string Prescrizioni { get; set; }
        public bool fImpiantoFunzionante { get; set; }
        public Nullable<System.DateTime> DataManutenzioneConsigliata { get; set; }
        public Nullable<System.DateTime> DataControllo { get; set; }
        public Nullable<System.DateTime> OraArrivo { get; set; }
        public Nullable<System.DateTime> OraPartenza { get; set; }
        public Nullable<decimal> TemperaturaFumi { get; set; }
        public Nullable<int> RegolazioneTemperaturaAmbiente { get; set; }
        public bool EvacuazioneForzata { get; set; }
        public bool EvacuazioneNaturale { get; set; }
        public Nullable<decimal> DepressioneCanaleFumo { get; set; }
        public Nullable<decimal> TemperaraturaComburente { get; set; }
        public Nullable<decimal> O2 { get; set; }
        public Nullable<decimal> Co2 { get; set; }
        public Nullable<decimal> RendimentoCombustione { get; set; }
        public Nullable<decimal> RendimentoMinimo { get; set; }
        public Nullable<int> DispositiviComandoRegolazione { get; set; }
        public Nullable<int> DispositiviSicurezza { get; set; }
        public Nullable<int> ValvolaSicurezzaSovrappressione { get; set; }
        public Nullable<int> ScambiatoreFumiPulito { get; set; }
        public Nullable<int> RiflussoProdottiCombustione { get; set; }
        public Nullable<int> ConformitaUNI10389 { get; set; }
        public Nullable<int> IdTipologiaGruppiTermici { get; set; }
        public Nullable<decimal> bacharach1 { get; set; }
        public Nullable<decimal> bacharach2 { get; set; }
        public Nullable<decimal> bacharach3 { get; set; }
        public Nullable<decimal> CoCorretto { get; set; }
        public string ModuloTermico { get; set; }
        public Nullable<decimal> PotenzaTermicaNominaleFocolare { get; set; }
        public Nullable<int> IDLIM_LibrettiImpiantiGruppitermici { get; set; }
        public Nullable<decimal> COFumiSecchi { get; set; }
        public Nullable<decimal> PortataCombustibile { get; set; }
        public bool RispettaIndiceBacharach { get; set; }
        public bool COFumiSecchiNoAria1000 { get; set; }
        public bool RendimentoSupMinimo { get; set; }
        public Nullable<int> IdTipologiaGeneratoriTermici { get; set; }
        public Nullable<decimal> PotenzaTermicaEffettiva { get; set; }
        public string DescrizioneRCT { get; set; }
        public string StatoRapportoDiControllo { get; set; }
        public string TipologiaResponsabile { get; set; }
        public string CodiceCatastale { get; set; }
        public string CodiceTargatura { get; set; }
        public Nullable<int> GeneratoriIdonei { get; set; }
        public string TipologiaGruppiTermici { get; set; }
        public string TipologiaCombustibile { get; set; }
        public Nullable<int> StatoCoibentazioniIdonee { get; set; }
        public Nullable<int> IDTipoSoggetto { get; set; }
        public Nullable<int> IDTipologiaSistemaDistribuzione { get; set; }
        public string AltroTipologiaSistemaDistribuzione { get; set; }
        public Nullable<int> Contabilizzazione { get; set; }
        public Nullable<int> IDTipologiaContabilizzazione { get; set; }
        public Nullable<int> Termoregolazione { get; set; }
        public Nullable<int> CorrettoFunzionamentoContabilizzazione { get; set; }
        public string TipologiaSistemaDistribuzione { get; set; }
        public string TipologiaContabilizzazione { get; set; }
        public string JsonFormat { get; set; }
        public string Provincia { get; set; }
        public string GuidRapportoTecnico { get; set; }
        public string guidInteroImpianto { get; set; }
    }
}
