//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RCT_RapportoDiControlloTecnicoGF
    {
        public long IDRapportoControlloTecnico { get; set; }
        public int IDSoggetto { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public Nullable<int> IDSoggettoDerived { get; set; }
        public int IDTargaturaImpianto { get; set; }
        public Nullable<decimal> PotenzaTermicaNominale { get; set; }
        public string Indirizzo { get; set; }
        public string Civico { get; set; }
        public string Palazzo { get; set; }
        public string Scala { get; set; }
        public string Interno { get; set; }
        public Nullable<int> IDCodiceCatastale { get; set; }
        public int IDTipologiaRCT { get; set; }
        public int IDLibrettoImpianto { get; set; }
        public int IDStatoRapportoDiControllo { get; set; }
        public int IDTipologiaControllo { get; set; }
        public Nullable<int> IDTipologiaResponsabile { get; set; }
        public string NomeResponsabile { get; set; }
        public string CognomeResponsabile { get; set; }
        public string CodiceFiscaleResponsabile { get; set; }
        public string RagioneSocialeResponsabile { get; set; }
        public string PartitaIVAResponsabile { get; set; }
        public string IndirizzoResponsabile { get; set; }
        public string CivicoResponsabile { get; set; }
        public string ComuneResponsabile { get; set; }
        public Nullable<int> IDProvinciaResponsabile { get; set; }
        public string ProvinciaResponsabile { get; set; }
        public string RagioneSocialeTerzoResponsabile { get; set; }
        public string PartitaIVATerzoResponsabile { get; set; }
        public string IndirizzoTerzoResponsabile { get; set; }
        public string CivicoTerzoResponsabile { get; set; }
        public string ComuneTerzoResponsabile { get; set; }
        public Nullable<int> IDProvinciaTerzoResponsabile { get; set; }
        public string ProvinciaTerzoResponsabile { get; set; }
        public string RagioneSocialeImpresaManutentrice { get; set; }
        public string PartitaIVAImpresaManutentrice { get; set; }
        public string IndirizzoImpresaManutentrice { get; set; }
        public string CivicoImpresaManutentrice { get; set; }
        public string ComuneImpresaManutentrice { get; set; }
        public Nullable<int> IDProvinciaImpresaManutentrice { get; set; }
        public string ProvinciaImpresaManutentrice { get; set; }
        public Nullable<int> LocaleInstallazioneIdoneo { get; set; }
        public Nullable<decimal> PotenzaTermicaNominaleTotaleMax { get; set; }
        public bool fDichiarazioneConformita { get; set; }
        public bool fLibrettoImpiantoPresente { get; set; }
        public bool fUsoManutenzioneGeneratore { get; set; }
        public bool fLibrettoImpiantoCompilato { get; set; }
        public Nullable<decimal> DurezzaAcqua { get; set; }
        public Nullable<int> TrattamentoACS { get; set; }
        public Nullable<int> TrattamentoRiscaldamento { get; set; }
        public Nullable<int> ApertureLibere { get; set; }
        public Nullable<int> DimensioniApertureAdeguate { get; set; }
        public Nullable<int> LineeElettricheIdonee { get; set; }
        public Nullable<int> CoibentazioniIdonee { get; set; }
        public Nullable<int> AssenzaPerditeCombustibile { get; set; }
        public Nullable<int> TenutaImpiantoIdraulico { get; set; }
        public Nullable<int> ScarichiIdonei { get; set; }
        public string Prefisso { get; set; }
        public int CodiceProgressivo { get; set; }
        public Nullable<System.DateTime> DataInstallazione { get; set; }
        public string Fabbricante { get; set; }
        public string Modello { get; set; }
        public string Matricola { get; set; }
        public bool fClimatizzazioneInvernale { get; set; }
        public bool fProduzioneACS { get; set; }
        public bool fClimatizzazioneEstiva { get; set; }
        public Nullable<int> IDTipologiaCombustibile { get; set; }
        public string AltroCombustibile { get; set; }
        public Nullable<int> IDTipologiaFluidoTermoVettore { get; set; }
        public string Osservazioni { get; set; }
        public string Raccomandazioni { get; set; }
        public string Prescrizioni { get; set; }
        public bool fImpiantoFunzionante { get; set; }
        public Nullable<System.DateTime> DataManutenzioneConsigliata { get; set; }
        public Nullable<System.DateTime> DataControllo { get; set; }
        public Nullable<System.DateTime> OraArrivo { get; set; }
        public Nullable<System.DateTime> OraPartenza { get; set; }
        public string DescrizioneRCT { get; set; }
        public string StatoRapportoDiControllo { get; set; }
        public string TipologiaResponsabile { get; set; }
        public string CodiceCatastale { get; set; }
        public string CodiceTargatura { get; set; }
        public Nullable<decimal> TemperaturaSurriscaldamento { get; set; }
        public Nullable<decimal> TemperaturaSottoraffreddamento { get; set; }
        public Nullable<decimal> TemperaturaCondensazione { get; set; }
        public Nullable<decimal> TemperaturaEvaporazione { get; set; }
        public Nullable<decimal> TInglatoEst { get; set; }
        public Nullable<decimal> TUscLatoEst { get; set; }
        public Nullable<decimal> TIngLatoUtenze { get; set; }
        public Nullable<decimal> TUscLatoUtenze { get; set; }
        public Nullable<int> AssenzaPerditeRefrigerante { get; set; }
        public Nullable<int> LeakDetector { get; set; }
        public Nullable<int> ParametriTermodinamici { get; set; }
        public Nullable<int> ScambiatoriLiberi { get; set; }
        public Nullable<decimal> Potenzafrigorifera { get; set; }
        public bool ProvaRaffrescamento { get; set; }
        public bool ProvaRiscaldamento { get; set; }
        public Nullable<int> IdLIM_LibrettiImpiantiMacchineFrigorifere { get; set; }
        public Nullable<int> IDTipologiemacchineFrigorifere { get; set; }
        public Nullable<decimal> NCircuiti { get; set; }
        public Nullable<int> FiltriPuliti { get; set; }
        public Nullable<decimal> PotenzaAssorbita { get; set; }
        public Nullable<decimal> TUscitaFluido { get; set; }
        public Nullable<decimal> TBulboUmidoAria { get; set; }
        public Nullable<decimal> TIngressoLatoEsterno { get; set; }
        public Nullable<decimal> TUscitaLatoEsterno { get; set; }
        public Nullable<decimal> TIngressoLatoMacchina { get; set; }
        public Nullable<decimal> TUscitaLatoMacchina { get; set; }
        public Nullable<decimal> NCircuitiTotali { get; set; }
        public string TipologiaMacchineFrigorifere { get; set; }
        public string TipologiaCombustibile { get; set; }
        public Nullable<int> StatoCoibentazioniIdonee { get; set; }
        public Nullable<int> IDTipoSoggetto { get; set; }
        public Nullable<int> IDTipologiaSistemaDistribuzione { get; set; }
        public string AltroTipologiaSistemaDistribuzione { get; set; }
        public Nullable<int> Contabilizzazione { get; set; }
        public Nullable<int> IDTipologiaContabilizzazione { get; set; }
        public Nullable<int> Termoregolazione { get; set; }
        public Nullable<int> CorrettoFunzionamentoContabilizzazione { get; set; }
        public string TipologiaSistemaDistribuzione { get; set; }
        public string TipologiaContabilizzazione { get; set; }
        public string JsonFormat { get; set; }
        public string Provincia { get; set; }
        public string GuidRapportoTecnico { get; set; }
        public string guidInteroImpianto { get; set; }
    }
}
