//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RCT_RapportoDiControlloTecnicoCG
    {
        public long IDRapportoControlloTecnico { get; set; }
        public int IDSoggetto { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public Nullable<int> IDSoggettoDerived { get; set; }
        public int IDTargaturaImpianto { get; set; }
        public Nullable<decimal> PotenzaTermicaNominale { get; set; }
        public string Indirizzo { get; set; }
        public string Civico { get; set; }
        public string Palazzo { get; set; }
        public string Scala { get; set; }
        public string Interno { get; set; }
        public Nullable<int> IDCodiceCatastale { get; set; }
        public int IDTipologiaRCT { get; set; }
        public int IDLibrettoImpianto { get; set; }
        public int IDStatoRapportoDiControllo { get; set; }
        public int IDTipologiaControllo { get; set; }
        public Nullable<int> IDTipologiaResponsabile { get; set; }
        public string NomeResponsabile { get; set; }
        public string CognomeResponsabile { get; set; }
        public string CodiceFiscaleResponsabile { get; set; }
        public string RagioneSocialeResponsabile { get; set; }
        public string PartitaIVAResponsabile { get; set; }
        public string IndirizzoResponsabile { get; set; }
        public string CivicoResponsabile { get; set; }
        public string ComuneResponsabile { get; set; }
        public Nullable<int> IDProvinciaResponsabile { get; set; }
        public string ProvinciaResponsabile { get; set; }
        public string RagioneSocialeTerzoResponsabile { get; set; }
        public string PartitaIVATerzoResponsabile { get; set; }
        public string IndirizzoTerzoResponsabile { get; set; }
        public string CivicoTerzoResponsabile { get; set; }
        public string ComuneTerzoResponsabile { get; set; }
        public Nullable<int> IDProvinciaTerzoResponsabile { get; set; }
        public string ProvinciaTerzoResponsabile { get; set; }
        public string RagioneSocialeImpresaManutentrice { get; set; }
        public string PartitaIVAImpresaManutentrice { get; set; }
        public string IndirizzoImpresaManutentrice { get; set; }
        public string CivicoImpresaManutentrice { get; set; }
        public string ComuneImpresaManutentrice { get; set; }
        public Nullable<int> IDProvinciaImpresaManutentrice { get; set; }
        public string ProvinciaImpresaManutentrice { get; set; }
        public Nullable<int> LocaleInstallazioneIdoneo { get; set; }
        public Nullable<decimal> PotenzaTermicaNominaleTotaleMax { get; set; }
        public bool fDichiarazioneConformita { get; set; }
        public bool fLibrettoImpiantoPresente { get; set; }
        public bool fUsoManutenzioneGeneratore { get; set; }
        public bool fLibrettoImpiantoCompilato { get; set; }
        public Nullable<decimal> DurezzaAcqua { get; set; }
        public Nullable<int> TrattamentoACS { get; set; }
        public Nullable<int> TrattamentoRiscaldamento { get; set; }
        public Nullable<int> ApertureLibere { get; set; }
        public Nullable<int> DimensioniApertureAdeguate { get; set; }
        public Nullable<int> LineeElettricheIdonee { get; set; }
        public Nullable<int> CoibentazioniIdonee { get; set; }
        public Nullable<int> AssenzaPerditeCombustibile { get; set; }
        public Nullable<int> TenutaImpiantoIdraulico { get; set; }
        public Nullable<int> ScarichiIdonei { get; set; }
        public string Prefisso { get; set; }
        public int CodiceProgressivo { get; set; }
        public Nullable<System.DateTime> DataInstallazione { get; set; }
        public string Fabbricante { get; set; }
        public string Modello { get; set; }
        public string Matricola { get; set; }
        public bool fClimatizzazioneInvernale { get; set; }
        public bool fProduzioneACS { get; set; }
        public bool fClimatizzazioneEstiva { get; set; }
        public Nullable<int> IDTipologiaCombustibile { get; set; }
        public string AltroCombustibile { get; set; }
        public string Osservazioni { get; set; }
        public string Raccomandazioni { get; set; }
        public string Prescrizioni { get; set; }
        public bool fImpiantoFunzionante { get; set; }
        public Nullable<System.DateTime> DataManutenzioneConsigliata { get; set; }
        public Nullable<System.DateTime> DataControllo { get; set; }
        public Nullable<System.DateTime> OraArrivo { get; set; }
        public Nullable<System.DateTime> OraPartenza { get; set; }
        public string DescrizioneRCT { get; set; }
        public string StatoRapportoDiControllo { get; set; }
        public string TipologiaResponsabile { get; set; }
        public string CodiceCatastale { get; set; }
        public string CodiceTargatura { get; set; }
        public Nullable<int> CapsulaInsonorizzataIdonea { get; set; }
        public Nullable<int> TenutaCircuitoOlioIdonea { get; set; }
        public Nullable<int> FunzionalitàScambiatoreSeparazione { get; set; }
        public Nullable<decimal> TemperaturaAriaComburente { get; set; }
        public Nullable<decimal> TemperaturaAcquaIngresso { get; set; }
        public Nullable<decimal> TemperaturaAcquauscita { get; set; }
        public Nullable<decimal> PotenzaAiMorsetti { get; set; }
        public Nullable<decimal> TemperaturaAcquaMotore { get; set; }
        public Nullable<decimal> TemperaturaFumiMonte { get; set; }
        public Nullable<decimal> TemperaturaFumiValle { get; set; }
        public Nullable<decimal> PotenzaElettricaMorsetti { get; set; }
        public Nullable<decimal> PotenzaAssorbitaCombustibile { get; set; }
        public Nullable<decimal> PotenzaMassimoRecupero { get; set; }
        public Nullable<decimal> PotenzaByPass { get; set; }
        public Nullable<decimal> EmissioneMonossido { get; set; }
        public Nullable<int> IdLIM_LibrettiImpiantiCogeneratori { get; set; }
        public Nullable<decimal> SovrafrequenzaSogliaInterv1 { get; set; }
        public Nullable<decimal> SovrafrequenzaSogliaInterv2 { get; set; }
        public Nullable<decimal> SovrafrequenzaSogliaInterv3 { get; set; }
        public Nullable<decimal> SovrafrequenzaTempoInterv1 { get; set; }
        public Nullable<decimal> SovrafrequenzaTempoInterv2 { get; set; }
        public Nullable<decimal> SovrafrequenzaTempoInterv3 { get; set; }
        public Nullable<decimal> SottofrequenzaSogliaInterv1 { get; set; }
        public Nullable<decimal> SottofrequenzaSogliaInterv2 { get; set; }
        public Nullable<decimal> SottofrequenzaSogliaInterv3 { get; set; }
        public Nullable<decimal> SottofrequenzaTempoInterv1 { get; set; }
        public Nullable<decimal> SottofrequenzaTempoInterv2 { get; set; }
        public Nullable<decimal> SottofrequenzaTempoInterv3 { get; set; }
        public Nullable<decimal> SovratensioneSogliaInterv1 { get; set; }
        public Nullable<decimal> SovratensioneSogliaInterv2 { get; set; }
        public Nullable<decimal> SovratensioneSogliaInterv3 { get; set; }
        public Nullable<decimal> SovratensioneTempoInterv1 { get; set; }
        public Nullable<decimal> SovratensioneTempoInterv2 { get; set; }
        public Nullable<decimal> SovratensioneTempoInterv3 { get; set; }
        public Nullable<decimal> SottotensioneSogliaInterv1 { get; set; }
        public Nullable<decimal> SottotensioneSogliaInterv2 { get; set; }
        public Nullable<decimal> SottotensioneSogliaInterv3 { get; set; }
        public Nullable<decimal> SottotensioneTempoInterv1 { get; set; }
        public Nullable<decimal> SottotensioneTempoInterv2 { get; set; }
        public Nullable<decimal> SottotensioneTempoInterv3 { get; set; }
        public Nullable<int> IDTipologiaCogeneratore { get; set; }
        public string TipologiaFluidoTermoVettore { get; set; }
        public string TipologiaCogeneratore { get; set; }
        public string TipologiaCombustibile { get; set; }
        public Nullable<int> StatoCoibentazioniIdonee { get; set; }
        public Nullable<int> IDTipoSoggetto { get; set; }
        public Nullable<int> IDTipologiaFluidoTermoVettoreUscita { get; set; }
        public string AltroTipologiaFluidoTermoVettoreUscita { get; set; }
        public Nullable<int> IDTipologiaSistemaDistribuzione { get; set; }
        public string AltroTipologiaSistemaDistribuzione { get; set; }
        public Nullable<int> Contabilizzazione { get; set; }
        public Nullable<int> IDTipologiaContabilizzazione { get; set; }
        public Nullable<int> Termoregolazione { get; set; }
        public Nullable<int> CorrettoFunzionamentoContabilizzazione { get; set; }
        public string TipologiaSistemaDistribuzione { get; set; }
        public string TipologiaContabilizzazione { get; set; }
        public string JsonFormat { get; set; }
        public string Provincia { get; set; }
        public string GuidRapportoTecnico { get; set; }
        public string guidInteroImpianto { get; set; }
    }
}
