//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SYS_ProvinceRegioni
    {
        public int IDProvincia { get; set; }
        public string SiglaProvincia { get; set; }
        public string Provincia { get; set; }
        public int IDRegione { get; set; }
        public bool fAttivo { get; set; }
        public string Regione { get; set; }
        public bool fProvinciaCompetenza { get; set; }
    }
}
