//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SYS_CodiciCatastali
    {
        public int IDCodiceCatastale { get; set; }
        public string Comune { get; set; }
        public Nullable<int> IDProvincia { get; set; }
        public string Provincia { get; set; }
        public bool fAttivo { get; set; }
        public string ZonaClimatica { get; set; }
        public Nullable<double> GradiGiorno { get; set; }
        public string CodiceCatastale { get; set; }
        public Nullable<System.DateTime> DataTermineBloccoRct { get; set; }
        public string EmailPec { get; set; }
        public string Cap { get; set; }
    }
}
