//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_VER_IspezioniStato
    {
        public long IDIspezioneStato { get; set; }
        public long IDIspezione { get; set; }
        public System.DateTime Data { get; set; }
        public int IDStatoIspezione { get; set; }
        public int IDUtenteUltimaModifica { get; set; }
        public string StatoIspezione { get; set; }
        public string Utente { get; set; }
        public Nullable<System.DateTime> DataIspezione { get; set; }
        public Nullable<int> IDOrarioDa { get; set; }
        public Nullable<int> IDOrarioA { get; set; }
        public string OrarioDa { get; set; }
        public string OrarioA { get; set; }
    }
}
