//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_VER_Ispezioni
    {
        public long IDIspezione { get; set; }
        public int IDSoggetto { get; set; }
        public long IDIspezioneVisita { get; set; }
        public string DescrizioneVisita { get; set; }
        public string CodiceIspezione { get; set; }
        public int IDStatoIspezione { get; set; }
        public Nullable<System.DateTime> DataIspezione { get; set; }
        public bool fIspezioneNonSvolta { get; set; }
        public Nullable<System.DateTime> DataIspezioneRipianificazione { get; set; }
        public bool fIspezioneNonSvolta2 { get; set; }
        public string NotaCoordinatore { get; set; }
        public bool fAttivo { get; set; }
        public string StatoIspezione { get; set; }
        public Nullable<long> IDAccertamento { get; set; }
        public int IDLibrettoImpianto { get; set; }
        public string NomeAzienda { get; set; }
        public string IndirizzoAzienda { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string EmailPec { get; set; }
        public string PartitaIVA { get; set; }
        public string CodiceTargatura { get; set; }
        public string Indirizzo { get; set; }
        public string Civico { get; set; }
        public string Comune { get; set; }
        public string SiglaProvincia { get; set; }
        public string CodiceSoggetto { get; set; }
        public string Telefono { get; set; }
        public string NomeResponsabile { get; set; }
        public string CognomeResponsabile { get; set; }
        public string RagioneSocialeResponsabile { get; set; }
        public string EmailResponsabile { get; set; }
        public string EmailPecResponsabile { get; set; }
        public string IndirizzoResponsabile { get; set; }
        public string CivicoResponsabile { get; set; }
        public string ProvinciaResponsabile { get; set; }
        public string ComuneResponsabile { get; set; }
        public string Note { get; set; }
        public string DescrizioneIspezione { get; set; }
        public long IDIspezioneVisitaInfo { get; set; }
        public bool fInIspezione { get; set; }
        public int IDTipoIspezione { get; set; }
        public string TipoIspezione { get; set; }
        public Nullable<int> IDIspettore { get; set; }
        public string Ispettore { get; set; }
        public string CodiceFiscaleIspettore { get; set; }
        public Nullable<int> IDLibrettoImpiantoGruppoTermico { get; set; }
        public Nullable<int> IDTipologiaCombustibile { get; set; }
        public Nullable<decimal> PotenzaTermicaUtileNominaleKw { get; set; }
        public Nullable<System.DateTime> DataInstallazione { get; set; }
        public string TipologiaCombustibile { get; set; }
        public int IDProgrammaIspezione { get; set; }
        public string Descrizione { get; set; }
        public Nullable<long> IDRapportoDiControllo { get; set; }
        public Nullable<decimal> PotenzaClimatizzazioneInvernale { get; set; }
        public Nullable<int> IDOrarioDa { get; set; }
        public Nullable<int> IDOrarioA { get; set; }
        public string OrarioDa { get; set; }
        public string OrarioA { get; set; }
        public string Osservatore { get; set; }
        public bool fIspezionePagamento { get; set; }
        public Nullable<decimal> CostoIspezione { get; set; }
        public bool fIspezioneRipianificata { get; set; }
        public Nullable<int> IDTipologiaGruppiTermici { get; set; }
        public string TipologiaGruppiTermici { get; set; }
        public string Prefisso { get; set; }
        public Nullable<int> CodiceProgressivo { get; set; }
        public Nullable<decimal> CompensoIspezione { get; set; }
        public string IndirizzoNormalizzatoResponsabile { get; set; }
        public string CapResponsabile { get; set; }
        public Nullable<System.DateTime> DataIspezionePrecedente { get; set; }
        public Nullable<int> IDOrarioDaPrecedente { get; set; }
        public Nullable<int> IDOrarioAPrecedente { get; set; }
        public string OrarioDaPrecedente { get; set; }
        public string OrarioAPrecedente { get; set; }
        public string CivicoNormalizzatoResponsabile { get; set; }
        public Nullable<bool> fTerzoResponsabile { get; set; }
        public string NomeTerzoResponsabile { get; set; }
        public string CognomeTerzoResponsabile { get; set; }
        public string RagioneSocialeTerzoResponsabile { get; set; }
        public string IndirizzoTerzoResponsabile { get; set; }
        public string CapTerzoResponsabile { get; set; }
        public string CittaTerzoResponsabile { get; set; }
        public string CivicoTerzoResponsabile { get; set; }
        public Nullable<int> IDProvinciaTerzoResponsabile { get; set; }
        public string ProvinciaTerzoResponsabile { get; set; }
        public string EmailTerzoResponsabile { get; set; }
        public string EmailPecTerzoResponsabile { get; set; }
        public Nullable<int> IDTargaturaImpianto { get; set; }
        public bool IsIspezioneSvolta { get; set; }
        public Nullable<int> IDSvolgimentoIspezione { get; set; }
        public bool IsPagamentoMai1 { get; set; }
        public bool IsPagamentoMai2 { get; set; }
        public string SvolgimentoIspezione { get; set; }
        public string AltroSvolgimentoIspezione { get; set; }
        public bool IsAvvisoPecTerzoResponsabile { get; set; }
        public string DettagliAvvisoPecTerzoResponsabile { get; set; }
        public string Osservazioni { get; set; }
        public string Raccomandazioni { get; set; }
        public string Prescrizioni { get; set; }
        public Nullable<bool> fImpiantoPuoFunzionare { get; set; }
        public string EmailIspettore { get; set; }
        public string EmailPecIspettore { get; set; }
        public string CellulareIspettore { get; set; }
    }
}
