//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_VER_Accertamenti
    {
        public long IDAccertamento { get; set; }
        public Nullable<long> IDRapportoDiControlloTecnicoBase { get; set; }
        public int IDStatoAccertamento { get; set; }
        public string CodiceAccertamento { get; set; }
        public System.DateTime DataRilevazione { get; set; }
        public int IDSoggetto { get; set; }
        public Nullable<int> IDUtenteAccertatore { get; set; }
        public string Accertatore { get; set; }
        public Nullable<int> IDUtenteCoordinatore { get; set; }
        public string Coordinatore { get; set; }
        public string Note { get; set; }
        public bool fAttivo { get; set; }
        public string CodiceSoggetto { get; set; }
        public string NomeAzienda { get; set; }
        public string IndirizzoAzienda { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string EmailPec { get; set; }
        public string PartitaIVA { get; set; }
        public string CodiceTargatura { get; set; }
        public string StatoAccertamento { get; set; }
        public int IDCodiceCatastale { get; set; }
        public string Comune { get; set; }
        public string SiglaProvincia { get; set; }
        public string EmailPecComune { get; set; }
        public Nullable<int> IDDistributore { get; set; }
        public string Distributore { get; set; }
        public string EmailPecDistributore { get; set; }
        public string GuidAccertamento { get; set; }
        public string TipologiaCombustibile { get; set; }
        public int IDTargaturaImpianto { get; set; }
        public string Prefisso { get; set; }
        public int CodiceProgressivo { get; set; }
        public Nullable<int> GiorniRealizzazioneInterventi { get; set; }
        public bool fEmailConfermaAccertamento { get; set; }
        public Nullable<System.DateTime> DataInvioEmail { get; set; }
        public string TestoEmail { get; set; }
        public string NomeLegaleRappresentante { get; set; }
        public string CognomeLegaleRappresentante { get; set; }
        public string RispostaEmail { get; set; }
        public Nullable<int> IDStatoAccertamentoIntervento { get; set; }
        public string StatoAccertamentoIntervento { get; set; }
        public Nullable<System.DateTime> DataInvioRaccomandata { get; set; }
        public Nullable<System.DateTime> DataRicevimentoRaccomandata { get; set; }
        public Nullable<System.DateTime> DataScadenzaIntervento { get; set; }
        public string NoteInterventi { get; set; }
        public string ProvinciaResponsabile { get; set; }
        public string ProvinciaTerzoResponsabile { get; set; }
        public Nullable<int> IDComuneResponsabile { get; set; }
        public string CapResponsabile { get; set; }
        public Nullable<int> IDTipoAccertamento { get; set; }
        public string TipoAccertamento { get; set; }
        public Nullable<long> IDIspezione { get; set; }
        public Nullable<int> PunteggioNCAccertamento { get; set; }
        public Nullable<int> IDUtenteAgenteAccertatore { get; set; }
        public string AgenteAccertatore { get; set; }
        public Nullable<int> IDProgrammaAccertamento { get; set; }
        public string ProgrammaAccertamento { get; set; }
        public Nullable<int> IDLibrettoImpianto { get; set; }
        public Nullable<int> IDTipologiaCombustibile { get; set; }
        public string Indirizzo { get; set; }
        public string Civico { get; set; }
        public string Palazzo { get; set; }
        public string Scala { get; set; }
        public string Interno { get; set; }
        public string NomeResponsabile { get; set; }
        public string CognomeResponsabile { get; set; }
        public string CodiceFiscaleResponsabile { get; set; }
        public string RagioneSocialeResponsabile { get; set; }
        public string IndirizzoResponsabile { get; set; }
        public string CivicoResponsabile { get; set; }
        public string ComuneResponsabile { get; set; }
        public Nullable<int> IDProvinciaResponsabile { get; set; }
        public Nullable<decimal> PotenzaTermicaNominale { get; set; }
        public string RagioneSocialeTerzoResponsabile { get; set; }
        public string IndirizzoTerzoResponsabile { get; set; }
        public string CivicoTerzoResponsabile { get; set; }
        public string ComuneTerzoResponsabile { get; set; }
        public string Osservazioni { get; set; }
        public string Raccomandazioni { get; set; }
        public string Prescrizioni { get; set; }
        public bool fImpiantoFunzionante { get; set; }
        public Nullable<System.DateTime> DataControllo { get; set; }
        public string PartitaIVATerzoResponsabile { get; set; }
        public string PartitaIvaResponsabile { get; set; }
        public Nullable<int> IDStatoAccertamentoSanzione { get; set; }
        public Nullable<System.DateTime> DataInvioSanzione { get; set; }
        public Nullable<System.DateTime> DataRicezioneSanzione { get; set; }
        public string StatoAccertamentoSanzione { get; set; }
        public Nullable<System.DateTime> DataScadenzaSanzione { get; set; }
        public Nullable<System.DateTime> DataRicevutaPagamento { get; set; }
        public string NoteSanzione { get; set; }
        public string IndirizzoNormalizzatoResponsabile { get; set; }
        public string CivicoNormalizzatoResponsabile { get; set; }
        public Nullable<bool> fTerzoResponsabile { get; set; }
        public string CapTerzoResponsabile { get; set; }
        public string CodiceSanzione { get; set; }
        public Nullable<System.DateTime> DataScadenzaPagamentoRidottoSanzione { get; set; }
        public bool IsSanzioneRevocata { get; set; }
        public string MotivoSanzioneRevocata { get; set; }
    }
}
