//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_VER_IspezioneDocumento
    {
        public long IDIspezioneDocumento { get; set; }
        public int IDTipoDocumentoIspezione { get; set; }
        public long IDIspezione { get; set; }
        public string TipoDocumentoIspezione { get; set; }
        public string NomeDocumentoIspezione { get; set; }
        public bool fAttivo { get; set; }
        public string Estensione { get; set; }
        public bool fDocumentoObbligatorio { get; set; }
        public bool fDocumentoCompilato { get; set; }
        public string NomeDocumento { get; set; }
    }
}
