//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_VER_AccertamentiStato
    {
        public long IDAccertamentoStato { get; set; }
        public long IDAccertamento { get; set; }
        public System.DateTime Data { get; set; }
        public int IDStatoAccertamento { get; set; }
        public string StatoAccertamento { get; set; }
        public Nullable<int> IDUtenteAccertatore { get; set; }
        public string Accertatore { get; set; }
        public Nullable<int> IDUtenteCoordinatore { get; set; }
        public string Coordinatore { get; set; }
        public int IDUtenteUltimaModifica { get; set; }
        public string Utente { get; set; }
        public Nullable<int> IDStatoAccertamentoIntervento { get; set; }
        public string StatoAccertamentoIntervento { get; set; }
    }
}
