//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_VER_AccertamentiProgramma
    {
        public long IDAccertamento { get; set; }
        public Nullable<long> IDRapportoDiControlloTecnicoBase { get; set; }
        public int IDStatoAccertamento { get; set; }
        public string CodiceAccertamento { get; set; }
        public System.DateTime DataRilevazione { get; set; }
        public Nullable<int> IDUtenteAccertatore { get; set; }
        public string Accertatore { get; set; }
        public Nullable<int> IDUtenteCoordinatore { get; set; }
        public string Coordinatore { get; set; }
        public string Note { get; set; }
        public bool fAttivo { get; set; }
        public Nullable<int> IDSoggetto { get; set; }
        public Nullable<int> IDTipologiaRCT { get; set; }
        public Nullable<int> IDLibrettoImpianto { get; set; }
        public Nullable<int> IDTipologiaControllo { get; set; }
        public Nullable<int> IDSoggettoDerived { get; set; }
        public string CodiceSoggetto { get; set; }
        public string NomeAzienda { get; set; }
        public string IndirizzoAzienda { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string EmailPec { get; set; }
        public string PartitaIVA { get; set; }
        public string CodiceTargatura { get; set; }
        public Nullable<bool> fImpiantoFunzionante { get; set; }
        public string Osservazioni { get; set; }
        public string Raccomandazioni { get; set; }
        public string Indirizzo { get; set; }
        public string Civico { get; set; }
        public string Palazzo { get; set; }
        public string Scala { get; set; }
        public string Interno { get; set; }
        public string StatoAccertamento { get; set; }
        public string Prescrizioni { get; set; }
        public int IDCodiceCatastale { get; set; }
        public string Comune { get; set; }
        public string SiglaProvincia { get; set; }
        public string EmailPecComune { get; set; }
        public Nullable<int> IDDistributore { get; set; }
        public string Distributore { get; set; }
        public string EmailPecDistributore { get; set; }
        public string GuidAccertamento { get; set; }
        public Nullable<decimal> PotenzaTermicaNominale { get; set; }
        public Nullable<int> IDTipologiaCombustibile { get; set; }
        public string TipologiaCombustibile { get; set; }
        public int IDTargaturaImpianto { get; set; }
        public string Prefisso { get; set; }
        public int CodiceProgressivo { get; set; }
        public Nullable<int> GiorniRealizzazioneInterventi { get; set; }
        public bool fEmailConfermaAccertamento { get; set; }
        public Nullable<System.DateTime> DataInvioEmail { get; set; }
        public string TestoEmail { get; set; }
        public string NomeLegaleRappresentante { get; set; }
        public string CognomeLegaleRappresentante { get; set; }
        public Nullable<System.DateTime> DataControllo { get; set; }
        public string NomeResponsabile { get; set; }
        public string CognomeResponsabile { get; set; }
        public string CodiceFiscaleResponsabile { get; set; }
        public string RispostaEmail { get; set; }
        public Nullable<int> IDStatoAccertamentoIntervento { get; set; }
        public string StatoAccertamentoIntervento { get; set; }
        public Nullable<System.DateTime> DataInvioRaccomandata { get; set; }
        public Nullable<System.DateTime> DataRicevimentoRaccomandata { get; set; }
        public Nullable<System.DateTime> DataScadenzaIntervento { get; set; }
        public string NoteInterventi { get; set; }
        public string RagioneSocialeResponsabile { get; set; }
        public string IndirizzoResponsabile { get; set; }
        public string CivicoResponsabile { get; set; }
        public string ComuneResponsabile { get; set; }
        public Nullable<int> IDProvinciaResponsabile { get; set; }
        public string ProvinciaResponsabile { get; set; }
        public string RagioneSocialeTerzoResponsabile { get; set; }
        public string IndirizzoTerzoResponsabile { get; set; }
        public string CivicoTerzoResponsabile { get; set; }
        public string ComuneTerzoResponsabile { get; set; }
        public string ProvinciaTerzoResponsabile { get; set; }
        public Nullable<int> IDComuneResponsabile { get; set; }
        public string CapResponsabile { get; set; }
        public Nullable<int> IDTipoAccertamento { get; set; }
        public string TipoAccertamento { get; set; }
        public Nullable<long> IDIspezione { get; set; }
        public Nullable<bool> fDichiarazioneConformita { get; set; }
        public Nullable<bool> fUsoManutenzioneGeneratore { get; set; }
        public Nullable<bool> fLibrettoImpiantoCompilato { get; set; }
        public Nullable<decimal> DurezzaAcqua { get; set; }
        public Nullable<int> TrattamentoRiscaldamento { get; set; }
        public Nullable<int> TrattamentoACS { get; set; }
        public Nullable<int> DimensioniApertureAdeguate { get; set; }
        public Nullable<int> LineeElettricheIdonee { get; set; }
        public Nullable<int> ScarichiIdonei { get; set; }
        public Nullable<int> ApertureLibere { get; set; }
        public Nullable<int> LocaleInstallazioneIdoneo { get; set; }
        public string AltroCombustibile { get; set; }
        public Nullable<int> TenutaImpiantoIdraulico { get; set; }
        public Nullable<int> AssenzaPerditeCombustibile { get; set; }
        public Nullable<int> Contabilizzazione { get; set; }
        public Nullable<int> Termoregolazione { get; set; }
        public Nullable<int> CorrettoFunzionamentoContabilizzazione { get; set; }
        public Nullable<int> GeneratoriIdonei { get; set; }
        public Nullable<int> RegolazioneTemperaturaAmbiente { get; set; }
        public Nullable<decimal> DepressioneCanaleFumo { get; set; }
        public Nullable<int> CapsulaInsonorizzataIdonea { get; set; }
        public Nullable<int> TenutaCircuitoOlioIdonea { get; set; }
        public Nullable<int> DispositiviComandoRegolazione { get; set; }
        public Nullable<int> DispositiviSicurezza { get; set; }
        public Nullable<int> ValvolaSicurezzaSovrappressione { get; set; }
        public Nullable<int> ScambiatoreFumiPulito { get; set; }
        public Nullable<int> RiflussoProdottiCombustione { get; set; }
        public Nullable<int> ConformitaUNI10389 { get; set; }
        public Nullable<decimal> CoCorretto { get; set; }
        public Nullable<decimal> RendimentoCombustione { get; set; }
        public Nullable<decimal> RendimentoMinimo { get; set; }
        public Nullable<bool> RispettaIndiceBacharach { get; set; }
        public Nullable<bool> COFumiSecchiNoAria1000 { get; set; }
        public Nullable<bool> RendimentoSupMinimo { get; set; }
        public Nullable<int> CoibentazioniIdonee { get; set; }
        public Nullable<int> StatoCoibentazioniIdonee { get; set; }
        public Nullable<int> AssenzaPerditeRefrigerante { get; set; }
        public Nullable<int> FiltriPuliti { get; set; }
        public Nullable<int> LeakDetector { get; set; }
        public Nullable<int> ScambiatoriLiberi { get; set; }
        public Nullable<int> ParametriTermodinamici { get; set; }
        public Nullable<int> PotenzaCompatibileProgetto { get; set; }
        public Nullable<int> AssenzaTrafilamenti { get; set; }
        public Nullable<int> FunzionalitàScambiatoreSeparazione { get; set; }
        public Nullable<int> PunteggioNCAccertamento { get; set; }
        public string CodiceIspezione { get; set; }
        public Nullable<System.DateTime> DataIspezione { get; set; }
        public string Ispettore { get; set; }
    }
}
