//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_VER_AccertamentoVisita
    {
        public long IDAccertamentoVisitaInfo { get; set; }
        public string DescrizioneAccertamentoVisita { get; set; }
        public int IDUtenteInserimento { get; set; }
        public System.DateTime DataInserimento { get; set; }
        public string CodiceCatastale { get; set; }
        public string Comune { get; set; }
        public string CodiceAccertamento { get; set; }
        public string NomeAzienda { get; set; }
        public string IndirizzoAzienda { get; set; }
        public string CodiceTargatura { get; set; }
        public string Indirizzo { get; set; }
        public Nullable<decimal> PotenzaTermicaNominale { get; set; }
        public string TipologiaCombustibile { get; set; }
        public string Prefisso { get; set; }
        public int CodiceProgressivo { get; set; }
        public long IDAccertamento { get; set; }
        public Nullable<System.DateTime> DataAssegnazione { get; set; }
        public Nullable<int> IDUtenteAssegnazione { get; set; }
        public long IDAccertamentoVisita { get; set; }
        public long IDAccertamentoProgramma { get; set; }
        public bool fPacchettoAssegnato { get; set; }
        public Nullable<int> PunteggioNCAccertamento { get; set; }
    }
}
