//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VER_ProgrammaIspezione
    {
        public VER_ProgrammaIspezione()
        {
            this.VER_IspezioneVisita = new HashSet<VER_IspezioneVisita>();
            this.VER_ProgrammaIspezioneInfo = new HashSet<VER_ProgrammaIspezioneInfo>();
        }
    
        public int IDProgrammaIspezione { get; set; }
        public string Descrizione { get; set; }
        public System.DateTime DataInizio { get; set; }
        public Nullable<System.DateTime> DataFine { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<VER_IspezioneVisita> VER_IspezioneVisita { get; set; }
        public virtual ICollection<VER_ProgrammaIspezioneInfo> VER_ProgrammaIspezioneInfo { get; set; }
    }
}
