//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VER_ProgrammaAccertamento
    {
        public VER_ProgrammaAccertamento()
        {
            this.VER_AccertamentoProgramma = new HashSet<VER_AccertamentoProgramma>();
            this.VER_AccertamentoVisita = new HashSet<VER_AccertamentoVisita>();
            this.VER_Accertamento = new HashSet<VER_Accertamento>();
        }
    
        public int IDProgrammaAccertamento { get; set; }
        public string Descrizione { get; set; }
        public System.DateTime DataInizio { get; set; }
        public System.DateTime DataFine { get; set; }
        public Nullable<int> IDTipoAccertamento { get; set; }
        public bool fAttivo { get; set; }
    
        public virtual ICollection<VER_AccertamentoProgramma> VER_AccertamentoProgramma { get; set; }
        public virtual ICollection<VER_AccertamentoVisita> VER_AccertamentoVisita { get; set; }
        public virtual SYS_TipoAccertamento SYS_TipoAccertamento { get; set; }
        public virtual ICollection<VER_Accertamento> VER_Accertamento { get; set; }
    }
}
