//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VER_RegoleControlli
    {
        public string RegolaControllo { get; set; }
        public int IDLibrettoImpianto { get; set; }
        public int IDLibrettoImpiantoGruppoTermico { get; set; }
        public int IDTargaturaImpianto { get; set; }
        public decimal ImportoIspezione { get; set; }
        public Nullable<decimal> PotenzaTermicaUtileNominaleKw { get; set; }
        public Nullable<int> IDTipologiaCombustibile { get; set; }
        public int IDTipologiaGruppiTermici { get; set; }
        public System.DateTime DataInserimento { get; set; }
    
        public virtual LIM_LibrettiImpiantiGruppiTermici LIM_LibrettiImpiantiGruppiTermici { get; set; }
        public virtual LIM_TargatureImpianti LIM_TargatureImpianti { get; set; }
        public virtual SYS_TipologiaCombustibile SYS_TipologiaCombustibile { get; set; }
        public virtual SYS_TipologiaGruppiTermici SYS_TipologiaGruppiTermici { get; set; }
        public virtual LIM_LibrettiImpianti LIM_LibrettiImpianti { get; set; }
    }
}
