//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VER_IspezioneStato
    {
        public long IDIspezioneStato { get; set; }
        public long IDIspezione { get; set; }
        public System.DateTime Data { get; set; }
        public Nullable<System.DateTime> DataIspezione { get; set; }
        public Nullable<int> IDOrarioDa { get; set; }
        public Nullable<int> IDOrarioA { get; set; }
        public int IDStatoIspezione { get; set; }
        public int IDUtenteUltimaModifica { get; set; }
    
        public virtual COM_Utenti COM_Utenti { get; set; }
        public virtual SYS_Orario SYS_Orario { get; set; }
        public virtual SYS_Orario SYS_Orario1 { get; set; }
        public virtual SYS_StatoIspezione SYS_StatoIspezione { get; set; }
        public virtual VER_Ispezione VER_Ispezione { get; set; }
    }
}
