//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VER_IspezioneRaccomandazioniPrescrizioni
    {
        public int IDRaccomandazioniPrescrizioniIspezione { get; set; }
        public long IDIspezione { get; set; }
        public int IDTipologiaRaccomandazionePrescrizioneIspezione { get; set; }
        public Nullable<int> IDTipologiaRaccomandazioneIspezione { get; set; }
        public Nullable<int> IDTipologiaPrescrizioneIspezione { get; set; }
    
        public virtual VER_Ispezione VER_Ispezione { get; set; }
    }
}
