//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VER_ProgrammaIspezioneInfo
    {
        public long IDProgrammaIspezioneInfo { get; set; }
        public Nullable<int> IDProgrammaIspezione { get; set; }
        public Nullable<long> IDAccertamento { get; set; }
        public Nullable<int> IDLibrettoImpianto { get; set; }
        public int IDTipoIspezione { get; set; }
        public bool fInVisitaIspettiva { get; set; }
        public Nullable<int> IDLibrettoImpiantoGruppoTermico { get; set; }
        public Nullable<int> IDTargaturaImpianto { get; set; }
        public Nullable<System.DateTime> DataInserimento { get; set; }
        public string NoteProgrammaIspezione { get; set; }
    
        public virtual SYS_TipoIspezione SYS_TipoIspezione { get; set; }
        public virtual VER_ProgrammaIspezione VER_ProgrammaIspezione { get; set; }
        public virtual LIM_LibrettiImpianti LIM_LibrettiImpianti { get; set; }
        public virtual VER_Accertamento VER_Accertamento { get; set; }
    }
}
