//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VER_IspezioneRapportoCheckList
    {
        public int IDIspezioneCheckList { get; set; }
        public long IDIspezione { get; set; }
        public int IDTipologiaCheckList { get; set; }
        public int IDTipoCheckList { get; set; }
    
        public virtual SYS_TipologiaIspezioneRapportoCheckList SYS_TipologiaIspezioneRapportoCheckList { get; set; }
        public virtual VER_IspezioneRapporto VER_IspezioneRapporto { get; set; }
    }
}
