//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VER_Accertamento
    {
        public VER_Accertamento()
        {
            this.VER_AccertamentoStato = new HashSet<VER_AccertamentoStato>();
            this.VER_AccertamentoDocumento = new HashSet<VER_AccertamentoDocumento>();
            this.VER_AccertamentoFirmaDigitale = new HashSet<VER_AccertamentoFirmaDigitale>();
            this.VER_AccertamentoNonConformita = new HashSet<VER_AccertamentoNonConformita>();
            this.VER_AccertamentoNote = new HashSet<VER_AccertamentoNote>();
            this.VER_AccertamentoProgramma = new HashSet<VER_AccertamentoProgramma>();
            this.VER_AccertamentoVisitaInfo = new HashSet<VER_AccertamentoVisitaInfo>();
            this.VER_ProgrammaIspezioneInfo = new HashSet<VER_ProgrammaIspezioneInfo>();
            this.COM_Raccomandate = new HashSet<COM_Raccomandate>();
        }
    
        public long IDAccertamento { get; set; }
        public Nullable<int> IDTipoAccertamento { get; set; }
        public string CodiceAccertamento { get; set; }
        public int IDSoggetto { get; set; }
        public Nullable<int> IDLibrettoImpianto { get; set; }
        public Nullable<long> IDRapportoDiControlloTecnicoBase { get; set; }
        public int IDTargaturaImpianto { get; set; }
        public string Prefisso { get; set; }
        public Nullable<int> IDTipologiaCombustibile { get; set; }
        public Nullable<decimal> PotenzaTermicaNominale { get; set; }
        public int CodiceProgressivo { get; set; }
        public Nullable<int> GiorniRealizzazioneInterventi { get; set; }
        public int IDStatoAccertamento { get; set; }
        public System.DateTime DataRilevazione { get; set; }
        public int IDCodiceCatastale { get; set; }
        public Nullable<int> IDDistributore { get; set; }
        public Nullable<int> IDUtenteAccertatore { get; set; }
        public Nullable<int> IDUtenteCoordinatore { get; set; }
        public string Note { get; set; }
        public bool fAttivo { get; set; }
        public string GuidAccertamento { get; set; }
        public bool fEmailConfermaAccertamento { get; set; }
        public Nullable<System.DateTime> DataInvioEmail { get; set; }
        public string TestoEmail { get; set; }
        public string RispostaEmail { get; set; }
        public Nullable<int> IDStatoAccertamentoIntervento { get; set; }
        public Nullable<System.DateTime> DataInvioRaccomandata { get; set; }
        public Nullable<System.DateTime> DataRicevimentoRaccomandata { get; set; }
        public Nullable<System.DateTime> DataScadenzaIntervento { get; set; }
        public string NoteInterventi { get; set; }
        public Nullable<long> IDIspezione { get; set; }
        public Nullable<int> PunteggioNCAccertamento { get; set; }
        public Nullable<int> IDUtenteAgenteAccertatore { get; set; }
        public Nullable<int> IDProgrammaAccertamento { get; set; }
        public string RagioneSocialeTerzoResponsabile { get; set; }
        public string PartitaIVATerzoResponsabile { get; set; }
        public string IndirizzoTerzoResponsabile { get; set; }
        public string CivicoTerzoResponsabile { get; set; }
        public string ComuneTerzoResponsabile { get; set; }
        public Nullable<int> IDProvinciaTerzoResponsabile { get; set; }
        public string Osservazioni { get; set; }
        public string Raccomandazioni { get; set; }
        public string Prescrizioni { get; set; }
        public bool fImpiantoFunzionante { get; set; }
        public Nullable<System.DateTime> DataControllo { get; set; }
        public Nullable<int> IDStatoAccertamentoSanzione { get; set; }
        public Nullable<System.DateTime> DataInvioSanzione { get; set; }
        public Nullable<System.DateTime> DataRicezioneSanzione { get; set; }
        public Nullable<System.DateTime> DataScadenzaSanzione { get; set; }
        public Nullable<System.DateTime> DataRicevutaPagamento { get; set; }
        public string NoteSanzione { get; set; }
        public string CapTerzoResponsabile { get; set; }
        public string CodiceSanzione { get; set; }
        public Nullable<System.DateTime> DataScadenzaPagamentoRidottoSanzione { get; set; }
        public bool IsSanzioneRevocata { get; set; }
        public string MotivoSanzioneRevocata { get; set; }
    
        public virtual COM_AnagraficaSoggetti COM_AnagraficaSoggetti { get; set; }
        public virtual COM_Utenti COM_Utenti { get; set; }
        public virtual COM_Utenti COM_Utenti1 { get; set; }
        public virtual COM_Utenti COM_Utenti2 { get; set; }
        public virtual LIM_LibrettiImpianti LIM_LibrettiImpianti { get; set; }
        public virtual LIM_TargatureImpianti LIM_TargatureImpianti { get; set; }
        public virtual RCT_RapportoDiControlloTecnicoBase RCT_RapportoDiControlloTecnicoBase { get; set; }
        public virtual SYS_CodiciCatastali SYS_CodiciCatastali { get; set; }
        public virtual SYS_StatoAccertamento SYS_StatoAccertamento { get; set; }
        public virtual SYS_StatoAccertamentoIntervento SYS_StatoAccertamentoIntervento { get; set; }
        public virtual SYS_StatoAccertamentoSanzione SYS_StatoAccertamentoSanzione { get; set; }
        public virtual SYS_TipoAccertamento SYS_TipoAccertamento { get; set; }
        public virtual SYS_TipologiaCombustibile SYS_TipologiaCombustibile { get; set; }
        public virtual SYS_TipologiaDistributori SYS_TipologiaDistributori { get; set; }
        public virtual ICollection<VER_AccertamentoStato> VER_AccertamentoStato { get; set; }
        public virtual VER_ProgrammaAccertamento VER_ProgrammaAccertamento { get; set; }
        public virtual ICollection<VER_AccertamentoDocumento> VER_AccertamentoDocumento { get; set; }
        public virtual ICollection<VER_AccertamentoFirmaDigitale> VER_AccertamentoFirmaDigitale { get; set; }
        public virtual ICollection<VER_AccertamentoNonConformita> VER_AccertamentoNonConformita { get; set; }
        public virtual ICollection<VER_AccertamentoNote> VER_AccertamentoNote { get; set; }
        public virtual ICollection<VER_AccertamentoProgramma> VER_AccertamentoProgramma { get; set; }
        public virtual ICollection<VER_AccertamentoVisitaInfo> VER_AccertamentoVisitaInfo { get; set; }
        public virtual ICollection<VER_ProgrammaIspezioneInfo> VER_ProgrammaIspezioneInfo { get; set; }
        public virtual VER_Ispezione VER_Ispezione { get; set; }
        public virtual ICollection<COM_Raccomandate> COM_Raccomandate { get; set; }
    }
}
