//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VER_IspezioneGruppoVerifica
    {
        public long IDIspezioneGruppoVerifica { get; set; }
        public long IDIspezioneVisita { get; set; }
        public int IDIspettore { get; set; }
        public int IDStatoPianificazioneIspettore { get; set; }
        public Nullable<int> NumeroVerificheEffettuate { get; set; }
        public Nullable<int> Distanza { get; set; }
        public Nullable<int> TempoPercorrenza { get; set; }
        public Nullable<decimal> PunteggioGraduatoria { get; set; }
        public string SecurityCode { get; set; }
        public Nullable<System.DateTime> DataInvioPianificazione { get; set; }
        public Nullable<System.DateTime> DataAccettazione { get; set; }
        public Nullable<System.DateTime> DataRifiuto { get; set; }
        public bool fInGruppoVerifica { get; set; }
        public bool fIspettorePrincipale { get; set; }
        public bool fEmailIncaricoInviata { get; set; }
        public bool fIncaricoFirmato { get; set; }
        public Nullable<System.DateTime> DataFirmaIncarico { get; set; }
    
        public virtual COM_AnagraficaSoggetti COM_AnagraficaSoggetti { get; set; }
        public virtual SYS_StatoPianificazioneIspettore SYS_StatoPianificazioneIspettore { get; set; }
        public virtual VER_IspezioneVisita VER_IspezioneVisita { get; set; }
    }
}
