//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VER_IspezioneVisitaInfo
    {
        public VER_IspezioneVisitaInfo()
        {
            this.VER_Ispezione = new HashSet<VER_Ispezione>();
        }
    
        public long IDIspezioneVisitaInfo { get; set; }
        public long IDIspezioneVisita { get; set; }
        public Nullable<long> IDAccertamento { get; set; }
        public int IDLibrettoImpianto { get; set; }
        public Nullable<int> IDLibrettoImpiantoGruppoTermico { get; set; }
        public int IDTipoIspezione { get; set; }
        public bool fInIspezione { get; set; }
        public bool fGeneratoreModificato { get; set; }
        public string GeneratoreModificatoDettagli { get; set; }
        public string NoteIspezioneVisita { get; set; }
        public string NoteProgrammaIspezione { get; set; }
    
        public virtual SYS_TipoIspezione SYS_TipoIspezione { get; set; }
        public virtual VER_IspezioneVisita VER_IspezioneVisita { get; set; }
        public virtual ICollection<VER_Ispezione> VER_Ispezione { get; set; }
    }
}
