//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VER_AccertamentoFirmaDigitale
    {
        public int IDFirmaDigitale { get; set; }
        public long IDAccertamento { get; set; }
        public int IDSoggetto { get; set; }
        public string Documento { get; set; }
        public System.DateTime DataFirma { get; set; }
        public string IPClient { get; set; }
        public string SignerQualifier { get; set; }
        public string SignerName { get; set; }
        public string SignerSurname { get; set; }
        public string SignerIdentifier { get; set; }
        public string SignerFullName { get; set; }
        public string SignerAuthority { get; set; }
        public string SignerCertificationAuthority { get; set; }
        public string SignerSerialNumber { get; set; }
    
        public virtual VER_Accertamento VER_Accertamento { get; set; }
    }
}
