//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VER_IspezioneQuestinarioQualita
    {
        public long IDIspezione { get; set; }
        public Nullable<int> IndiceTempisticheConclusioneVerifica { get; set; }
        public Nullable<int> IndiceCompletezzaRvi { get; set; }
        public Nullable<int> IndiceReclami { get; set; }
        public Nullable<int> IspezioneNonEffettuataOption { get; set; }
        public bool IsIspezioneEffettuataNoAnalisi { get; set; }
        public bool IsIspezioneEffettuataRitardoConsegnaRvi { get; set; }
        public bool IsIspezioneEffettuataRitardoComunicazione { get; set; }
        public bool IsIspezioneEffettuataRitardoAppuntamento { get; set; }
        public bool IsIspezioneEffettuataMancataDocumentazione { get; set; }
        public bool IsIspezioneNonEffettuataMAI1 { get; set; }
        public bool IsIspezioneNonEffettuataMAI2 { get; set; }
        public Nullable<decimal> CostoFinale { get; set; }
        public Nullable<int> TrimestreFatturazione { get; set; }
        public bool IsDefinitivo { get; set; }
        public System.DateTime DataUltimaModifica { get; set; }
        public int IDUtenteUltimaModifica { get; set; }
    
        public virtual VER_Ispezione VER_Ispezione { get; set; }
    }
}
