//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VER_AccertamentoVisita
    {
        public VER_AccertamentoVisita()
        {
            this.VER_AccertamentoVisitaInfo = new HashSet<VER_AccertamentoVisitaInfo>();
        }
    
        public long IDAccertamentoVisita { get; set; }
        public int IDProgrammaAccertamento { get; set; }
        public string DescrizioneAccertamentoVisita { get; set; }
        public System.DateTime DataCreazione { get; set; }
        public bool fPacchettoAssegnato { get; set; }
        public Nullable<System.DateTime> DataAssegnazione { get; set; }
        public Nullable<int> IDUtenteAssegnazione { get; set; }
        public Nullable<int> IDAccertatore { get; set; }
    
        public virtual COM_Utenti COM_Utenti { get; set; }
        public virtual ICollection<VER_AccertamentoVisitaInfo> VER_AccertamentoVisitaInfo { get; set; }
        public virtual VER_ProgrammaAccertamento VER_ProgrammaAccertamento { get; set; }
    }
}
