//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VER_IspezioneRapportoStrumenti
    {
        public int IDIspezioneStrumenti { get; set; }
        public long IDIspezione { get; set; }
        public string Tipologia { get; set; }
        public string Matricola { get; set; }
        public string TipologiaMisurazione { get; set; }
        public string CertificatoTaratura { get; set; }
        public Nullable<System.DateTime> DataScadenzaCertificato { get; set; }
    
        public virtual VER_IspezioneRapporto VER_IspezioneRapporto { get; set; }
    }
}
