//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VER_AccertamentoProgramma
    {
        public VER_AccertamentoProgramma()
        {
            this.VER_AccertamentoVisitaInfo = new HashSet<VER_AccertamentoVisitaInfo>();
        }
    
        public long IDAccertamentoProgramma { get; set; }
        public int IDProgrammaAccertamento { get; set; }
        public long IDAccertamento { get; set; }
        public int IDUtenteInserimento { get; set; }
        public System.DateTime DataInserimento { get; set; }
    
        public virtual COM_Utenti COM_Utenti { get; set; }
        public virtual ICollection<VER_AccertamentoVisitaInfo> VER_AccertamentoVisitaInfo { get; set; }
        public virtual VER_ProgrammaAccertamento VER_ProgrammaAccertamento { get; set; }
        public virtual VER_Accertamento VER_Accertamento { get; set; }
    }
}
