//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaLib.WSFirma {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cxf.ws.omnys.com/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cxf.ws.omnys.com/")]
    public partial class beanDssCreaTransazioneFirma : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string htmlPageField;
        
        private string htmlPageUrlField;
        
        private string[] listUrlDataToSignField;
        
        private string pinField;
        
        private string policyIdField;
        
        private int returnCodeField;
        
        private string returnMessageField;
        
        private long sessionIdField;
        
        private string signerCnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string htmlPage {
            get {
                return this.htmlPageField;
            }
            set {
                this.htmlPageField = value;
                this.RaisePropertyChanged("htmlPage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string htmlPageUrl {
            get {
                return this.htmlPageUrlField;
            }
            set {
                this.htmlPageUrlField = value;
                this.RaisePropertyChanged("htmlPageUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listUrlDataToSign", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string[] listUrlDataToSign {
            get {
                return this.listUrlDataToSignField;
            }
            set {
                this.listUrlDataToSignField = value;
                this.RaisePropertyChanged("listUrlDataToSign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string pin {
            get {
                return this.pinField;
            }
            set {
                this.pinField = value;
                this.RaisePropertyChanged("pin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string policyId {
            get {
                return this.policyIdField;
            }
            set {
                this.policyIdField = value;
                this.RaisePropertyChanged("policyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("returnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string returnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
                this.RaisePropertyChanged("returnMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public long sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
                this.RaisePropertyChanged("sessionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string signerCn {
            get {
                return this.signerCnField;
            }
            set {
                this.signerCnField = value;
                this.RaisePropertyChanged("signerCn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cxf.ws.omnys.com/", ConfigurationName="WSFirma.WSFirma")]
    public interface WSFirma {
        
        // CODEGEN: Parameter 'CreaTransazioneFirmaResponse' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(FirmaLib.WSFirma.IOException), Action="", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CreaTransazioneFirmaResponse")]
        FirmaLib.WSFirma.creaTransazioneFirmaResponse creaTransazioneFirma(FirmaLib.WSFirma.creaTransazioneFirma request);
        
        // CODEGEN: Parameter 'cleanUpResponse' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cleanUpResponse")]
        FirmaLib.WSFirma.cleanUpResponse cleanUp(FirmaLib.WSFirma.cleanUp request);
        
        // CODEGEN: Parameter 'CompletaTransazioneFirmaResponse' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CompletaTransazioneFirmaResponse")]
        FirmaLib.WSFirma.completaTransazioneFirmaResponse completaTransazioneFirma(FirmaLib.WSFirma.completaTransazioneFirma request);
        
        // CODEGEN: Parameter 'CreaTransazioneVerificaResponse' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(FirmaLib.WSFirma.IOException), Action="", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CreaTransazioneVerificaResponse")]
        FirmaLib.WSFirma.creaTransazioneVerificaResponse creaTransazioneVerifica(FirmaLib.WSFirma.creaTransazioneVerifica request);
        
        // CODEGEN: Parameter 'ControllaTransazioneFirmaResponse' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ControllaTransazioneFirmaResponse")]
        FirmaLib.WSFirma.controllaTransazioneFirmaResponse controllaTransazioneFirma(FirmaLib.WSFirma.controllaTransazioneFirma request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="creaTransazioneFirma", WrapperNamespace="http://cxf.ws.omnys.com/", IsWrapped=true)]
    public partial class creaTransazioneFirma {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cxf.ws.omnys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string policyFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cxf.ws.omnys.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cxf.ws.omnys.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signerCn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cxf.ws.omnys.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cxf.ws.omnys.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("files", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] files;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cxf.ws.omnys.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("b64Files", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[][] b64Files;
        
        public creaTransazioneFirma() {
        }
        
        public creaTransazioneFirma(string policyFileName, long sessionId, string signerCn, string pin, string[] files, byte[][] b64Files) {
            this.policyFileName = policyFileName;
            this.sessionId = sessionId;
            this.signerCn = signerCn;
            this.pin = pin;
            this.files = files;
            this.b64Files = b64Files;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="creaTransazioneFirmaResponse", WrapperNamespace="http://cxf.ws.omnys.com/", IsWrapped=true)]
    public partial class creaTransazioneFirmaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreaTransazioneFirmaResponse", Namespace="http://cxf.ws.omnys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FirmaLib.WSFirma.beanDssCreaTransazioneFirma CreaTransazioneFirmaResponse1;
        
        public creaTransazioneFirmaResponse() {
        }
        
        public creaTransazioneFirmaResponse(FirmaLib.WSFirma.beanDssCreaTransazioneFirma CreaTransazioneFirmaResponse1) {
            this.CreaTransazioneFirmaResponse1 = CreaTransazioneFirmaResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cleanUp", WrapperNamespace="http://cxf.ws.omnys.com/", IsWrapped=true)]
    public partial class cleanUp {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cxf.ws.omnys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long sessionId;
        
        public cleanUp() {
        }
        
        public cleanUp(long sessionId) {
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cleanUpResponse", WrapperNamespace="http://cxf.ws.omnys.com/", IsWrapped=true)]
    public partial class cleanUpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cleanUpResponse", Namespace="http://cxf.ws.omnys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool cleanUpResponse1;
        
        public cleanUpResponse() {
        }
        
        public cleanUpResponse(bool cleanUpResponse1) {
            this.cleanUpResponse1 = cleanUpResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cxf.ws.omnys.com/")]
    public partial class beanDssCompletaTransazioneFirma : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] certificatoField;
        
        private beanDssCompletaTransazioneFirmaItem[] firmeField;
        
        private byte[] hashCertificatoField;
        
        private string issuerField;
        
        private int returnCodeField;
        
        private string returnMessageField;
        
        private long sessionIdField;
        
        private string subjectCnField;
        
        private string subjectDnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] certificato {
            get {
                return this.certificatoField;
            }
            set {
                this.certificatoField = value;
                this.RaisePropertyChanged("certificato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("firme", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public beanDssCompletaTransazioneFirmaItem[] firme {
            get {
                return this.firmeField;
            }
            set {
                this.firmeField = value;
                this.RaisePropertyChanged("firme");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
        public byte[] hashCertificato {
            get {
                return this.hashCertificatoField;
            }
            set {
                this.hashCertificatoField = value;
                this.RaisePropertyChanged("hashCertificato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string issuer {
            get {
                return this.issuerField;
            }
            set {
                this.issuerField = value;
                this.RaisePropertyChanged("issuer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("returnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string returnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
                this.RaisePropertyChanged("returnMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
                this.RaisePropertyChanged("sessionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string subjectCn {
            get {
                return this.subjectCnField;
            }
            set {
                this.subjectCnField = value;
                this.RaisePropertyChanged("subjectCn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string subjectDn {
            get {
                return this.subjectDnField;
            }
            set {
                this.subjectDnField = value;
                this.RaisePropertyChanged("subjectDn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cxf.ws.omnys.com/")]
    public partial class beanDssCompletaTransazioneFirmaItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dataFirmaField;
        
        private bool dataFirmaFieldSpecified;
        
        private int esitoField;
        
        private string esitoMsgField;
        
        private byte[] originalDataField;
        
        private string recFileNameField;
        
        private byte[] signedDataField;
        
        private string signedDataFileNameField;
        
        private string tokenLdocField;
        
        private string tstFileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime dataFirma {
            get {
                return this.dataFirmaField;
            }
            set {
                this.dataFirmaField = value;
                this.RaisePropertyChanged("dataFirma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataFirmaSpecified {
            get {
                return this.dataFirmaFieldSpecified;
            }
            set {
                this.dataFirmaFieldSpecified = value;
                this.RaisePropertyChanged("dataFirmaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int esito {
            get {
                return this.esitoField;
            }
            set {
                this.esitoField = value;
                this.RaisePropertyChanged("esito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string esitoMsg {
            get {
                return this.esitoMsgField;
            }
            set {
                this.esitoMsgField = value;
                this.RaisePropertyChanged("esitoMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=3)]
        public byte[] originalData {
            get {
                return this.originalDataField;
            }
            set {
                this.originalDataField = value;
                this.RaisePropertyChanged("originalData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string recFileName {
            get {
                return this.recFileNameField;
            }
            set {
                this.recFileNameField = value;
                this.RaisePropertyChanged("recFileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=5)]
        public byte[] signedData {
            get {
                return this.signedDataField;
            }
            set {
                this.signedDataField = value;
                this.RaisePropertyChanged("signedData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string signedDataFileName {
            get {
                return this.signedDataFileNameField;
            }
            set {
                this.signedDataFileNameField = value;
                this.RaisePropertyChanged("signedDataFileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string tokenLdoc {
            get {
                return this.tokenLdocField;
            }
            set {
                this.tokenLdocField = value;
                this.RaisePropertyChanged("tokenLdoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string tstFileName {
            get {
                return this.tstFileNameField;
            }
            set {
                this.tstFileNameField = value;
                this.RaisePropertyChanged("tstFileName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="completaTransazioneFirma", WrapperNamespace="http://cxf.ws.omnys.com/", IsWrapped=true)]
    public partial class completaTransazioneFirma {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cxf.ws.omnys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long sessionId;
        
        public completaTransazioneFirma() {
        }
        
        public completaTransazioneFirma(long sessionId) {
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="completaTransazioneFirmaResponse", WrapperNamespace="http://cxf.ws.omnys.com/", IsWrapped=true)]
    public partial class completaTransazioneFirmaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CompletaTransazioneFirmaResponse", Namespace="http://cxf.ws.omnys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FirmaLib.WSFirma.beanDssCompletaTransazioneFirma CompletaTransazioneFirmaResponse1;
        
        public completaTransazioneFirmaResponse() {
        }
        
        public completaTransazioneFirmaResponse(FirmaLib.WSFirma.beanDssCompletaTransazioneFirma CompletaTransazioneFirmaResponse1) {
            this.CompletaTransazioneFirmaResponse1 = CompletaTransazioneFirmaResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cxf.ws.omnys.com/")]
    public partial class beanDssCreaTransazioneVerifica : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] listUrlDataToSignField;
        
        private string pinField;
        
        private string policyIdField;
        
        private int returnCodeField;
        
        private bool returnCodeFieldSpecified;
        
        private string returnMessageField;
        
        private long sessionIdField;
        
        private string signerCnField;
        
        private beanDssCreaTransazioneVerificaData[] verifyDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listUrlDataToSign", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string[] listUrlDataToSign {
            get {
                return this.listUrlDataToSignField;
            }
            set {
                this.listUrlDataToSignField = value;
                this.RaisePropertyChanged("listUrlDataToSign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string pin {
            get {
                return this.pinField;
            }
            set {
                this.pinField = value;
                this.RaisePropertyChanged("pin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string policyId {
            get {
                return this.policyIdField;
            }
            set {
                this.policyIdField = value;
                this.RaisePropertyChanged("policyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("returnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnCodeSpecified {
            get {
                return this.returnCodeFieldSpecified;
            }
            set {
                this.returnCodeFieldSpecified = value;
                this.RaisePropertyChanged("returnCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string returnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
                this.RaisePropertyChanged("returnMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
                this.RaisePropertyChanged("sessionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string signerCn {
            get {
                return this.signerCnField;
            }
            set {
                this.signerCnField = value;
                this.RaisePropertyChanged("signerCn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("verifyData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public beanDssCreaTransazioneVerificaData[] verifyData {
            get {
                return this.verifyDataField;
            }
            set {
                this.verifyDataField = value;
                this.RaisePropertyChanged("verifyData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cxf.ws.omnys.com/")]
    public partial class beanDssCreaTransazioneVerificaData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentMessageField;
        
        private string documentNameField;
        
        private beanDssCreaTransazioneVerificaSignatureInfo[] signatureInfoField;
        
        private bool signedField;
        
        private bool signedFieldSpecified;
        
        private bool validField;
        
        private bool validFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string documentMessage {
            get {
                return this.documentMessageField;
            }
            set {
                this.documentMessageField = value;
                this.RaisePropertyChanged("documentMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string documentName {
            get {
                return this.documentNameField;
            }
            set {
                this.documentNameField = value;
                this.RaisePropertyChanged("documentName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("signatureInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public beanDssCreaTransazioneVerificaSignatureInfo[] signatureInfo {
            get {
                return this.signatureInfoField;
            }
            set {
                this.signatureInfoField = value;
                this.RaisePropertyChanged("signatureInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool signed {
            get {
                return this.signedField;
            }
            set {
                this.signedField = value;
                this.RaisePropertyChanged("signed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool signedSpecified {
            get {
                return this.signedFieldSpecified;
            }
            set {
                this.signedFieldSpecified = value;
                this.RaisePropertyChanged("signedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
                this.RaisePropertyChanged("valid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validSpecified {
            get {
                return this.validFieldSpecified;
            }
            set {
                this.validFieldSpecified = value;
                this.RaisePropertyChanged("validSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cxf.ws.omnys.com/")]
    public partial class beanDssCreaTransazioneVerificaSignatureInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string certificateB64Field;
        
        private bool isTimeStampedField;
        
        private bool isTimeStampedFieldSpecified;
        
        private string issuerDnField;
        
        private string revocationControlField;
        
        private string revocationTimeStampField;
        
        private string signatureTimeField;
        
        private string subjectCnField;
        
        private string subjectDnField;
        
        private string subjectEmailField;
        
        private bool verifiedField;
        
        private bool verifiedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string certificateB64 {
            get {
                return this.certificateB64Field;
            }
            set {
                this.certificateB64Field = value;
                this.RaisePropertyChanged("certificateB64");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool isTimeStamped {
            get {
                return this.isTimeStampedField;
            }
            set {
                this.isTimeStampedField = value;
                this.RaisePropertyChanged("isTimeStamped");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isTimeStampedSpecified {
            get {
                return this.isTimeStampedFieldSpecified;
            }
            set {
                this.isTimeStampedFieldSpecified = value;
                this.RaisePropertyChanged("isTimeStampedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string issuerDn {
            get {
                return this.issuerDnField;
            }
            set {
                this.issuerDnField = value;
                this.RaisePropertyChanged("issuerDn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string revocationControl {
            get {
                return this.revocationControlField;
            }
            set {
                this.revocationControlField = value;
                this.RaisePropertyChanged("revocationControl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string revocationTimeStamp {
            get {
                return this.revocationTimeStampField;
            }
            set {
                this.revocationTimeStampField = value;
                this.RaisePropertyChanged("revocationTimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string signatureTime {
            get {
                return this.signatureTimeField;
            }
            set {
                this.signatureTimeField = value;
                this.RaisePropertyChanged("signatureTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string subjectCn {
            get {
                return this.subjectCnField;
            }
            set {
                this.subjectCnField = value;
                this.RaisePropertyChanged("subjectCn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string subjectDn {
            get {
                return this.subjectDnField;
            }
            set {
                this.subjectDnField = value;
                this.RaisePropertyChanged("subjectDn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string subjectEmail {
            get {
                return this.subjectEmailField;
            }
            set {
                this.subjectEmailField = value;
                this.RaisePropertyChanged("subjectEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public bool verified {
            get {
                return this.verifiedField;
            }
            set {
                this.verifiedField = value;
                this.RaisePropertyChanged("verified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool verifiedSpecified {
            get {
                return this.verifiedFieldSpecified;
            }
            set {
                this.verifiedFieldSpecified = value;
                this.RaisePropertyChanged("verifiedSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="creaTransazioneVerifica", WrapperNamespace="http://cxf.ws.omnys.com/", IsWrapped=true)]
    public partial class creaTransazioneVerifica {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cxf.ws.omnys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string policyFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cxf.ws.omnys.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cxf.ws.omnys.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signerCn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cxf.ws.omnys.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cxf.ws.omnys.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("files", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] files;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cxf.ws.omnys.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("b64Files", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[][] b64Files;
        
        public creaTransazioneVerifica() {
        }
        
        public creaTransazioneVerifica(string policyFileName, long sessionId, string signerCn, string pin, string[] files, byte[][] b64Files) {
            this.policyFileName = policyFileName;
            this.sessionId = sessionId;
            this.signerCn = signerCn;
            this.pin = pin;
            this.files = files;
            this.b64Files = b64Files;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="creaTransazioneVerificaResponse", WrapperNamespace="http://cxf.ws.omnys.com/", IsWrapped=true)]
    public partial class creaTransazioneVerificaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreaTransazioneVerificaResponse", Namespace="http://cxf.ws.omnys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FirmaLib.WSFirma.beanDssCreaTransazioneVerifica CreaTransazioneVerificaResponse1;
        
        public creaTransazioneVerificaResponse() {
        }
        
        public creaTransazioneVerificaResponse(FirmaLib.WSFirma.beanDssCreaTransazioneVerifica CreaTransazioneVerificaResponse1) {
            this.CreaTransazioneVerificaResponse1 = CreaTransazioneVerificaResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cxf.ws.omnys.com/")]
    public partial class beanDssControllaTransazioneFirma : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] b64p7mField;
        
        private string policyIdField;
        
        private int returnCodeField;
        
        private string returnMessageField;
        
        private long sessionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] b64p7m {
            get {
                return this.b64p7mField;
            }
            set {
                this.b64p7mField = value;
                this.RaisePropertyChanged("b64p7m");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string policyId {
            get {
                return this.policyIdField;
            }
            set {
                this.policyIdField = value;
                this.RaisePropertyChanged("policyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("returnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string returnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
                this.RaisePropertyChanged("returnMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
                this.RaisePropertyChanged("sessionId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="controllaTransazioneFirma", WrapperNamespace="http://cxf.ws.omnys.com/", IsWrapped=true)]
    public partial class controllaTransazioneFirma {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cxf.ws.omnys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string policyFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cxf.ws.omnys.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cxf.ws.omnys.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] b64Files;
        
        public controllaTransazioneFirma() {
        }
        
        public controllaTransazioneFirma(string policyFileName, long sessionId, byte[] b64Files) {
            this.policyFileName = policyFileName;
            this.sessionId = sessionId;
            this.b64Files = b64Files;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="controllaTransazioneFirmaResponse", WrapperNamespace="http://cxf.ws.omnys.com/", IsWrapped=true)]
    public partial class controllaTransazioneFirmaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ControllaTransazioneFirmaResponse", Namespace="http://cxf.ws.omnys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FirmaLib.WSFirma.beanDssControllaTransazioneFirma ControllaTransazioneFirmaResponse1;
        
        public controllaTransazioneFirmaResponse() {
        }
        
        public controllaTransazioneFirmaResponse(FirmaLib.WSFirma.beanDssControllaTransazioneFirma ControllaTransazioneFirmaResponse1) {
            this.ControllaTransazioneFirmaResponse1 = ControllaTransazioneFirmaResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSFirmaChannel : FirmaLib.WSFirma.WSFirma, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSFirmaClient : System.ServiceModel.ClientBase<FirmaLib.WSFirma.WSFirma>, FirmaLib.WSFirma.WSFirma {
        
        public WSFirmaClient() {
        }
        
        public WSFirmaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSFirmaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSFirmaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSFirmaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FirmaLib.WSFirma.creaTransazioneFirmaResponse FirmaLib.WSFirma.WSFirma.creaTransazioneFirma(FirmaLib.WSFirma.creaTransazioneFirma request) {
            return base.Channel.creaTransazioneFirma(request);
        }
        
        public FirmaLib.WSFirma.beanDssCreaTransazioneFirma creaTransazioneFirma(string policyFileName, long sessionId, string signerCn, string pin, string[] files, byte[][] b64Files) {
            FirmaLib.WSFirma.creaTransazioneFirma inValue = new FirmaLib.WSFirma.creaTransazioneFirma();
            inValue.policyFileName = policyFileName;
            inValue.sessionId = sessionId;
            inValue.signerCn = signerCn;
            inValue.pin = pin;
            inValue.files = files;
            inValue.b64Files = b64Files;
            FirmaLib.WSFirma.creaTransazioneFirmaResponse retVal = ((FirmaLib.WSFirma.WSFirma)(this)).creaTransazioneFirma(inValue);
            return retVal.CreaTransazioneFirmaResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FirmaLib.WSFirma.cleanUpResponse FirmaLib.WSFirma.WSFirma.cleanUp(FirmaLib.WSFirma.cleanUp request) {
            return base.Channel.cleanUp(request);
        }
        
        public bool cleanUp(long sessionId) {
            FirmaLib.WSFirma.cleanUp inValue = new FirmaLib.WSFirma.cleanUp();
            inValue.sessionId = sessionId;
            FirmaLib.WSFirma.cleanUpResponse retVal = ((FirmaLib.WSFirma.WSFirma)(this)).cleanUp(inValue);
            return retVal.cleanUpResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FirmaLib.WSFirma.completaTransazioneFirmaResponse FirmaLib.WSFirma.WSFirma.completaTransazioneFirma(FirmaLib.WSFirma.completaTransazioneFirma request) {
            return base.Channel.completaTransazioneFirma(request);
        }
        
        public FirmaLib.WSFirma.beanDssCompletaTransazioneFirma completaTransazioneFirma(long sessionId) {
            FirmaLib.WSFirma.completaTransazioneFirma inValue = new FirmaLib.WSFirma.completaTransazioneFirma();
            inValue.sessionId = sessionId;
            FirmaLib.WSFirma.completaTransazioneFirmaResponse retVal = ((FirmaLib.WSFirma.WSFirma)(this)).completaTransazioneFirma(inValue);
            return retVal.CompletaTransazioneFirmaResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FirmaLib.WSFirma.creaTransazioneVerificaResponse FirmaLib.WSFirma.WSFirma.creaTransazioneVerifica(FirmaLib.WSFirma.creaTransazioneVerifica request) {
            return base.Channel.creaTransazioneVerifica(request);
        }
        
        public FirmaLib.WSFirma.beanDssCreaTransazioneVerifica creaTransazioneVerifica(string policyFileName, long sessionId, string signerCn, string pin, string[] files, byte[][] b64Files) {
            FirmaLib.WSFirma.creaTransazioneVerifica inValue = new FirmaLib.WSFirma.creaTransazioneVerifica();
            inValue.policyFileName = policyFileName;
            inValue.sessionId = sessionId;
            inValue.signerCn = signerCn;
            inValue.pin = pin;
            inValue.files = files;
            inValue.b64Files = b64Files;
            FirmaLib.WSFirma.creaTransazioneVerificaResponse retVal = ((FirmaLib.WSFirma.WSFirma)(this)).creaTransazioneVerifica(inValue);
            return retVal.CreaTransazioneVerificaResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FirmaLib.WSFirma.controllaTransazioneFirmaResponse FirmaLib.WSFirma.WSFirma.controllaTransazioneFirma(FirmaLib.WSFirma.controllaTransazioneFirma request) {
            return base.Channel.controllaTransazioneFirma(request);
        }
        
        public FirmaLib.WSFirma.beanDssControllaTransazioneFirma controllaTransazioneFirma(string policyFileName, long sessionId, byte[] b64Files) {
            FirmaLib.WSFirma.controllaTransazioneFirma inValue = new FirmaLib.WSFirma.controllaTransazioneFirma();
            inValue.policyFileName = policyFileName;
            inValue.sessionId = sessionId;
            inValue.b64Files = b64Files;
            FirmaLib.WSFirma.controllaTransazioneFirmaResponse retVal = ((FirmaLib.WSFirma.WSFirma)(this)).controllaTransazioneFirma(inValue);
            return retVal.ControllaTransazioneFirmaResponse1;
        }
    }
}
